// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Test message for the OCSF JSON exporter. DO NOT USE in production.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: sample.proto

package samplev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SeverityId is an OCSF-style integer-keyed enum.
type SampleEvent_SeverityId int32

const (
	SampleEvent_SEVERITY_ID_UNKNOWN  SampleEvent_SeverityId = 0
	SampleEvent_SEVERITY_ID_CRITICAL SampleEvent_SeverityId = 5
	SampleEvent_SEVERITY_ID_OTHER    SampleEvent_SeverityId = 99
)

// Enum value maps for SampleEvent_SeverityId.
var (
	SampleEvent_SeverityId_name = map[int32]string{
		0:  "SEVERITY_ID_UNKNOWN",
		5:  "SEVERITY_ID_CRITICAL",
		99: "SEVERITY_ID_OTHER",
	}
	SampleEvent_SeverityId_value = map[string]int32{
		"SEVERITY_ID_UNKNOWN":  0,
		"SEVERITY_ID_CRITICAL": 5,
		"SEVERITY_ID_OTHER":    99,
	}
)

func (x SampleEvent_SeverityId) Enum() *SampleEvent_SeverityId {
	p := new(SampleEvent_SeverityId)
	*p = x
	return p
}

func (x SampleEvent_SeverityId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SampleEvent_SeverityId) Descriptor() protoreflect.EnumDescriptor {
	return file_sample_proto_enumTypes[0].Descriptor()
}

func (SampleEvent_SeverityId) Type() protoreflect.EnumType {
	return &file_sample_proto_enumTypes[0]
}

func (x SampleEvent_SeverityId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SampleEvent_SeverityId.Descriptor instead.
func (SampleEvent_SeverityId) EnumDescriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{0, 0}
}

type SampleEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// severity_id exercises enum -> integer conversion.
	SeverityId SampleEvent_SeverityId `protobuf:"varint,1,opt,name=severity_id,json=severityId,proto3,enum=ocsf.exporter.sample.v1.SampleEvent_SeverityId" json:"severity_id,omitempty"`
	// time is an int64 (timestamp_t in OCSF) — must be a JSON number, not quoted.
	Time int64 `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	// count is an int32.
	Count int32 `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	// message_text is a plain string field.
	MessageText string `protobuf:"bytes,4,opt,name=message_text,json=messageText,proto3" json:"message_text,omitempty"`
	// is_alert is a bool.
	IsAlert bool `protobuf:"varint,5,opt,name=is_alert,json=isAlert,proto3" json:"is_alert,omitempty"`
	// score is a double.
	Score float64 `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	// metadata is a google.protobuf.Value (OCSF json_t / unmapped bag).
	Metadata *structpb.Value `protobuf:"bytes,7,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// tags is a repeated string.
	Tags []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	// actor is a nested message.
	Actor *Actor `protobuf:"bytes,9,opt,name=actor,proto3" json:"actor,omitempty"`
	// note is an explicit optional string; absent when unset.
	Note *string `protobuf:"bytes,10,opt,name=note,proto3,oneof" json:"note,omitempty"`
	// severities is a repeated enum field; must marshal to a JSON array of
	// integers (e.g. [5,99]), never name strings.
	Severities    []SampleEvent_SeverityId `protobuf:"varint,11,rep,packed,name=severities,proto3,enum=ocsf.exporter.sample.v1.SampleEvent_SeverityId" json:"severities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SampleEvent) Reset() {
	*x = SampleEvent{}
	mi := &file_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SampleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SampleEvent) ProtoMessage() {}

func (x *SampleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SampleEvent.ProtoReflect.Descriptor instead.
func (*SampleEvent) Descriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{0}
}

func (x *SampleEvent) GetSeverityId() SampleEvent_SeverityId {
	if x != nil {
		return x.SeverityId
	}
	return SampleEvent_SEVERITY_ID_UNKNOWN
}

func (x *SampleEvent) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SampleEvent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SampleEvent) GetMessageText() string {
	if x != nil {
		return x.MessageText
	}
	return ""
}

func (x *SampleEvent) GetIsAlert() bool {
	if x != nil {
		return x.IsAlert
	}
	return false
}

func (x *SampleEvent) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SampleEvent) GetMetadata() *structpb.Value {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SampleEvent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SampleEvent) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *SampleEvent) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *SampleEvent) GetSeverities() []SampleEvent_SeverityId {
	if x != nil {
		return x.Severities
	}
	return nil
}

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_sample_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Actor) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

var File_sample_proto protoreflect.FileDescriptor

const file_sample_proto_rawDesc = "" +
	"\n" +
	"\fsample.proto\x12\x17ocsf.exporter.sample.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xa6\x04\n" +
	"\vSampleEvent\x12P\n" +
	"\vseverity_id\x18\x01 \x01(\x0e2/.ocsf.exporter.sample.v1.SampleEvent.SeverityIdR\n" +
	"severityId\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\x12!\n" +
	"\fmessage_text\x18\x04 \x01(\tR\vmessageText\x12\x19\n" +
	"\bis_alert\x18\x05 \x01(\bR\aisAlert\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x122\n" +
	"\bmetadata\x18\a \x01(\v2\x16.google.protobuf.ValueR\bmetadata\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x124\n" +
	"\x05actor\x18\t \x01(\v2\x1e.ocsf.exporter.sample.v1.ActorR\x05actor\x12\x17\n" +
	"\x04note\x18\n" +
	" \x01(\tH\x00R\x04note\x88\x01\x01\x12O\n" +
	"\n" +
	"severities\x18\v \x03(\x0e2/.ocsf.exporter.sample.v1.SampleEvent.SeverityIdR\n" +
	"severities\"V\n" +
	"\n" +
	"SeverityId\x12\x17\n" +
	"\x13SEVERITY_ID_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14SEVERITY_ID_CRITICAL\x10\x05\x12\x15\n" +
	"\x11SEVERITY_ID_OTHER\x10cB\a\n" +
	"\x05_note\"-\n" +
	"\x05Actor\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uidBYZWgithub.com/redpanda-data/common-go/ocsf/internal/ocsf/exporter/testdata/sample;samplev1b\x06proto3"

var (
	file_sample_proto_rawDescOnce sync.Once
	file_sample_proto_rawDescData []byte
)

func file_sample_proto_rawDescGZIP() []byte {
	file_sample_proto_rawDescOnce.Do(func() {
		file_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sample_proto_rawDesc), len(file_sample_proto_rawDesc)))
	})
	return file_sample_proto_rawDescData
}

var file_sample_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sample_proto_goTypes = []any{
	(SampleEvent_SeverityId)(0), // 0: ocsf.exporter.sample.v1.SampleEvent.SeverityId
	(*SampleEvent)(nil),         // 1: ocsf.exporter.sample.v1.SampleEvent
	(*Actor)(nil),               // 2: ocsf.exporter.sample.v1.Actor
	(*structpb.Value)(nil),      // 3: google.protobuf.Value
}
var file_sample_proto_depIdxs = []int32{
	0, // 0: ocsf.exporter.sample.v1.SampleEvent.severity_id:type_name -> ocsf.exporter.sample.v1.SampleEvent.SeverityId
	3, // 1: ocsf.exporter.sample.v1.SampleEvent.metadata:type_name -> google.protobuf.Value
	2, // 2: ocsf.exporter.sample.v1.SampleEvent.actor:type_name -> ocsf.exporter.sample.v1.Actor
	0, // 3: ocsf.exporter.sample.v1.SampleEvent.severities:type_name -> ocsf.exporter.sample.v1.SampleEvent.SeverityId
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sample_proto_init() }
func file_sample_proto_init() {
	if File_sample_proto != nil {
		return
	}
	file_sample_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sample_proto_rawDesc), len(file_sample_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sample_proto_goTypes,
		DependencyIndexes: file_sample_proto_depIdxs,
		EnumInfos:         file_sample_proto_enumTypes,
		MessageInfos:      file_sample_proto_msgTypes,
	}.Build()
	File_sample_proto = out.File
	file_sample_proto_goTypes = nil
	file_sample_proto_depIdxs = nil
}
