// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by ocsf-protogen. DO NOT EDIT.
// Source: OCSF schema 1.8.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ocsf/v1/api_activity.proto

package ocsfv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiActivity_ActionId int32

const (
	ApiActivity_ACTION_ID_UNKNOWN  ApiActivity_ActionId = 0
	ApiActivity_ACTION_ID_ALLOWED  ApiActivity_ActionId = 1
	ApiActivity_ACTION_ID_DENIED   ApiActivity_ActionId = 2
	ApiActivity_ACTION_ID_OBSERVED ApiActivity_ActionId = 3
	ApiActivity_ACTION_ID_MODIFIED ApiActivity_ActionId = 4
	ApiActivity_ACTION_ID_OTHER    ApiActivity_ActionId = 99
)

// Enum value maps for ApiActivity_ActionId.
var (
	ApiActivity_ActionId_name = map[int32]string{
		0:  "ACTION_ID_UNKNOWN",
		1:  "ACTION_ID_ALLOWED",
		2:  "ACTION_ID_DENIED",
		3:  "ACTION_ID_OBSERVED",
		4:  "ACTION_ID_MODIFIED",
		99: "ACTION_ID_OTHER",
	}
	ApiActivity_ActionId_value = map[string]int32{
		"ACTION_ID_UNKNOWN":  0,
		"ACTION_ID_ALLOWED":  1,
		"ACTION_ID_DENIED":   2,
		"ACTION_ID_OBSERVED": 3,
		"ACTION_ID_MODIFIED": 4,
		"ACTION_ID_OTHER":    99,
	}
)

func (x ApiActivity_ActionId) Enum() *ApiActivity_ActionId {
	p := new(ApiActivity_ActionId)
	*p = x
	return p
}

func (x ApiActivity_ActionId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_ActionId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[0].Descriptor()
}

func (ApiActivity_ActionId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[0]
}

func (x ApiActivity_ActionId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_ActionId.Descriptor instead.
func (ApiActivity_ActionId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 0}
}

type ApiActivity_ActivityId int32

const (
	ApiActivity_ACTIVITY_ID_UNKNOWN ApiActivity_ActivityId = 0
	ApiActivity_ACTIVITY_ID_CREATE  ApiActivity_ActivityId = 1
	ApiActivity_ACTIVITY_ID_READ    ApiActivity_ActivityId = 2
	ApiActivity_ACTIVITY_ID_UPDATE  ApiActivity_ActivityId = 3
	ApiActivity_ACTIVITY_ID_DELETE  ApiActivity_ActivityId = 4
	ApiActivity_ACTIVITY_ID_OTHER   ApiActivity_ActivityId = 99
)

// Enum value maps for ApiActivity_ActivityId.
var (
	ApiActivity_ActivityId_name = map[int32]string{
		0:  "ACTIVITY_ID_UNKNOWN",
		1:  "ACTIVITY_ID_CREATE",
		2:  "ACTIVITY_ID_READ",
		3:  "ACTIVITY_ID_UPDATE",
		4:  "ACTIVITY_ID_DELETE",
		99: "ACTIVITY_ID_OTHER",
	}
	ApiActivity_ActivityId_value = map[string]int32{
		"ACTIVITY_ID_UNKNOWN": 0,
		"ACTIVITY_ID_CREATE":  1,
		"ACTIVITY_ID_READ":    2,
		"ACTIVITY_ID_UPDATE":  3,
		"ACTIVITY_ID_DELETE":  4,
		"ACTIVITY_ID_OTHER":   99,
	}
)

func (x ApiActivity_ActivityId) Enum() *ApiActivity_ActivityId {
	p := new(ApiActivity_ActivityId)
	*p = x
	return p
}

func (x ApiActivity_ActivityId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_ActivityId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[1].Descriptor()
}

func (ApiActivity_ActivityId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[1]
}

func (x ApiActivity_ActivityId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_ActivityId.Descriptor instead.
func (ApiActivity_ActivityId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 1}
}

type ApiActivity_CategoryUid int32

const (
	ApiActivity_CATEGORY_UID_UNKNOWN              ApiActivity_CategoryUid = 0
	ApiActivity_CATEGORY_UID_APPLICATION_ACTIVITY ApiActivity_CategoryUid = 6
)

// Enum value maps for ApiActivity_CategoryUid.
var (
	ApiActivity_CategoryUid_name = map[int32]string{
		0: "CATEGORY_UID_UNKNOWN",
		6: "CATEGORY_UID_APPLICATION_ACTIVITY",
	}
	ApiActivity_CategoryUid_value = map[string]int32{
		"CATEGORY_UID_UNKNOWN":              0,
		"CATEGORY_UID_APPLICATION_ACTIVITY": 6,
	}
)

func (x ApiActivity_CategoryUid) Enum() *ApiActivity_CategoryUid {
	p := new(ApiActivity_CategoryUid)
	*p = x
	return p
}

func (x ApiActivity_CategoryUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_CategoryUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[2].Descriptor()
}

func (ApiActivity_CategoryUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[2]
}

func (x ApiActivity_CategoryUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_CategoryUid.Descriptor instead.
func (ApiActivity_CategoryUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 2}
}

type ApiActivity_ClassUid int32

const (
	ApiActivity_CLASS_UID_UNKNOWN      ApiActivity_ClassUid = 0
	ApiActivity_CLASS_UID_API_ACTIVITY ApiActivity_ClassUid = 6003
)

// Enum value maps for ApiActivity_ClassUid.
var (
	ApiActivity_ClassUid_name = map[int32]string{
		0:    "CLASS_UID_UNKNOWN",
		6003: "CLASS_UID_API_ACTIVITY",
	}
	ApiActivity_ClassUid_value = map[string]int32{
		"CLASS_UID_UNKNOWN":      0,
		"CLASS_UID_API_ACTIVITY": 6003,
	}
)

func (x ApiActivity_ClassUid) Enum() *ApiActivity_ClassUid {
	p := new(ApiActivity_ClassUid)
	*p = x
	return p
}

func (x ApiActivity_ClassUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_ClassUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[3].Descriptor()
}

func (ApiActivity_ClassUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[3]
}

func (x ApiActivity_ClassUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_ClassUid.Descriptor instead.
func (ApiActivity_ClassUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 3}
}

type ApiActivity_ConfidenceId int32

const (
	ApiActivity_CONFIDENCE_ID_UNKNOWN ApiActivity_ConfidenceId = 0
	ApiActivity_CONFIDENCE_ID_LOW     ApiActivity_ConfidenceId = 1
	ApiActivity_CONFIDENCE_ID_MEDIUM  ApiActivity_ConfidenceId = 2
	ApiActivity_CONFIDENCE_ID_HIGH    ApiActivity_ConfidenceId = 3
	ApiActivity_CONFIDENCE_ID_OTHER   ApiActivity_ConfidenceId = 99
)

// Enum value maps for ApiActivity_ConfidenceId.
var (
	ApiActivity_ConfidenceId_name = map[int32]string{
		0:  "CONFIDENCE_ID_UNKNOWN",
		1:  "CONFIDENCE_ID_LOW",
		2:  "CONFIDENCE_ID_MEDIUM",
		3:  "CONFIDENCE_ID_HIGH",
		99: "CONFIDENCE_ID_OTHER",
	}
	ApiActivity_ConfidenceId_value = map[string]int32{
		"CONFIDENCE_ID_UNKNOWN": 0,
		"CONFIDENCE_ID_LOW":     1,
		"CONFIDENCE_ID_MEDIUM":  2,
		"CONFIDENCE_ID_HIGH":    3,
		"CONFIDENCE_ID_OTHER":   99,
	}
)

func (x ApiActivity_ConfidenceId) Enum() *ApiActivity_ConfidenceId {
	p := new(ApiActivity_ConfidenceId)
	*p = x
	return p
}

func (x ApiActivity_ConfidenceId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_ConfidenceId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[4].Descriptor()
}

func (ApiActivity_ConfidenceId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[4]
}

func (x ApiActivity_ConfidenceId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_ConfidenceId.Descriptor instead.
func (ApiActivity_ConfidenceId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 4}
}

type ApiActivity_DispositionId int32

const (
	ApiActivity_DISPOSITION_ID_UNKNOWN             ApiActivity_DispositionId = 0
	ApiActivity_DISPOSITION_ID_ALLOWED             ApiActivity_DispositionId = 1
	ApiActivity_DISPOSITION_ID_BLOCKED             ApiActivity_DispositionId = 2
	ApiActivity_DISPOSITION_ID_QUARANTINED         ApiActivity_DispositionId = 3
	ApiActivity_DISPOSITION_ID_ISOLATED            ApiActivity_DispositionId = 4
	ApiActivity_DISPOSITION_ID_DELETED             ApiActivity_DispositionId = 5
	ApiActivity_DISPOSITION_ID_DROPPED             ApiActivity_DispositionId = 6
	ApiActivity_DISPOSITION_ID_CUSTOM_ACTION       ApiActivity_DispositionId = 7
	ApiActivity_DISPOSITION_ID_APPROVED            ApiActivity_DispositionId = 8
	ApiActivity_DISPOSITION_ID_RESTORED            ApiActivity_DispositionId = 9
	ApiActivity_DISPOSITION_ID_EXONERATED          ApiActivity_DispositionId = 10
	ApiActivity_DISPOSITION_ID_CORRECTED           ApiActivity_DispositionId = 11
	ApiActivity_DISPOSITION_ID_PARTIALLY_CORRECTED ApiActivity_DispositionId = 12
	ApiActivity_DISPOSITION_ID_UNCORRECTED         ApiActivity_DispositionId = 13
	ApiActivity_DISPOSITION_ID_DELAYED             ApiActivity_DispositionId = 14
	ApiActivity_DISPOSITION_ID_DETECTED            ApiActivity_DispositionId = 15
	ApiActivity_DISPOSITION_ID_NO_ACTION           ApiActivity_DispositionId = 16
	ApiActivity_DISPOSITION_ID_LOGGED              ApiActivity_DispositionId = 17
	ApiActivity_DISPOSITION_ID_TAGGED              ApiActivity_DispositionId = 18
	ApiActivity_DISPOSITION_ID_ALERT               ApiActivity_DispositionId = 19
	ApiActivity_DISPOSITION_ID_COUNT               ApiActivity_DispositionId = 20
	ApiActivity_DISPOSITION_ID_RESET               ApiActivity_DispositionId = 21
	ApiActivity_DISPOSITION_ID_CAPTCHA             ApiActivity_DispositionId = 22
	ApiActivity_DISPOSITION_ID_CHALLENGE           ApiActivity_DispositionId = 23
	ApiActivity_DISPOSITION_ID_ACCESS_REVOKED      ApiActivity_DispositionId = 24
	ApiActivity_DISPOSITION_ID_REJECTED            ApiActivity_DispositionId = 25
	ApiActivity_DISPOSITION_ID_UNAUTHORIZED        ApiActivity_DispositionId = 26
	ApiActivity_DISPOSITION_ID_ERROR               ApiActivity_DispositionId = 27
	ApiActivity_DISPOSITION_ID_OTHER               ApiActivity_DispositionId = 99
)

// Enum value maps for ApiActivity_DispositionId.
var (
	ApiActivity_DispositionId_name = map[int32]string{
		0:  "DISPOSITION_ID_UNKNOWN",
		1:  "DISPOSITION_ID_ALLOWED",
		2:  "DISPOSITION_ID_BLOCKED",
		3:  "DISPOSITION_ID_QUARANTINED",
		4:  "DISPOSITION_ID_ISOLATED",
		5:  "DISPOSITION_ID_DELETED",
		6:  "DISPOSITION_ID_DROPPED",
		7:  "DISPOSITION_ID_CUSTOM_ACTION",
		8:  "DISPOSITION_ID_APPROVED",
		9:  "DISPOSITION_ID_RESTORED",
		10: "DISPOSITION_ID_EXONERATED",
		11: "DISPOSITION_ID_CORRECTED",
		12: "DISPOSITION_ID_PARTIALLY_CORRECTED",
		13: "DISPOSITION_ID_UNCORRECTED",
		14: "DISPOSITION_ID_DELAYED",
		15: "DISPOSITION_ID_DETECTED",
		16: "DISPOSITION_ID_NO_ACTION",
		17: "DISPOSITION_ID_LOGGED",
		18: "DISPOSITION_ID_TAGGED",
		19: "DISPOSITION_ID_ALERT",
		20: "DISPOSITION_ID_COUNT",
		21: "DISPOSITION_ID_RESET",
		22: "DISPOSITION_ID_CAPTCHA",
		23: "DISPOSITION_ID_CHALLENGE",
		24: "DISPOSITION_ID_ACCESS_REVOKED",
		25: "DISPOSITION_ID_REJECTED",
		26: "DISPOSITION_ID_UNAUTHORIZED",
		27: "DISPOSITION_ID_ERROR",
		99: "DISPOSITION_ID_OTHER",
	}
	ApiActivity_DispositionId_value = map[string]int32{
		"DISPOSITION_ID_UNKNOWN":             0,
		"DISPOSITION_ID_ALLOWED":             1,
		"DISPOSITION_ID_BLOCKED":             2,
		"DISPOSITION_ID_QUARANTINED":         3,
		"DISPOSITION_ID_ISOLATED":            4,
		"DISPOSITION_ID_DELETED":             5,
		"DISPOSITION_ID_DROPPED":             6,
		"DISPOSITION_ID_CUSTOM_ACTION":       7,
		"DISPOSITION_ID_APPROVED":            8,
		"DISPOSITION_ID_RESTORED":            9,
		"DISPOSITION_ID_EXONERATED":          10,
		"DISPOSITION_ID_CORRECTED":           11,
		"DISPOSITION_ID_PARTIALLY_CORRECTED": 12,
		"DISPOSITION_ID_UNCORRECTED":         13,
		"DISPOSITION_ID_DELAYED":             14,
		"DISPOSITION_ID_DETECTED":            15,
		"DISPOSITION_ID_NO_ACTION":           16,
		"DISPOSITION_ID_LOGGED":              17,
		"DISPOSITION_ID_TAGGED":              18,
		"DISPOSITION_ID_ALERT":               19,
		"DISPOSITION_ID_COUNT":               20,
		"DISPOSITION_ID_RESET":               21,
		"DISPOSITION_ID_CAPTCHA":             22,
		"DISPOSITION_ID_CHALLENGE":           23,
		"DISPOSITION_ID_ACCESS_REVOKED":      24,
		"DISPOSITION_ID_REJECTED":            25,
		"DISPOSITION_ID_UNAUTHORIZED":        26,
		"DISPOSITION_ID_ERROR":               27,
		"DISPOSITION_ID_OTHER":               99,
	}
)

func (x ApiActivity_DispositionId) Enum() *ApiActivity_DispositionId {
	p := new(ApiActivity_DispositionId)
	*p = x
	return p
}

func (x ApiActivity_DispositionId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_DispositionId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[5].Descriptor()
}

func (ApiActivity_DispositionId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[5]
}

func (x ApiActivity_DispositionId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_DispositionId.Descriptor instead.
func (ApiActivity_DispositionId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 5}
}

type ApiActivity_RiskLevelId int32

const (
	ApiActivity_RISK_LEVEL_ID_INFO     ApiActivity_RiskLevelId = 0
	ApiActivity_RISK_LEVEL_ID_LOW      ApiActivity_RiskLevelId = 1
	ApiActivity_RISK_LEVEL_ID_MEDIUM   ApiActivity_RiskLevelId = 2
	ApiActivity_RISK_LEVEL_ID_HIGH     ApiActivity_RiskLevelId = 3
	ApiActivity_RISK_LEVEL_ID_CRITICAL ApiActivity_RiskLevelId = 4
	ApiActivity_RISK_LEVEL_ID_OTHER    ApiActivity_RiskLevelId = 99
)

// Enum value maps for ApiActivity_RiskLevelId.
var (
	ApiActivity_RiskLevelId_name = map[int32]string{
		0:  "RISK_LEVEL_ID_INFO",
		1:  "RISK_LEVEL_ID_LOW",
		2:  "RISK_LEVEL_ID_MEDIUM",
		3:  "RISK_LEVEL_ID_HIGH",
		4:  "RISK_LEVEL_ID_CRITICAL",
		99: "RISK_LEVEL_ID_OTHER",
	}
	ApiActivity_RiskLevelId_value = map[string]int32{
		"RISK_LEVEL_ID_INFO":     0,
		"RISK_LEVEL_ID_LOW":      1,
		"RISK_LEVEL_ID_MEDIUM":   2,
		"RISK_LEVEL_ID_HIGH":     3,
		"RISK_LEVEL_ID_CRITICAL": 4,
		"RISK_LEVEL_ID_OTHER":    99,
	}
)

func (x ApiActivity_RiskLevelId) Enum() *ApiActivity_RiskLevelId {
	p := new(ApiActivity_RiskLevelId)
	*p = x
	return p
}

func (x ApiActivity_RiskLevelId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_RiskLevelId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[6].Descriptor()
}

func (ApiActivity_RiskLevelId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[6]
}

func (x ApiActivity_RiskLevelId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_RiskLevelId.Descriptor instead.
func (ApiActivity_RiskLevelId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 6}
}

type ApiActivity_SeverityId int32

const (
	ApiActivity_SEVERITY_ID_UNKNOWN       ApiActivity_SeverityId = 0
	ApiActivity_SEVERITY_ID_INFORMATIONAL ApiActivity_SeverityId = 1
	ApiActivity_SEVERITY_ID_LOW           ApiActivity_SeverityId = 2
	ApiActivity_SEVERITY_ID_MEDIUM        ApiActivity_SeverityId = 3
	ApiActivity_SEVERITY_ID_HIGH          ApiActivity_SeverityId = 4
	ApiActivity_SEVERITY_ID_CRITICAL      ApiActivity_SeverityId = 5
	ApiActivity_SEVERITY_ID_FATAL         ApiActivity_SeverityId = 6
	ApiActivity_SEVERITY_ID_OTHER         ApiActivity_SeverityId = 99
)

// Enum value maps for ApiActivity_SeverityId.
var (
	ApiActivity_SeverityId_name = map[int32]string{
		0:  "SEVERITY_ID_UNKNOWN",
		1:  "SEVERITY_ID_INFORMATIONAL",
		2:  "SEVERITY_ID_LOW",
		3:  "SEVERITY_ID_MEDIUM",
		4:  "SEVERITY_ID_HIGH",
		5:  "SEVERITY_ID_CRITICAL",
		6:  "SEVERITY_ID_FATAL",
		99: "SEVERITY_ID_OTHER",
	}
	ApiActivity_SeverityId_value = map[string]int32{
		"SEVERITY_ID_UNKNOWN":       0,
		"SEVERITY_ID_INFORMATIONAL": 1,
		"SEVERITY_ID_LOW":           2,
		"SEVERITY_ID_MEDIUM":        3,
		"SEVERITY_ID_HIGH":          4,
		"SEVERITY_ID_CRITICAL":      5,
		"SEVERITY_ID_FATAL":         6,
		"SEVERITY_ID_OTHER":         99,
	}
)

func (x ApiActivity_SeverityId) Enum() *ApiActivity_SeverityId {
	p := new(ApiActivity_SeverityId)
	*p = x
	return p
}

func (x ApiActivity_SeverityId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_SeverityId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[7].Descriptor()
}

func (ApiActivity_SeverityId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[7]
}

func (x ApiActivity_SeverityId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_SeverityId.Descriptor instead.
func (ApiActivity_SeverityId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 7}
}

type ApiActivity_StatusId int32

const (
	ApiActivity_STATUS_ID_UNKNOWN ApiActivity_StatusId = 0
	ApiActivity_STATUS_ID_SUCCESS ApiActivity_StatusId = 1
	ApiActivity_STATUS_ID_FAILURE ApiActivity_StatusId = 2
	ApiActivity_STATUS_ID_OTHER   ApiActivity_StatusId = 99
)

// Enum value maps for ApiActivity_StatusId.
var (
	ApiActivity_StatusId_name = map[int32]string{
		0:  "STATUS_ID_UNKNOWN",
		1:  "STATUS_ID_SUCCESS",
		2:  "STATUS_ID_FAILURE",
		99: "STATUS_ID_OTHER",
	}
	ApiActivity_StatusId_value = map[string]int32{
		"STATUS_ID_UNKNOWN": 0,
		"STATUS_ID_SUCCESS": 1,
		"STATUS_ID_FAILURE": 2,
		"STATUS_ID_OTHER":   99,
	}
)

func (x ApiActivity_StatusId) Enum() *ApiActivity_StatusId {
	p := new(ApiActivity_StatusId)
	*p = x
	return p
}

func (x ApiActivity_StatusId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_StatusId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[8].Descriptor()
}

func (ApiActivity_StatusId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[8]
}

func (x ApiActivity_StatusId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_StatusId.Descriptor instead.
func (ApiActivity_StatusId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 8}
}

type ApiActivity_TypeUid int32

const (
	ApiActivity_TYPE_UID_UNKNOWN              ApiActivity_TypeUid = 0
	ApiActivity_TYPE_UID_API_ACTIVITY_UNKNOWN ApiActivity_TypeUid = 600300
	ApiActivity_TYPE_UID_API_ACTIVITY_CREATE  ApiActivity_TypeUid = 600301
	ApiActivity_TYPE_UID_API_ACTIVITY_READ    ApiActivity_TypeUid = 600302
	ApiActivity_TYPE_UID_API_ACTIVITY_UPDATE  ApiActivity_TypeUid = 600303
	ApiActivity_TYPE_UID_API_ACTIVITY_DELETE  ApiActivity_TypeUid = 600304
	ApiActivity_TYPE_UID_API_ACTIVITY_OTHER   ApiActivity_TypeUid = 600399
)

// Enum value maps for ApiActivity_TypeUid.
var (
	ApiActivity_TypeUid_name = map[int32]string{
		0:      "TYPE_UID_UNKNOWN",
		600300: "TYPE_UID_API_ACTIVITY_UNKNOWN",
		600301: "TYPE_UID_API_ACTIVITY_CREATE",
		600302: "TYPE_UID_API_ACTIVITY_READ",
		600303: "TYPE_UID_API_ACTIVITY_UPDATE",
		600304: "TYPE_UID_API_ACTIVITY_DELETE",
		600399: "TYPE_UID_API_ACTIVITY_OTHER",
	}
	ApiActivity_TypeUid_value = map[string]int32{
		"TYPE_UID_UNKNOWN":              0,
		"TYPE_UID_API_ACTIVITY_UNKNOWN": 600300,
		"TYPE_UID_API_ACTIVITY_CREATE":  600301,
		"TYPE_UID_API_ACTIVITY_READ":    600302,
		"TYPE_UID_API_ACTIVITY_UPDATE":  600303,
		"TYPE_UID_API_ACTIVITY_DELETE":  600304,
		"TYPE_UID_API_ACTIVITY_OTHER":   600399,
	}
)

func (x ApiActivity_TypeUid) Enum() *ApiActivity_TypeUid {
	p := new(ApiActivity_TypeUid)
	*p = x
	return p
}

func (x ApiActivity_TypeUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApiActivity_TypeUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_api_activity_proto_enumTypes[9].Descriptor()
}

func (ApiActivity_TypeUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_api_activity_proto_enumTypes[9]
}

func (x ApiActivity_TypeUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApiActivity_TypeUid.Descriptor instead.
func (ApiActivity_TypeUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0, 9}
}

type ApiActivity struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Action          string                    `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	ActionId        ApiActivity_ActionId      `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3,enum=ocsf.v1.ApiActivity_ActionId" json:"action_id,omitempty"`
	ActivityId      ApiActivity_ActivityId    `protobuf:"varint,3,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1.ApiActivity_ActivityId" json:"activity_id,omitempty"`
	ActivityName    string                    `protobuf:"bytes,4,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	Actor           *Actor                    `protobuf:"bytes,5,opt,name=actor,proto3" json:"actor,omitempty"`
	AiModel         *AiModel                  `protobuf:"bytes,6,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	Api             *Api                      `protobuf:"bytes,7,opt,name=api,proto3" json:"api,omitempty"`
	Attacks         []*Attack                 `protobuf:"bytes,8,rep,name=attacks,proto3" json:"attacks,omitempty"`
	Authorizations  []*Authorization          `protobuf:"bytes,9,rep,name=authorizations,proto3" json:"authorizations,omitempty"`
	CategoryName    string                    `protobuf:"bytes,10,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryUid     ApiActivity_CategoryUid   `protobuf:"varint,11,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1.ApiActivity_CategoryUid" json:"category_uid,omitempty"`
	ClassName       string                    `protobuf:"bytes,12,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ClassUid        ApiActivity_ClassUid      `protobuf:"varint,13,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1.ApiActivity_ClassUid" json:"class_uid,omitempty"`
	Cloud           *Cloud                    `protobuf:"bytes,14,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Confidence      string                    `protobuf:"bytes,15,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ConfidenceId    ApiActivity_ConfidenceId  `protobuf:"varint,16,opt,name=confidence_id,json=confidenceId,proto3,enum=ocsf.v1.ApiActivity_ConfidenceId" json:"confidence_id,omitempty"`
	ConfidenceScore int32                     `protobuf:"varint,17,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Count           int32                     `protobuf:"varint,18,opt,name=count,proto3" json:"count,omitempty"`
	Device          *Device                   `protobuf:"bytes,19,opt,name=device,proto3" json:"device,omitempty"`
	Disposition     string                    `protobuf:"bytes,20,opt,name=disposition,proto3" json:"disposition,omitempty"`
	DispositionId   ApiActivity_DispositionId `protobuf:"varint,21,opt,name=disposition_id,json=dispositionId,proto3,enum=ocsf.v1.ApiActivity_DispositionId" json:"disposition_id,omitempty"`
	DstEndpoint     *NetworkEndpoint          `protobuf:"bytes,22,opt,name=dst_endpoint,json=dstEndpoint,proto3" json:"dst_endpoint,omitempty"`
	Duration        int64                     `protobuf:"varint,23,opt,name=duration,proto3" json:"duration,omitempty"`
	EndTime         int64                     `protobuf:"varint,24,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	EndTimeDt       string                    `protobuf:"bytes,25,opt,name=end_time_dt,json=endTimeDt,proto3" json:"end_time_dt,omitempty"`
	Enrichments     []*Enrichment             `protobuf:"bytes,26,rep,name=enrichments,proto3" json:"enrichments,omitempty"`
	FirewallRule    *FirewallRule             `protobuf:"bytes,27,opt,name=firewall_rule,json=firewallRule,proto3" json:"firewall_rule,omitempty"`
	HttpRequest     *HttpRequest              `protobuf:"bytes,28,opt,name=http_request,json=httpRequest,proto3" json:"http_request,omitempty"`
	HttpResponse    *HttpResponse             `protobuf:"bytes,29,opt,name=http_response,json=httpResponse,proto3" json:"http_response,omitempty"`
	IsAlert         bool                      `protobuf:"varint,30,opt,name=is_alert,json=isAlert,proto3" json:"is_alert,omitempty"`
	Malware         []*Malware                `protobuf:"bytes,31,rep,name=malware,proto3" json:"malware,omitempty"`
	MalwareScanInfo *MalwareScanInfo          `protobuf:"bytes,32,opt,name=malware_scan_info,json=malwareScanInfo,proto3" json:"malware_scan_info,omitempty"`
	Message         string                    `protobuf:"bytes,33,opt,name=message,proto3" json:"message,omitempty"`
	MessageContext  *MessageContext           `protobuf:"bytes,34,opt,name=message_context,json=messageContext,proto3" json:"message_context,omitempty"`
	Metadata        *Metadata                 `protobuf:"bytes,35,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Observables     []*Observable             `protobuf:"bytes,36,rep,name=observables,proto3" json:"observables,omitempty"`
	Osint           []*Osint                  `protobuf:"bytes,37,rep,name=osint,proto3" json:"osint,omitempty"`
	Policy          *Policy                   `protobuf:"bytes,38,opt,name=policy,proto3" json:"policy,omitempty"`
	RawData         string                    `protobuf:"bytes,39,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	RawDataHash     *Fingerprint              `protobuf:"bytes,40,opt,name=raw_data_hash,json=rawDataHash,proto3" json:"raw_data_hash,omitempty"`
	RawDataSize     int64                     `protobuf:"varint,41,opt,name=raw_data_size,json=rawDataSize,proto3" json:"raw_data_size,omitempty"`
	Resources       []*ResourceDetails        `protobuf:"bytes,42,rep,name=resources,proto3" json:"resources,omitempty"`
	RiskDetails     string                    `protobuf:"bytes,43,opt,name=risk_details,json=riskDetails,proto3" json:"risk_details,omitempty"`
	RiskLevel       string                    `protobuf:"bytes,44,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RiskLevelId     ApiActivity_RiskLevelId   `protobuf:"varint,45,opt,name=risk_level_id,json=riskLevelId,proto3,enum=ocsf.v1.ApiActivity_RiskLevelId" json:"risk_level_id,omitempty"`
	RiskScore       int32                     `protobuf:"varint,46,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Severity        string                    `protobuf:"bytes,47,opt,name=severity,proto3" json:"severity,omitempty"`
	SeverityId      ApiActivity_SeverityId    `protobuf:"varint,48,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1.ApiActivity_SeverityId" json:"severity_id,omitempty"`
	SrcEndpoint     *NetworkEndpoint          `protobuf:"bytes,49,opt,name=src_endpoint,json=srcEndpoint,proto3" json:"src_endpoint,omitempty"`
	StartTime       int64                     `protobuf:"varint,50,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StartTimeDt     string                    `protobuf:"bytes,51,opt,name=start_time_dt,json=startTimeDt,proto3" json:"start_time_dt,omitempty"`
	Status          string                    `protobuf:"bytes,52,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode      string                    `protobuf:"bytes,53,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusDetail    string                    `protobuf:"bytes,54,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`
	StatusId        ApiActivity_StatusId      `protobuf:"varint,55,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1.ApiActivity_StatusId" json:"status_id,omitempty"`
	Time            int64                     `protobuf:"varint,56,opt,name=time,proto3" json:"time,omitempty"`
	TimeDt          string                    `protobuf:"bytes,57,opt,name=time_dt,json=timeDt,proto3" json:"time_dt,omitempty"`
	TimezoneOffset  int32                     `protobuf:"varint,58,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`
	Trace           *Trace                    `protobuf:"bytes,59,opt,name=trace,proto3" json:"trace,omitempty"`
	TypeName        string                    `protobuf:"bytes,60,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	TypeUid         ApiActivity_TypeUid       `protobuf:"varint,61,opt,name=type_uid,json=typeUid,proto3,enum=ocsf.v1.ApiActivity_TypeUid" json:"type_uid,omitempty"`
	Unmapped        *structpb.Value           `protobuf:"bytes,62,opt,name=unmapped,proto3" json:"unmapped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApiActivity) Reset() {
	*x = ApiActivity{}
	mi := &file_ocsf_v1_api_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiActivity) ProtoMessage() {}

func (x *ApiActivity) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_api_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiActivity.ProtoReflect.Descriptor instead.
func (*ApiActivity) Descriptor() ([]byte, []int) {
	return file_ocsf_v1_api_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ApiActivity) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ApiActivity) GetActionId() ApiActivity_ActionId {
	if x != nil {
		return x.ActionId
	}
	return ApiActivity_ACTION_ID_UNKNOWN
}

func (x *ApiActivity) GetActivityId() ApiActivity_ActivityId {
	if x != nil {
		return x.ActivityId
	}
	return ApiActivity_ACTIVITY_ID_UNKNOWN
}

func (x *ApiActivity) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *ApiActivity) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *ApiActivity) GetAiModel() *AiModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

func (x *ApiActivity) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *ApiActivity) GetAttacks() []*Attack {
	if x != nil {
		return x.Attacks
	}
	return nil
}

func (x *ApiActivity) GetAuthorizations() []*Authorization {
	if x != nil {
		return x.Authorizations
	}
	return nil
}

func (x *ApiActivity) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ApiActivity) GetCategoryUid() ApiActivity_CategoryUid {
	if x != nil {
		return x.CategoryUid
	}
	return ApiActivity_CATEGORY_UID_UNKNOWN
}

func (x *ApiActivity) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ApiActivity) GetClassUid() ApiActivity_ClassUid {
	if x != nil {
		return x.ClassUid
	}
	return ApiActivity_CLASS_UID_UNKNOWN
}

func (x *ApiActivity) GetCloud() *Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *ApiActivity) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *ApiActivity) GetConfidenceId() ApiActivity_ConfidenceId {
	if x != nil {
		return x.ConfidenceId
	}
	return ApiActivity_CONFIDENCE_ID_UNKNOWN
}

func (x *ApiActivity) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *ApiActivity) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ApiActivity) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *ApiActivity) GetDisposition() string {
	if x != nil {
		return x.Disposition
	}
	return ""
}

func (x *ApiActivity) GetDispositionId() ApiActivity_DispositionId {
	if x != nil {
		return x.DispositionId
	}
	return ApiActivity_DISPOSITION_ID_UNKNOWN
}

func (x *ApiActivity) GetDstEndpoint() *NetworkEndpoint {
	if x != nil {
		return x.DstEndpoint
	}
	return nil
}

func (x *ApiActivity) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *ApiActivity) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *ApiActivity) GetEndTimeDt() string {
	if x != nil {
		return x.EndTimeDt
	}
	return ""
}

func (x *ApiActivity) GetEnrichments() []*Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *ApiActivity) GetFirewallRule() *FirewallRule {
	if x != nil {
		return x.FirewallRule
	}
	return nil
}

func (x *ApiActivity) GetHttpRequest() *HttpRequest {
	if x != nil {
		return x.HttpRequest
	}
	return nil
}

func (x *ApiActivity) GetHttpResponse() *HttpResponse {
	if x != nil {
		return x.HttpResponse
	}
	return nil
}

func (x *ApiActivity) GetIsAlert() bool {
	if x != nil {
		return x.IsAlert
	}
	return false
}

func (x *ApiActivity) GetMalware() []*Malware {
	if x != nil {
		return x.Malware
	}
	return nil
}

func (x *ApiActivity) GetMalwareScanInfo() *MalwareScanInfo {
	if x != nil {
		return x.MalwareScanInfo
	}
	return nil
}

func (x *ApiActivity) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiActivity) GetMessageContext() *MessageContext {
	if x != nil {
		return x.MessageContext
	}
	return nil
}

func (x *ApiActivity) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ApiActivity) GetObservables() []*Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *ApiActivity) GetOsint() []*Osint {
	if x != nil {
		return x.Osint
	}
	return nil
}

func (x *ApiActivity) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *ApiActivity) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *ApiActivity) GetRawDataHash() *Fingerprint {
	if x != nil {
		return x.RawDataHash
	}
	return nil
}

func (x *ApiActivity) GetRawDataSize() int64 {
	if x != nil {
		return x.RawDataSize
	}
	return 0
}

func (x *ApiActivity) GetResources() []*ResourceDetails {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ApiActivity) GetRiskDetails() string {
	if x != nil {
		return x.RiskDetails
	}
	return ""
}

func (x *ApiActivity) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *ApiActivity) GetRiskLevelId() ApiActivity_RiskLevelId {
	if x != nil {
		return x.RiskLevelId
	}
	return ApiActivity_RISK_LEVEL_ID_INFO
}

func (x *ApiActivity) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *ApiActivity) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *ApiActivity) GetSeverityId() ApiActivity_SeverityId {
	if x != nil {
		return x.SeverityId
	}
	return ApiActivity_SEVERITY_ID_UNKNOWN
}

func (x *ApiActivity) GetSrcEndpoint() *NetworkEndpoint {
	if x != nil {
		return x.SrcEndpoint
	}
	return nil
}

func (x *ApiActivity) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ApiActivity) GetStartTimeDt() string {
	if x != nil {
		return x.StartTimeDt
	}
	return ""
}

func (x *ApiActivity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApiActivity) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *ApiActivity) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *ApiActivity) GetStatusId() ApiActivity_StatusId {
	if x != nil {
		return x.StatusId
	}
	return ApiActivity_STATUS_ID_UNKNOWN
}

func (x *ApiActivity) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ApiActivity) GetTimeDt() string {
	if x != nil {
		return x.TimeDt
	}
	return ""
}

func (x *ApiActivity) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *ApiActivity) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *ApiActivity) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *ApiActivity) GetTypeUid() ApiActivity_TypeUid {
	if x != nil {
		return x.TypeUid
	}
	return ApiActivity_TYPE_UID_UNKNOWN
}

func (x *ApiActivity) GetUnmapped() *structpb.Value {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

var File_ocsf_v1_api_activity_proto protoreflect.FileDescriptor

const file_ocsf_v1_api_activity_proto_rawDesc = "" +
	"\n" +
	"\x1aocsf/v1/api_activity.proto\x12\aocsf.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15ocsf/v1/objects.proto\"\xa5'\n" +
	"\vApiActivity\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12:\n" +
	"\taction_id\x18\x02 \x01(\x0e2\x1d.ocsf.v1.ApiActivity.ActionIdR\bactionId\x12H\n" +
	"\vactivity_id\x18\x03 \x01(\x0e2\x1f.ocsf.v1.ApiActivity.ActivityIdB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x04 \x01(\tR\factivityName\x12,\n" +
	"\x05actor\x18\x05 \x01(\v2\x0e.ocsf.v1.ActorB\x06\xbaH\x03\xc8\x01\x01R\x05actor\x12+\n" +
	"\bai_model\x18\x06 \x01(\v2\x10.ocsf.v1.AiModelR\aaiModel\x12&\n" +
	"\x03api\x18\a \x01(\v2\f.ocsf.v1.ApiB\x06\xbaH\x03\xc8\x01\x01R\x03api\x12)\n" +
	"\aattacks\x18\b \x03(\v2\x0f.ocsf.v1.AttackR\aattacks\x12>\n" +
	"\x0eauthorizations\x18\t \x03(\v2\x16.ocsf.v1.AuthorizationR\x0eauthorizations\x12#\n" +
	"\rcategory_name\x18\n" +
	" \x01(\tR\fcategoryName\x12K\n" +
	"\fcategory_uid\x18\v \x01(\x0e2 .ocsf.v1.ApiActivity.CategoryUidB\x06\xbaH\x03\xc8\x01\x01R\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\f \x01(\tR\tclassName\x12B\n" +
	"\tclass_uid\x18\r \x01(\x0e2\x1d.ocsf.v1.ApiActivity.ClassUidB\x06\xbaH\x03\xc8\x01\x01R\bclassUid\x12,\n" +
	"\x05cloud\x18\x0e \x01(\v2\x0e.ocsf.v1.CloudB\x06\xbaH\x03\xc8\x01\x01R\x05cloud\x12\x1e\n" +
	"\n" +
	"confidence\x18\x0f \x01(\tR\n" +
	"confidence\x12F\n" +
	"\rconfidence_id\x18\x10 \x01(\x0e2!.ocsf.v1.ApiActivity.ConfidenceIdR\fconfidenceId\x12)\n" +
	"\x10confidence_score\x18\x11 \x01(\x05R\x0fconfidenceScore\x12\x14\n" +
	"\x05count\x18\x12 \x01(\x05R\x05count\x12'\n" +
	"\x06device\x18\x13 \x01(\v2\x0f.ocsf.v1.DeviceR\x06device\x12 \n" +
	"\vdisposition\x18\x14 \x01(\tR\vdisposition\x12I\n" +
	"\x0edisposition_id\x18\x15 \x01(\x0e2\".ocsf.v1.ApiActivity.DispositionIdR\rdispositionId\x12;\n" +
	"\fdst_endpoint\x18\x16 \x01(\v2\x18.ocsf.v1.NetworkEndpointR\vdstEndpoint\x12\x1a\n" +
	"\bduration\x18\x17 \x01(\x03R\bduration\x12\x19\n" +
	"\bend_time\x18\x18 \x01(\x03R\aendTime\x12\x1e\n" +
	"\vend_time_dt\x18\x19 \x01(\tR\tendTimeDt\x125\n" +
	"\venrichments\x18\x1a \x03(\v2\x13.ocsf.v1.EnrichmentR\venrichments\x12:\n" +
	"\rfirewall_rule\x18\x1b \x01(\v2\x15.ocsf.v1.FirewallRuleR\ffirewallRule\x127\n" +
	"\fhttp_request\x18\x1c \x01(\v2\x14.ocsf.v1.HttpRequestR\vhttpRequest\x12:\n" +
	"\rhttp_response\x18\x1d \x01(\v2\x15.ocsf.v1.HttpResponseR\fhttpResponse\x12\x19\n" +
	"\bis_alert\x18\x1e \x01(\bR\aisAlert\x12*\n" +
	"\amalware\x18\x1f \x03(\v2\x10.ocsf.v1.MalwareR\amalware\x12D\n" +
	"\x11malware_scan_info\x18  \x01(\v2\x18.ocsf.v1.MalwareScanInfoR\x0fmalwareScanInfo\x12\x18\n" +
	"\amessage\x18! \x01(\tR\amessage\x12@\n" +
	"\x0fmessage_context\x18\" \x01(\v2\x17.ocsf.v1.MessageContextR\x0emessageContext\x125\n" +
	"\bmetadata\x18# \x01(\v2\x11.ocsf.v1.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x125\n" +
	"\vobservables\x18$ \x03(\v2\x13.ocsf.v1.ObservableR\vobservables\x12$\n" +
	"\x05osint\x18% \x03(\v2\x0e.ocsf.v1.OsintR\x05osint\x12'\n" +
	"\x06policy\x18& \x01(\v2\x0f.ocsf.v1.PolicyR\x06policy\x12\x19\n" +
	"\braw_data\x18' \x01(\tR\arawData\x128\n" +
	"\rraw_data_hash\x18( \x01(\v2\x14.ocsf.v1.FingerprintR\vrawDataHash\x12\"\n" +
	"\rraw_data_size\x18) \x01(\x03R\vrawDataSize\x126\n" +
	"\tresources\x18* \x03(\v2\x18.ocsf.v1.ResourceDetailsR\tresources\x12!\n" +
	"\frisk_details\x18+ \x01(\tR\vriskDetails\x12\x1d\n" +
	"\n" +
	"risk_level\x18, \x01(\tR\triskLevel\x12D\n" +
	"\rrisk_level_id\x18- \x01(\x0e2 .ocsf.v1.ApiActivity.RiskLevelIdR\vriskLevelId\x12\x1d\n" +
	"\n" +
	"risk_score\x18. \x01(\x05R\triskScore\x12\x1a\n" +
	"\bseverity\x18/ \x01(\tR\bseverity\x12H\n" +
	"\vseverity_id\x180 \x01(\x0e2\x1f.ocsf.v1.ApiActivity.SeverityIdB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"severityId\x12C\n" +
	"\fsrc_endpoint\x181 \x01(\v2\x18.ocsf.v1.NetworkEndpointB\x06\xbaH\x03\xc8\x01\x01R\vsrcEndpoint\x12\x1d\n" +
	"\n" +
	"start_time\x182 \x01(\x03R\tstartTime\x12\"\n" +
	"\rstart_time_dt\x183 \x01(\tR\vstartTimeDt\x12\x16\n" +
	"\x06status\x184 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x185 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x186 \x01(\tR\fstatusDetail\x12:\n" +
	"\tstatus_id\x187 \x01(\x0e2\x1d.ocsf.v1.ApiActivity.StatusIdR\bstatusId\x12\x1a\n" +
	"\x04time\x188 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x04time\x12\x17\n" +
	"\atime_dt\x189 \x01(\tR\x06timeDt\x12'\n" +
	"\x0ftimezone_offset\x18: \x01(\x05R\x0etimezoneOffset\x12$\n" +
	"\x05trace\x18; \x01(\v2\x0e.ocsf.v1.TraceR\x05trace\x12\x1b\n" +
	"\ttype_name\x18< \x01(\tR\btypeName\x12?\n" +
	"\btype_uid\x18= \x01(\x0e2\x1c.ocsf.v1.ApiActivity.TypeUidB\x06\xbaH\x03\xc8\x01\x01R\atypeUid\x122\n" +
	"\bunmapped\x18> \x01(\v2\x16.google.protobuf.ValueR\bunmapped\"\x93\x01\n" +
	"\bActionId\x12\x15\n" +
	"\x11ACTION_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11ACTION_ID_ALLOWED\x10\x01\x12\x14\n" +
	"\x10ACTION_ID_DENIED\x10\x02\x12\x16\n" +
	"\x12ACTION_ID_OBSERVED\x10\x03\x12\x16\n" +
	"\x12ACTION_ID_MODIFIED\x10\x04\x12\x13\n" +
	"\x0fACTION_ID_OTHER\x10c\"\x9a\x01\n" +
	"\n" +
	"ActivityId\x12\x17\n" +
	"\x13ACTIVITY_ID_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12ACTIVITY_ID_CREATE\x10\x01\x12\x14\n" +
	"\x10ACTIVITY_ID_READ\x10\x02\x12\x16\n" +
	"\x12ACTIVITY_ID_UPDATE\x10\x03\x12\x16\n" +
	"\x12ACTIVITY_ID_DELETE\x10\x04\x12\x15\n" +
	"\x11ACTIVITY_ID_OTHER\x10c\"N\n" +
	"\vCategoryUid\x12\x18\n" +
	"\x14CATEGORY_UID_UNKNOWN\x10\x00\x12%\n" +
	"!CATEGORY_UID_APPLICATION_ACTIVITY\x10\x06\">\n" +
	"\bClassUid\x12\x15\n" +
	"\x11CLASS_UID_UNKNOWN\x10\x00\x12\x1b\n" +
	"\x16CLASS_UID_API_ACTIVITY\x10\xf3.\"\x8b\x01\n" +
	"\fConfidenceId\x12\x19\n" +
	"\x15CONFIDENCE_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CONFIDENCE_ID_LOW\x10\x01\x12\x18\n" +
	"\x14CONFIDENCE_ID_MEDIUM\x10\x02\x12\x16\n" +
	"\x12CONFIDENCE_ID_HIGH\x10\x03\x12\x17\n" +
	"\x13CONFIDENCE_ID_OTHER\x10c\"\xe3\x06\n" +
	"\rDispositionId\x12\x1a\n" +
	"\x16DISPOSITION_ID_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16DISPOSITION_ID_ALLOWED\x10\x01\x12\x1a\n" +
	"\x16DISPOSITION_ID_BLOCKED\x10\x02\x12\x1e\n" +
	"\x1aDISPOSITION_ID_QUARANTINED\x10\x03\x12\x1b\n" +
	"\x17DISPOSITION_ID_ISOLATED\x10\x04\x12\x1a\n" +
	"\x16DISPOSITION_ID_DELETED\x10\x05\x12\x1a\n" +
	"\x16DISPOSITION_ID_DROPPED\x10\x06\x12 \n" +
	"\x1cDISPOSITION_ID_CUSTOM_ACTION\x10\a\x12\x1b\n" +
	"\x17DISPOSITION_ID_APPROVED\x10\b\x12\x1b\n" +
	"\x17DISPOSITION_ID_RESTORED\x10\t\x12\x1d\n" +
	"\x19DISPOSITION_ID_EXONERATED\x10\n" +
	"\x12\x1c\n" +
	"\x18DISPOSITION_ID_CORRECTED\x10\v\x12&\n" +
	"\"DISPOSITION_ID_PARTIALLY_CORRECTED\x10\f\x12\x1e\n" +
	"\x1aDISPOSITION_ID_UNCORRECTED\x10\r\x12\x1a\n" +
	"\x16DISPOSITION_ID_DELAYED\x10\x0e\x12\x1b\n" +
	"\x17DISPOSITION_ID_DETECTED\x10\x0f\x12\x1c\n" +
	"\x18DISPOSITION_ID_NO_ACTION\x10\x10\x12\x19\n" +
	"\x15DISPOSITION_ID_LOGGED\x10\x11\x12\x19\n" +
	"\x15DISPOSITION_ID_TAGGED\x10\x12\x12\x18\n" +
	"\x14DISPOSITION_ID_ALERT\x10\x13\x12\x18\n" +
	"\x14DISPOSITION_ID_COUNT\x10\x14\x12\x18\n" +
	"\x14DISPOSITION_ID_RESET\x10\x15\x12\x1a\n" +
	"\x16DISPOSITION_ID_CAPTCHA\x10\x16\x12\x1c\n" +
	"\x18DISPOSITION_ID_CHALLENGE\x10\x17\x12!\n" +
	"\x1dDISPOSITION_ID_ACCESS_REVOKED\x10\x18\x12\x1b\n" +
	"\x17DISPOSITION_ID_REJECTED\x10\x19\x12\x1f\n" +
	"\x1bDISPOSITION_ID_UNAUTHORIZED\x10\x1a\x12\x18\n" +
	"\x14DISPOSITION_ID_ERROR\x10\x1b\x12\x18\n" +
	"\x14DISPOSITION_ID_OTHER\x10c\"\xa3\x01\n" +
	"\vRiskLevelId\x12\x16\n" +
	"\x12RISK_LEVEL_ID_INFO\x10\x00\x12\x15\n" +
	"\x11RISK_LEVEL_ID_LOW\x10\x01\x12\x18\n" +
	"\x14RISK_LEVEL_ID_MEDIUM\x10\x02\x12\x16\n" +
	"\x12RISK_LEVEL_ID_HIGH\x10\x03\x12\x1a\n" +
	"\x16RISK_LEVEL_ID_CRITICAL\x10\x04\x12\x17\n" +
	"\x13RISK_LEVEL_ID_OTHER\x10c\"\xcf\x01\n" +
	"\n" +
	"SeverityId\x12\x17\n" +
	"\x13SEVERITY_ID_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19SEVERITY_ID_INFORMATIONAL\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_ID_LOW\x10\x02\x12\x16\n" +
	"\x12SEVERITY_ID_MEDIUM\x10\x03\x12\x14\n" +
	"\x10SEVERITY_ID_HIGH\x10\x04\x12\x18\n" +
	"\x14SEVERITY_ID_CRITICAL\x10\x05\x12\x15\n" +
	"\x11SEVERITY_ID_FATAL\x10\x06\x12\x15\n" +
	"\x11SEVERITY_ID_OTHER\x10c\"d\n" +
	"\bStatusId\x12\x15\n" +
	"\x11STATUS_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11STATUS_ID_SUCCESS\x10\x01\x12\x15\n" +
	"\x11STATUS_ID_FAILURE\x10\x02\x12\x13\n" +
	"\x0fSTATUS_ID_OTHER\x10c\"\xf5\x01\n" +
	"\aTypeUid\x12\x14\n" +
	"\x10TYPE_UID_UNKNOWN\x10\x00\x12#\n" +
	"\x1dTYPE_UID_API_ACTIVITY_UNKNOWN\x10\xec\xd1$\x12\"\n" +
	"\x1cTYPE_UID_API_ACTIVITY_CREATE\x10\xed\xd1$\x12 \n" +
	"\x1aTYPE_UID_API_ACTIVITY_READ\x10\xee\xd1$\x12\"\n" +
	"\x1cTYPE_UID_API_ACTIVITY_UPDATE\x10\xef\xd1$\x12\"\n" +
	"\x1cTYPE_UID_API_ACTIVITY_DELETE\x10\xf0\xd1$\x12!\n" +
	"\x1bTYPE_UID_API_ACTIVITY_OTHER\x10\xcf\xd2$b\x06proto3"

var (
	file_ocsf_v1_api_activity_proto_rawDescOnce sync.Once
	file_ocsf_v1_api_activity_proto_rawDescData []byte
)

func file_ocsf_v1_api_activity_proto_rawDescGZIP() []byte {
	file_ocsf_v1_api_activity_proto_rawDescOnce.Do(func() {
		file_ocsf_v1_api_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocsf_v1_api_activity_proto_rawDesc), len(file_ocsf_v1_api_activity_proto_rawDesc)))
	})
	return file_ocsf_v1_api_activity_proto_rawDescData
}

var file_ocsf_v1_api_activity_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_ocsf_v1_api_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ocsf_v1_api_activity_proto_goTypes = []any{
	(ApiActivity_ActionId)(0),      // 0: ocsf.v1.ApiActivity.ActionId
	(ApiActivity_ActivityId)(0),    // 1: ocsf.v1.ApiActivity.ActivityId
	(ApiActivity_CategoryUid)(0),   // 2: ocsf.v1.ApiActivity.CategoryUid
	(ApiActivity_ClassUid)(0),      // 3: ocsf.v1.ApiActivity.ClassUid
	(ApiActivity_ConfidenceId)(0),  // 4: ocsf.v1.ApiActivity.ConfidenceId
	(ApiActivity_DispositionId)(0), // 5: ocsf.v1.ApiActivity.DispositionId
	(ApiActivity_RiskLevelId)(0),   // 6: ocsf.v1.ApiActivity.RiskLevelId
	(ApiActivity_SeverityId)(0),    // 7: ocsf.v1.ApiActivity.SeverityId
	(ApiActivity_StatusId)(0),      // 8: ocsf.v1.ApiActivity.StatusId
	(ApiActivity_TypeUid)(0),       // 9: ocsf.v1.ApiActivity.TypeUid
	(*ApiActivity)(nil),            // 10: ocsf.v1.ApiActivity
	(*Actor)(nil),                  // 11: ocsf.v1.Actor
	(*AiModel)(nil),                // 12: ocsf.v1.AiModel
	(*Api)(nil),                    // 13: ocsf.v1.Api
	(*Attack)(nil),                 // 14: ocsf.v1.Attack
	(*Authorization)(nil),          // 15: ocsf.v1.Authorization
	(*Cloud)(nil),                  // 16: ocsf.v1.Cloud
	(*Device)(nil),                 // 17: ocsf.v1.Device
	(*NetworkEndpoint)(nil),        // 18: ocsf.v1.NetworkEndpoint
	(*Enrichment)(nil),             // 19: ocsf.v1.Enrichment
	(*FirewallRule)(nil),           // 20: ocsf.v1.FirewallRule
	(*HttpRequest)(nil),            // 21: ocsf.v1.HttpRequest
	(*HttpResponse)(nil),           // 22: ocsf.v1.HttpResponse
	(*Malware)(nil),                // 23: ocsf.v1.Malware
	(*MalwareScanInfo)(nil),        // 24: ocsf.v1.MalwareScanInfo
	(*MessageContext)(nil),         // 25: ocsf.v1.MessageContext
	(*Metadata)(nil),               // 26: ocsf.v1.Metadata
	(*Observable)(nil),             // 27: ocsf.v1.Observable
	(*Osint)(nil),                  // 28: ocsf.v1.Osint
	(*Policy)(nil),                 // 29: ocsf.v1.Policy
	(*Fingerprint)(nil),            // 30: ocsf.v1.Fingerprint
	(*ResourceDetails)(nil),        // 31: ocsf.v1.ResourceDetails
	(*Trace)(nil),                  // 32: ocsf.v1.Trace
	(*structpb.Value)(nil),         // 33: google.protobuf.Value
}
var file_ocsf_v1_api_activity_proto_depIdxs = []int32{
	0,  // 0: ocsf.v1.ApiActivity.action_id:type_name -> ocsf.v1.ApiActivity.ActionId
	1,  // 1: ocsf.v1.ApiActivity.activity_id:type_name -> ocsf.v1.ApiActivity.ActivityId
	11, // 2: ocsf.v1.ApiActivity.actor:type_name -> ocsf.v1.Actor
	12, // 3: ocsf.v1.ApiActivity.ai_model:type_name -> ocsf.v1.AiModel
	13, // 4: ocsf.v1.ApiActivity.api:type_name -> ocsf.v1.Api
	14, // 5: ocsf.v1.ApiActivity.attacks:type_name -> ocsf.v1.Attack
	15, // 6: ocsf.v1.ApiActivity.authorizations:type_name -> ocsf.v1.Authorization
	2,  // 7: ocsf.v1.ApiActivity.category_uid:type_name -> ocsf.v1.ApiActivity.CategoryUid
	3,  // 8: ocsf.v1.ApiActivity.class_uid:type_name -> ocsf.v1.ApiActivity.ClassUid
	16, // 9: ocsf.v1.ApiActivity.cloud:type_name -> ocsf.v1.Cloud
	4,  // 10: ocsf.v1.ApiActivity.confidence_id:type_name -> ocsf.v1.ApiActivity.ConfidenceId
	17, // 11: ocsf.v1.ApiActivity.device:type_name -> ocsf.v1.Device
	5,  // 12: ocsf.v1.ApiActivity.disposition_id:type_name -> ocsf.v1.ApiActivity.DispositionId
	18, // 13: ocsf.v1.ApiActivity.dst_endpoint:type_name -> ocsf.v1.NetworkEndpoint
	19, // 14: ocsf.v1.ApiActivity.enrichments:type_name -> ocsf.v1.Enrichment
	20, // 15: ocsf.v1.ApiActivity.firewall_rule:type_name -> ocsf.v1.FirewallRule
	21, // 16: ocsf.v1.ApiActivity.http_request:type_name -> ocsf.v1.HttpRequest
	22, // 17: ocsf.v1.ApiActivity.http_response:type_name -> ocsf.v1.HttpResponse
	23, // 18: ocsf.v1.ApiActivity.malware:type_name -> ocsf.v1.Malware
	24, // 19: ocsf.v1.ApiActivity.malware_scan_info:type_name -> ocsf.v1.MalwareScanInfo
	25, // 20: ocsf.v1.ApiActivity.message_context:type_name -> ocsf.v1.MessageContext
	26, // 21: ocsf.v1.ApiActivity.metadata:type_name -> ocsf.v1.Metadata
	27, // 22: ocsf.v1.ApiActivity.observables:type_name -> ocsf.v1.Observable
	28, // 23: ocsf.v1.ApiActivity.osint:type_name -> ocsf.v1.Osint
	29, // 24: ocsf.v1.ApiActivity.policy:type_name -> ocsf.v1.Policy
	30, // 25: ocsf.v1.ApiActivity.raw_data_hash:type_name -> ocsf.v1.Fingerprint
	31, // 26: ocsf.v1.ApiActivity.resources:type_name -> ocsf.v1.ResourceDetails
	6,  // 27: ocsf.v1.ApiActivity.risk_level_id:type_name -> ocsf.v1.ApiActivity.RiskLevelId
	7,  // 28: ocsf.v1.ApiActivity.severity_id:type_name -> ocsf.v1.ApiActivity.SeverityId
	18, // 29: ocsf.v1.ApiActivity.src_endpoint:type_name -> ocsf.v1.NetworkEndpoint
	8,  // 30: ocsf.v1.ApiActivity.status_id:type_name -> ocsf.v1.ApiActivity.StatusId
	32, // 31: ocsf.v1.ApiActivity.trace:type_name -> ocsf.v1.Trace
	9,  // 32: ocsf.v1.ApiActivity.type_uid:type_name -> ocsf.v1.ApiActivity.TypeUid
	33, // 33: ocsf.v1.ApiActivity.unmapped:type_name -> google.protobuf.Value
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_ocsf_v1_api_activity_proto_init() }
func file_ocsf_v1_api_activity_proto_init() {
	if File_ocsf_v1_api_activity_proto != nil {
		return
	}
	file_ocsf_v1_objects_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_api_activity_proto_rawDesc), len(file_ocsf_v1_api_activity_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_api_activity_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_api_activity_proto_depIdxs,
		EnumInfos:         file_ocsf_v1_api_activity_proto_enumTypes,
		MessageInfos:      file_ocsf_v1_api_activity_proto_msgTypes,
	}.Build()
	File_ocsf_v1_api_activity_proto = out.File
	file_ocsf_v1_api_activity_proto_goTypes = nil
	file_ocsf_v1_api_activity_proto_depIdxs = nil
}
