// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by ocsf-protogen. DO NOT EDIT.
// Source: OCSF schema 1.8.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ocsf/v1/audit_event.proto

package ocsfv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "buf.build/gen/go/redpandadata/common/protocolbuffers/go/redpanda/api/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEvent_ActionId int32

const (
	AuditEvent_ACTION_ID_UNKNOWN  AuditEvent_ActionId = 0
	AuditEvent_ACTION_ID_ALLOWED  AuditEvent_ActionId = 1
	AuditEvent_ACTION_ID_DENIED   AuditEvent_ActionId = 2
	AuditEvent_ACTION_ID_OBSERVED AuditEvent_ActionId = 3
	AuditEvent_ACTION_ID_MODIFIED AuditEvent_ActionId = 4
	AuditEvent_ACTION_ID_OTHER    AuditEvent_ActionId = 99
)

// Enum value maps for AuditEvent_ActionId.
var (
	AuditEvent_ActionId_name = map[int32]string{
		0:  "ACTION_ID_UNKNOWN",
		1:  "ACTION_ID_ALLOWED",
		2:  "ACTION_ID_DENIED",
		3:  "ACTION_ID_OBSERVED",
		4:  "ACTION_ID_MODIFIED",
		99: "ACTION_ID_OTHER",
	}
	AuditEvent_ActionId_value = map[string]int32{
		"ACTION_ID_UNKNOWN":  0,
		"ACTION_ID_ALLOWED":  1,
		"ACTION_ID_DENIED":   2,
		"ACTION_ID_OBSERVED": 3,
		"ACTION_ID_MODIFIED": 4,
		"ACTION_ID_OTHER":    99,
	}
)

func (x AuditEvent_ActionId) Enum() *AuditEvent_ActionId {
	p := new(AuditEvent_ActionId)
	*p = x
	return p
}

func (x AuditEvent_ActionId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_ActionId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[0].Descriptor()
}

func (AuditEvent_ActionId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[0]
}

func (x AuditEvent_ActionId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_ActionId.Descriptor instead.
func (AuditEvent_ActionId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 0}
}

type AuditEvent_CategoryUid int32

const (
	AuditEvent_CATEGORY_UID_UNKNOWN                    AuditEvent_CategoryUid = 0
	AuditEvent_CATEGORY_UID_IDENTITY_ACCESS_MANAGEMENT AuditEvent_CategoryUid = 3
	AuditEvent_CATEGORY_UID_APPLICATION_ACTIVITY       AuditEvent_CategoryUid = 6
)

// Enum value maps for AuditEvent_CategoryUid.
var (
	AuditEvent_CategoryUid_name = map[int32]string{
		0: "CATEGORY_UID_UNKNOWN",
		3: "CATEGORY_UID_IDENTITY_ACCESS_MANAGEMENT",
		6: "CATEGORY_UID_APPLICATION_ACTIVITY",
	}
	AuditEvent_CategoryUid_value = map[string]int32{
		"CATEGORY_UID_UNKNOWN":                    0,
		"CATEGORY_UID_IDENTITY_ACCESS_MANAGEMENT": 3,
		"CATEGORY_UID_APPLICATION_ACTIVITY":       6,
	}
)

func (x AuditEvent_CategoryUid) Enum() *AuditEvent_CategoryUid {
	p := new(AuditEvent_CategoryUid)
	*p = x
	return p
}

func (x AuditEvent_CategoryUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_CategoryUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[1].Descriptor()
}

func (AuditEvent_CategoryUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[1]
}

func (x AuditEvent_CategoryUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_CategoryUid.Descriptor instead.
func (AuditEvent_CategoryUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 1}
}

type AuditEvent_ClassUid int32

const (
	AuditEvent_CLASS_UID_UNKNOWN           AuditEvent_ClassUid = 0
	AuditEvent_CLASS_UID_ENTITY_MANAGEMENT AuditEvent_ClassUid = 3004
	AuditEvent_CLASS_UID_API_ACTIVITY      AuditEvent_ClassUid = 6003
)

// Enum value maps for AuditEvent_ClassUid.
var (
	AuditEvent_ClassUid_name = map[int32]string{
		0:    "CLASS_UID_UNKNOWN",
		3004: "CLASS_UID_ENTITY_MANAGEMENT",
		6003: "CLASS_UID_API_ACTIVITY",
	}
	AuditEvent_ClassUid_value = map[string]int32{
		"CLASS_UID_UNKNOWN":           0,
		"CLASS_UID_ENTITY_MANAGEMENT": 3004,
		"CLASS_UID_API_ACTIVITY":      6003,
	}
)

func (x AuditEvent_ClassUid) Enum() *AuditEvent_ClassUid {
	p := new(AuditEvent_ClassUid)
	*p = x
	return p
}

func (x AuditEvent_ClassUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_ClassUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[2].Descriptor()
}

func (AuditEvent_ClassUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[2]
}

func (x AuditEvent_ClassUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_ClassUid.Descriptor instead.
func (AuditEvent_ClassUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 2}
}

type AuditEvent_ConfidenceId int32

const (
	AuditEvent_CONFIDENCE_ID_UNKNOWN AuditEvent_ConfidenceId = 0
	AuditEvent_CONFIDENCE_ID_LOW     AuditEvent_ConfidenceId = 1
	AuditEvent_CONFIDENCE_ID_MEDIUM  AuditEvent_ConfidenceId = 2
	AuditEvent_CONFIDENCE_ID_HIGH    AuditEvent_ConfidenceId = 3
	AuditEvent_CONFIDENCE_ID_OTHER   AuditEvent_ConfidenceId = 99
)

// Enum value maps for AuditEvent_ConfidenceId.
var (
	AuditEvent_ConfidenceId_name = map[int32]string{
		0:  "CONFIDENCE_ID_UNKNOWN",
		1:  "CONFIDENCE_ID_LOW",
		2:  "CONFIDENCE_ID_MEDIUM",
		3:  "CONFIDENCE_ID_HIGH",
		99: "CONFIDENCE_ID_OTHER",
	}
	AuditEvent_ConfidenceId_value = map[string]int32{
		"CONFIDENCE_ID_UNKNOWN": 0,
		"CONFIDENCE_ID_LOW":     1,
		"CONFIDENCE_ID_MEDIUM":  2,
		"CONFIDENCE_ID_HIGH":    3,
		"CONFIDENCE_ID_OTHER":   99,
	}
)

func (x AuditEvent_ConfidenceId) Enum() *AuditEvent_ConfidenceId {
	p := new(AuditEvent_ConfidenceId)
	*p = x
	return p
}

func (x AuditEvent_ConfidenceId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_ConfidenceId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[3].Descriptor()
}

func (AuditEvent_ConfidenceId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[3]
}

func (x AuditEvent_ConfidenceId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_ConfidenceId.Descriptor instead.
func (AuditEvent_ConfidenceId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 3}
}

type AuditEvent_DispositionId int32

const (
	AuditEvent_DISPOSITION_ID_UNKNOWN             AuditEvent_DispositionId = 0
	AuditEvent_DISPOSITION_ID_ALLOWED             AuditEvent_DispositionId = 1
	AuditEvent_DISPOSITION_ID_BLOCKED             AuditEvent_DispositionId = 2
	AuditEvent_DISPOSITION_ID_QUARANTINED         AuditEvent_DispositionId = 3
	AuditEvent_DISPOSITION_ID_ISOLATED            AuditEvent_DispositionId = 4
	AuditEvent_DISPOSITION_ID_DELETED             AuditEvent_DispositionId = 5
	AuditEvent_DISPOSITION_ID_DROPPED             AuditEvent_DispositionId = 6
	AuditEvent_DISPOSITION_ID_CUSTOM_ACTION       AuditEvent_DispositionId = 7
	AuditEvent_DISPOSITION_ID_APPROVED            AuditEvent_DispositionId = 8
	AuditEvent_DISPOSITION_ID_RESTORED            AuditEvent_DispositionId = 9
	AuditEvent_DISPOSITION_ID_EXONERATED          AuditEvent_DispositionId = 10
	AuditEvent_DISPOSITION_ID_CORRECTED           AuditEvent_DispositionId = 11
	AuditEvent_DISPOSITION_ID_PARTIALLY_CORRECTED AuditEvent_DispositionId = 12
	AuditEvent_DISPOSITION_ID_UNCORRECTED         AuditEvent_DispositionId = 13
	AuditEvent_DISPOSITION_ID_DELAYED             AuditEvent_DispositionId = 14
	AuditEvent_DISPOSITION_ID_DETECTED            AuditEvent_DispositionId = 15
	AuditEvent_DISPOSITION_ID_NO_ACTION           AuditEvent_DispositionId = 16
	AuditEvent_DISPOSITION_ID_LOGGED              AuditEvent_DispositionId = 17
	AuditEvent_DISPOSITION_ID_TAGGED              AuditEvent_DispositionId = 18
	AuditEvent_DISPOSITION_ID_ALERT               AuditEvent_DispositionId = 19
	AuditEvent_DISPOSITION_ID_COUNT               AuditEvent_DispositionId = 20
	AuditEvent_DISPOSITION_ID_RESET               AuditEvent_DispositionId = 21
	AuditEvent_DISPOSITION_ID_CAPTCHA             AuditEvent_DispositionId = 22
	AuditEvent_DISPOSITION_ID_CHALLENGE           AuditEvent_DispositionId = 23
	AuditEvent_DISPOSITION_ID_ACCESS_REVOKED      AuditEvent_DispositionId = 24
	AuditEvent_DISPOSITION_ID_REJECTED            AuditEvent_DispositionId = 25
	AuditEvent_DISPOSITION_ID_UNAUTHORIZED        AuditEvent_DispositionId = 26
	AuditEvent_DISPOSITION_ID_ERROR               AuditEvent_DispositionId = 27
	AuditEvent_DISPOSITION_ID_OTHER               AuditEvent_DispositionId = 99
)

// Enum value maps for AuditEvent_DispositionId.
var (
	AuditEvent_DispositionId_name = map[int32]string{
		0:  "DISPOSITION_ID_UNKNOWN",
		1:  "DISPOSITION_ID_ALLOWED",
		2:  "DISPOSITION_ID_BLOCKED",
		3:  "DISPOSITION_ID_QUARANTINED",
		4:  "DISPOSITION_ID_ISOLATED",
		5:  "DISPOSITION_ID_DELETED",
		6:  "DISPOSITION_ID_DROPPED",
		7:  "DISPOSITION_ID_CUSTOM_ACTION",
		8:  "DISPOSITION_ID_APPROVED",
		9:  "DISPOSITION_ID_RESTORED",
		10: "DISPOSITION_ID_EXONERATED",
		11: "DISPOSITION_ID_CORRECTED",
		12: "DISPOSITION_ID_PARTIALLY_CORRECTED",
		13: "DISPOSITION_ID_UNCORRECTED",
		14: "DISPOSITION_ID_DELAYED",
		15: "DISPOSITION_ID_DETECTED",
		16: "DISPOSITION_ID_NO_ACTION",
		17: "DISPOSITION_ID_LOGGED",
		18: "DISPOSITION_ID_TAGGED",
		19: "DISPOSITION_ID_ALERT",
		20: "DISPOSITION_ID_COUNT",
		21: "DISPOSITION_ID_RESET",
		22: "DISPOSITION_ID_CAPTCHA",
		23: "DISPOSITION_ID_CHALLENGE",
		24: "DISPOSITION_ID_ACCESS_REVOKED",
		25: "DISPOSITION_ID_REJECTED",
		26: "DISPOSITION_ID_UNAUTHORIZED",
		27: "DISPOSITION_ID_ERROR",
		99: "DISPOSITION_ID_OTHER",
	}
	AuditEvent_DispositionId_value = map[string]int32{
		"DISPOSITION_ID_UNKNOWN":             0,
		"DISPOSITION_ID_ALLOWED":             1,
		"DISPOSITION_ID_BLOCKED":             2,
		"DISPOSITION_ID_QUARANTINED":         3,
		"DISPOSITION_ID_ISOLATED":            4,
		"DISPOSITION_ID_DELETED":             5,
		"DISPOSITION_ID_DROPPED":             6,
		"DISPOSITION_ID_CUSTOM_ACTION":       7,
		"DISPOSITION_ID_APPROVED":            8,
		"DISPOSITION_ID_RESTORED":            9,
		"DISPOSITION_ID_EXONERATED":          10,
		"DISPOSITION_ID_CORRECTED":           11,
		"DISPOSITION_ID_PARTIALLY_CORRECTED": 12,
		"DISPOSITION_ID_UNCORRECTED":         13,
		"DISPOSITION_ID_DELAYED":             14,
		"DISPOSITION_ID_DETECTED":            15,
		"DISPOSITION_ID_NO_ACTION":           16,
		"DISPOSITION_ID_LOGGED":              17,
		"DISPOSITION_ID_TAGGED":              18,
		"DISPOSITION_ID_ALERT":               19,
		"DISPOSITION_ID_COUNT":               20,
		"DISPOSITION_ID_RESET":               21,
		"DISPOSITION_ID_CAPTCHA":             22,
		"DISPOSITION_ID_CHALLENGE":           23,
		"DISPOSITION_ID_ACCESS_REVOKED":      24,
		"DISPOSITION_ID_REJECTED":            25,
		"DISPOSITION_ID_UNAUTHORIZED":        26,
		"DISPOSITION_ID_ERROR":               27,
		"DISPOSITION_ID_OTHER":               99,
	}
)

func (x AuditEvent_DispositionId) Enum() *AuditEvent_DispositionId {
	p := new(AuditEvent_DispositionId)
	*p = x
	return p
}

func (x AuditEvent_DispositionId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_DispositionId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[4].Descriptor()
}

func (AuditEvent_DispositionId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[4]
}

func (x AuditEvent_DispositionId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_DispositionId.Descriptor instead.
func (AuditEvent_DispositionId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 4}
}

type AuditEvent_RiskLevelId int32

const (
	AuditEvent_RISK_LEVEL_ID_INFO     AuditEvent_RiskLevelId = 0
	AuditEvent_RISK_LEVEL_ID_LOW      AuditEvent_RiskLevelId = 1
	AuditEvent_RISK_LEVEL_ID_MEDIUM   AuditEvent_RiskLevelId = 2
	AuditEvent_RISK_LEVEL_ID_HIGH     AuditEvent_RiskLevelId = 3
	AuditEvent_RISK_LEVEL_ID_CRITICAL AuditEvent_RiskLevelId = 4
	AuditEvent_RISK_LEVEL_ID_OTHER    AuditEvent_RiskLevelId = 99
)

// Enum value maps for AuditEvent_RiskLevelId.
var (
	AuditEvent_RiskLevelId_name = map[int32]string{
		0:  "RISK_LEVEL_ID_INFO",
		1:  "RISK_LEVEL_ID_LOW",
		2:  "RISK_LEVEL_ID_MEDIUM",
		3:  "RISK_LEVEL_ID_HIGH",
		4:  "RISK_LEVEL_ID_CRITICAL",
		99: "RISK_LEVEL_ID_OTHER",
	}
	AuditEvent_RiskLevelId_value = map[string]int32{
		"RISK_LEVEL_ID_INFO":     0,
		"RISK_LEVEL_ID_LOW":      1,
		"RISK_LEVEL_ID_MEDIUM":   2,
		"RISK_LEVEL_ID_HIGH":     3,
		"RISK_LEVEL_ID_CRITICAL": 4,
		"RISK_LEVEL_ID_OTHER":    99,
	}
)

func (x AuditEvent_RiskLevelId) Enum() *AuditEvent_RiskLevelId {
	p := new(AuditEvent_RiskLevelId)
	*p = x
	return p
}

func (x AuditEvent_RiskLevelId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_RiskLevelId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[5].Descriptor()
}

func (AuditEvent_RiskLevelId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[5]
}

func (x AuditEvent_RiskLevelId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_RiskLevelId.Descriptor instead.
func (AuditEvent_RiskLevelId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 5}
}

type AuditEvent_SeverityId int32

const (
	AuditEvent_SEVERITY_ID_UNKNOWN       AuditEvent_SeverityId = 0
	AuditEvent_SEVERITY_ID_INFORMATIONAL AuditEvent_SeverityId = 1
	AuditEvent_SEVERITY_ID_LOW           AuditEvent_SeverityId = 2
	AuditEvent_SEVERITY_ID_MEDIUM        AuditEvent_SeverityId = 3
	AuditEvent_SEVERITY_ID_HIGH          AuditEvent_SeverityId = 4
	AuditEvent_SEVERITY_ID_CRITICAL      AuditEvent_SeverityId = 5
	AuditEvent_SEVERITY_ID_FATAL         AuditEvent_SeverityId = 6
	AuditEvent_SEVERITY_ID_OTHER         AuditEvent_SeverityId = 99
)

// Enum value maps for AuditEvent_SeverityId.
var (
	AuditEvent_SeverityId_name = map[int32]string{
		0:  "SEVERITY_ID_UNKNOWN",
		1:  "SEVERITY_ID_INFORMATIONAL",
		2:  "SEVERITY_ID_LOW",
		3:  "SEVERITY_ID_MEDIUM",
		4:  "SEVERITY_ID_HIGH",
		5:  "SEVERITY_ID_CRITICAL",
		6:  "SEVERITY_ID_FATAL",
		99: "SEVERITY_ID_OTHER",
	}
	AuditEvent_SeverityId_value = map[string]int32{
		"SEVERITY_ID_UNKNOWN":       0,
		"SEVERITY_ID_INFORMATIONAL": 1,
		"SEVERITY_ID_LOW":           2,
		"SEVERITY_ID_MEDIUM":        3,
		"SEVERITY_ID_HIGH":          4,
		"SEVERITY_ID_CRITICAL":      5,
		"SEVERITY_ID_FATAL":         6,
		"SEVERITY_ID_OTHER":         99,
	}
)

func (x AuditEvent_SeverityId) Enum() *AuditEvent_SeverityId {
	p := new(AuditEvent_SeverityId)
	*p = x
	return p
}

func (x AuditEvent_SeverityId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_SeverityId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[6].Descriptor()
}

func (AuditEvent_SeverityId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[6]
}

func (x AuditEvent_SeverityId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_SeverityId.Descriptor instead.
func (AuditEvent_SeverityId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 6}
}

type AuditEvent_StatusId int32

const (
	AuditEvent_STATUS_ID_UNKNOWN AuditEvent_StatusId = 0
	AuditEvent_STATUS_ID_SUCCESS AuditEvent_StatusId = 1
	AuditEvent_STATUS_ID_FAILURE AuditEvent_StatusId = 2
	AuditEvent_STATUS_ID_OTHER   AuditEvent_StatusId = 99
)

// Enum value maps for AuditEvent_StatusId.
var (
	AuditEvent_StatusId_name = map[int32]string{
		0:  "STATUS_ID_UNKNOWN",
		1:  "STATUS_ID_SUCCESS",
		2:  "STATUS_ID_FAILURE",
		99: "STATUS_ID_OTHER",
	}
	AuditEvent_StatusId_value = map[string]int32{
		"STATUS_ID_UNKNOWN": 0,
		"STATUS_ID_SUCCESS": 1,
		"STATUS_ID_FAILURE": 2,
		"STATUS_ID_OTHER":   99,
	}
)

func (x AuditEvent_StatusId) Enum() *AuditEvent_StatusId {
	p := new(AuditEvent_StatusId)
	*p = x
	return p
}

func (x AuditEvent_StatusId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_StatusId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[7].Descriptor()
}

func (AuditEvent_StatusId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[7]
}

func (x AuditEvent_StatusId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_StatusId.Descriptor instead.
func (AuditEvent_StatusId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 7}
}

type AuditEvent_TypeUid int32

const (
	AuditEvent_TYPE_UID_UNKNOWN                      AuditEvent_TypeUid = 0
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_UNKNOWN    AuditEvent_TypeUid = 300400
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_CREATE     AuditEvent_TypeUid = 300401
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_READ       AuditEvent_TypeUid = 300402
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_UPDATE     AuditEvent_TypeUid = 300403
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_DELETE     AuditEvent_TypeUid = 300404
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_MOVE       AuditEvent_TypeUid = 300405
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_ENROLL     AuditEvent_TypeUid = 300406
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_UNENROLL   AuditEvent_TypeUid = 300407
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_ENABLE     AuditEvent_TypeUid = 300408
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_DISABLE    AuditEvent_TypeUid = 300409
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_ACTIVATE   AuditEvent_TypeUid = 300410
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_DEACTIVATE AuditEvent_TypeUid = 300411
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_SUSPEND    AuditEvent_TypeUid = 300412
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_RESUME     AuditEvent_TypeUid = 300413
	AuditEvent_TYPE_UID_ENTITY_MANAGEMENT_OTHER      AuditEvent_TypeUid = 300499
	AuditEvent_TYPE_UID_API_ACTIVITY_UNKNOWN         AuditEvent_TypeUid = 600300
	AuditEvent_TYPE_UID_API_ACTIVITY_CREATE          AuditEvent_TypeUid = 600301
	AuditEvent_TYPE_UID_API_ACTIVITY_READ            AuditEvent_TypeUid = 600302
	AuditEvent_TYPE_UID_API_ACTIVITY_UPDATE          AuditEvent_TypeUid = 600303
	AuditEvent_TYPE_UID_API_ACTIVITY_DELETE          AuditEvent_TypeUid = 600304
	AuditEvent_TYPE_UID_API_ACTIVITY_OTHER           AuditEvent_TypeUid = 600399
)

// Enum value maps for AuditEvent_TypeUid.
var (
	AuditEvent_TypeUid_name = map[int32]string{
		0:      "TYPE_UID_UNKNOWN",
		300400: "TYPE_UID_ENTITY_MANAGEMENT_UNKNOWN",
		300401: "TYPE_UID_ENTITY_MANAGEMENT_CREATE",
		300402: "TYPE_UID_ENTITY_MANAGEMENT_READ",
		300403: "TYPE_UID_ENTITY_MANAGEMENT_UPDATE",
		300404: "TYPE_UID_ENTITY_MANAGEMENT_DELETE",
		300405: "TYPE_UID_ENTITY_MANAGEMENT_MOVE",
		300406: "TYPE_UID_ENTITY_MANAGEMENT_ENROLL",
		300407: "TYPE_UID_ENTITY_MANAGEMENT_UNENROLL",
		300408: "TYPE_UID_ENTITY_MANAGEMENT_ENABLE",
		300409: "TYPE_UID_ENTITY_MANAGEMENT_DISABLE",
		300410: "TYPE_UID_ENTITY_MANAGEMENT_ACTIVATE",
		300411: "TYPE_UID_ENTITY_MANAGEMENT_DEACTIVATE",
		300412: "TYPE_UID_ENTITY_MANAGEMENT_SUSPEND",
		300413: "TYPE_UID_ENTITY_MANAGEMENT_RESUME",
		300499: "TYPE_UID_ENTITY_MANAGEMENT_OTHER",
		600300: "TYPE_UID_API_ACTIVITY_UNKNOWN",
		600301: "TYPE_UID_API_ACTIVITY_CREATE",
		600302: "TYPE_UID_API_ACTIVITY_READ",
		600303: "TYPE_UID_API_ACTIVITY_UPDATE",
		600304: "TYPE_UID_API_ACTIVITY_DELETE",
		600399: "TYPE_UID_API_ACTIVITY_OTHER",
	}
	AuditEvent_TypeUid_value = map[string]int32{
		"TYPE_UID_UNKNOWN":                      0,
		"TYPE_UID_ENTITY_MANAGEMENT_UNKNOWN":    300400,
		"TYPE_UID_ENTITY_MANAGEMENT_CREATE":     300401,
		"TYPE_UID_ENTITY_MANAGEMENT_READ":       300402,
		"TYPE_UID_ENTITY_MANAGEMENT_UPDATE":     300403,
		"TYPE_UID_ENTITY_MANAGEMENT_DELETE":     300404,
		"TYPE_UID_ENTITY_MANAGEMENT_MOVE":       300405,
		"TYPE_UID_ENTITY_MANAGEMENT_ENROLL":     300406,
		"TYPE_UID_ENTITY_MANAGEMENT_UNENROLL":   300407,
		"TYPE_UID_ENTITY_MANAGEMENT_ENABLE":     300408,
		"TYPE_UID_ENTITY_MANAGEMENT_DISABLE":    300409,
		"TYPE_UID_ENTITY_MANAGEMENT_ACTIVATE":   300410,
		"TYPE_UID_ENTITY_MANAGEMENT_DEACTIVATE": 300411,
		"TYPE_UID_ENTITY_MANAGEMENT_SUSPEND":    300412,
		"TYPE_UID_ENTITY_MANAGEMENT_RESUME":     300413,
		"TYPE_UID_ENTITY_MANAGEMENT_OTHER":      300499,
		"TYPE_UID_API_ACTIVITY_UNKNOWN":         600300,
		"TYPE_UID_API_ACTIVITY_CREATE":          600301,
		"TYPE_UID_API_ACTIVITY_READ":            600302,
		"TYPE_UID_API_ACTIVITY_UPDATE":          600303,
		"TYPE_UID_API_ACTIVITY_DELETE":          600304,
		"TYPE_UID_API_ACTIVITY_OTHER":           600399,
	}
)

func (x AuditEvent_TypeUid) Enum() *AuditEvent_TypeUid {
	p := new(AuditEvent_TypeUid)
	*p = x
	return p
}

func (x AuditEvent_TypeUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditEvent_TypeUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_audit_event_proto_enumTypes[8].Descriptor()
}

func (AuditEvent_TypeUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_audit_event_proto_enumTypes[8]
}

func (x AuditEvent_TypeUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditEvent_TypeUid.Descriptor instead.
func (AuditEvent_TypeUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0, 8}
}

type AuditEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	AccessList []string               `protobuf:"bytes,1,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	AccessMask int32                  `protobuf:"varint,2,opt,name=access_mask,json=accessMask,proto3" json:"access_mask,omitempty"`
	Action     string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ActionId   AuditEvent_ActionId    `protobuf:"varint,4,opt,name=action_id,json=actionId,proto3,enum=ocsf.v1.AuditEvent_ActionId" json:"action_id,omitempty"`
	// Class-scoped enum: value semantics depend on class_uid; see TypeUid.
	ActivityId      int32                    `protobuf:"varint,5,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	ActivityName    string                   `protobuf:"bytes,6,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	Actor           *Actor                   `protobuf:"bytes,7,opt,name=actor,proto3" json:"actor,omitempty"`
	AiModel         *AiModel                 `protobuf:"bytes,8,opt,name=ai_model,json=aiModel,proto3" json:"ai_model,omitempty"`
	Api             *Api                     `protobuf:"bytes,9,opt,name=api,proto3" json:"api,omitempty"`
	Attacks         []*Attack                `protobuf:"bytes,10,rep,name=attacks,proto3" json:"attacks,omitempty"`
	Authorizations  []*Authorization         `protobuf:"bytes,11,rep,name=authorizations,proto3" json:"authorizations,omitempty"`
	CategoryName    string                   `protobuf:"bytes,12,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryUid     AuditEvent_CategoryUid   `protobuf:"varint,13,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1.AuditEvent_CategoryUid" json:"category_uid,omitempty"`
	ClassName       string                   `protobuf:"bytes,14,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ClassUid        AuditEvent_ClassUid      `protobuf:"varint,15,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1.AuditEvent_ClassUid" json:"class_uid,omitempty"`
	Cloud           *Cloud                   `protobuf:"bytes,16,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Comment         string                   `protobuf:"bytes,17,opt,name=comment,proto3" json:"comment,omitempty"`
	Confidence      string                   `protobuf:"bytes,18,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ConfidenceId    AuditEvent_ConfidenceId  `protobuf:"varint,19,opt,name=confidence_id,json=confidenceId,proto3,enum=ocsf.v1.AuditEvent_ConfidenceId" json:"confidence_id,omitempty"`
	ConfidenceScore int32                    `protobuf:"varint,20,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Count           int32                    `protobuf:"varint,21,opt,name=count,proto3" json:"count,omitempty"`
	Device          *Device                  `protobuf:"bytes,22,opt,name=device,proto3" json:"device,omitempty"`
	Disposition     string                   `protobuf:"bytes,23,opt,name=disposition,proto3" json:"disposition,omitempty"`
	DispositionId   AuditEvent_DispositionId `protobuf:"varint,24,opt,name=disposition_id,json=dispositionId,proto3,enum=ocsf.v1.AuditEvent_DispositionId" json:"disposition_id,omitempty"`
	DstEndpoint     *NetworkEndpoint         `protobuf:"bytes,25,opt,name=dst_endpoint,json=dstEndpoint,proto3" json:"dst_endpoint,omitempty"`
	Duration        int64                    `protobuf:"varint,26,opt,name=duration,proto3" json:"duration,omitempty"`
	EndTime         int64                    `protobuf:"varint,27,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	EndTimeDt       string                   `protobuf:"bytes,28,opt,name=end_time_dt,json=endTimeDt,proto3" json:"end_time_dt,omitempty"`
	Enrichments     []*Enrichment            `protobuf:"bytes,29,rep,name=enrichments,proto3" json:"enrichments,omitempty"`
	Entity          *ManagedEntity           `protobuf:"bytes,30,opt,name=entity,proto3" json:"entity,omitempty"`
	EntityResult    *ManagedEntity           `protobuf:"bytes,31,opt,name=entity_result,json=entityResult,proto3" json:"entity_result,omitempty"`
	FirewallRule    *FirewallRule            `protobuf:"bytes,32,opt,name=firewall_rule,json=firewallRule,proto3" json:"firewall_rule,omitempty"`
	HttpRequest     *HttpRequest             `protobuf:"bytes,33,opt,name=http_request,json=httpRequest,proto3" json:"http_request,omitempty"`
	HttpResponse    *HttpResponse            `protobuf:"bytes,34,opt,name=http_response,json=httpResponse,proto3" json:"http_response,omitempty"`
	IsAlert         bool                     `protobuf:"varint,35,opt,name=is_alert,json=isAlert,proto3" json:"is_alert,omitempty"`
	Malware         []*Malware               `protobuf:"bytes,36,rep,name=malware,proto3" json:"malware,omitempty"`
	MalwareScanInfo *MalwareScanInfo         `protobuf:"bytes,37,opt,name=malware_scan_info,json=malwareScanInfo,proto3" json:"malware_scan_info,omitempty"`
	Message         string                   `protobuf:"bytes,38,opt,name=message,proto3" json:"message,omitempty"`
	MessageContext  *MessageContext          `protobuf:"bytes,39,opt,name=message_context,json=messageContext,proto3" json:"message_context,omitempty"`
	Metadata        *Metadata                `protobuf:"bytes,40,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Observables     []*Observable            `protobuf:"bytes,41,rep,name=observables,proto3" json:"observables,omitempty"`
	Osint           []*Osint                 `protobuf:"bytes,42,rep,name=osint,proto3" json:"osint,omitempty"`
	Policy          *Policy                  `protobuf:"bytes,43,opt,name=policy,proto3" json:"policy,omitempty"`
	RawData         string                   `protobuf:"bytes,44,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	RawDataHash     *Fingerprint             `protobuf:"bytes,45,opt,name=raw_data_hash,json=rawDataHash,proto3" json:"raw_data_hash,omitempty"`
	RawDataSize     int64                    `protobuf:"varint,46,opt,name=raw_data_size,json=rawDataSize,proto3" json:"raw_data_size,omitempty"`
	Resources       []*ResourceDetails       `protobuf:"bytes,47,rep,name=resources,proto3" json:"resources,omitempty"`
	RiskDetails     string                   `protobuf:"bytes,48,opt,name=risk_details,json=riskDetails,proto3" json:"risk_details,omitempty"`
	RiskLevel       string                   `protobuf:"bytes,49,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RiskLevelId     AuditEvent_RiskLevelId   `protobuf:"varint,50,opt,name=risk_level_id,json=riskLevelId,proto3,enum=ocsf.v1.AuditEvent_RiskLevelId" json:"risk_level_id,omitempty"`
	RiskScore       int32                    `protobuf:"varint,51,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Severity        string                   `protobuf:"bytes,52,opt,name=severity,proto3" json:"severity,omitempty"`
	SeverityId      AuditEvent_SeverityId    `protobuf:"varint,53,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1.AuditEvent_SeverityId" json:"severity_id,omitempty"`
	SrcEndpoint     *NetworkEndpoint         `protobuf:"bytes,54,opt,name=src_endpoint,json=srcEndpoint,proto3" json:"src_endpoint,omitempty"`
	StartTime       int64                    `protobuf:"varint,55,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StartTimeDt     string                   `protobuf:"bytes,56,opt,name=start_time_dt,json=startTimeDt,proto3" json:"start_time_dt,omitempty"`
	Status          string                   `protobuf:"bytes,57,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode      string                   `protobuf:"bytes,58,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusDetail    string                   `protobuf:"bytes,59,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`
	StatusId        AuditEvent_StatusId      `protobuf:"varint,60,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1.AuditEvent_StatusId" json:"status_id,omitempty"`
	Time            int64                    `protobuf:"varint,61,opt,name=time,proto3" json:"time,omitempty"`
	TimeDt          string                   `protobuf:"bytes,62,opt,name=time_dt,json=timeDt,proto3" json:"time_dt,omitempty"`
	TimezoneOffset  int32                    `protobuf:"varint,63,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`
	Trace           *Trace                   `protobuf:"bytes,64,opt,name=trace,proto3" json:"trace,omitempty"`
	TypeName        string                   `protobuf:"bytes,65,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	TypeUid         AuditEvent_TypeUid       `protobuf:"varint,66,opt,name=type_uid,json=typeUid,proto3,enum=ocsf.v1.AuditEvent_TypeUid" json:"type_uid,omitempty"`
	Unmapped        *structpb.Value          `protobuf:"bytes,67,opt,name=unmapped,proto3" json:"unmapped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditEvent) Reset() {
	*x = AuditEvent{}
	mi := &file_ocsf_v1_audit_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEvent) ProtoMessage() {}

func (x *AuditEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_audit_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEvent.ProtoReflect.Descriptor instead.
func (*AuditEvent) Descriptor() ([]byte, []int) {
	return file_ocsf_v1_audit_event_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEvent) GetAccessList() []string {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *AuditEvent) GetAccessMask() int32 {
	if x != nil {
		return x.AccessMask
	}
	return 0
}

func (x *AuditEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEvent) GetActionId() AuditEvent_ActionId {
	if x != nil {
		return x.ActionId
	}
	return AuditEvent_ACTION_ID_UNKNOWN
}

func (x *AuditEvent) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *AuditEvent) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *AuditEvent) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AuditEvent) GetAiModel() *AiModel {
	if x != nil {
		return x.AiModel
	}
	return nil
}

func (x *AuditEvent) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *AuditEvent) GetAttacks() []*Attack {
	if x != nil {
		return x.Attacks
	}
	return nil
}

func (x *AuditEvent) GetAuthorizations() []*Authorization {
	if x != nil {
		return x.Authorizations
	}
	return nil
}

func (x *AuditEvent) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *AuditEvent) GetCategoryUid() AuditEvent_CategoryUid {
	if x != nil {
		return x.CategoryUid
	}
	return AuditEvent_CATEGORY_UID_UNKNOWN
}

func (x *AuditEvent) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *AuditEvent) GetClassUid() AuditEvent_ClassUid {
	if x != nil {
		return x.ClassUid
	}
	return AuditEvent_CLASS_UID_UNKNOWN
}

func (x *AuditEvent) GetCloud() *Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *AuditEvent) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *AuditEvent) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *AuditEvent) GetConfidenceId() AuditEvent_ConfidenceId {
	if x != nil {
		return x.ConfidenceId
	}
	return AuditEvent_CONFIDENCE_ID_UNKNOWN
}

func (x *AuditEvent) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *AuditEvent) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AuditEvent) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *AuditEvent) GetDisposition() string {
	if x != nil {
		return x.Disposition
	}
	return ""
}

func (x *AuditEvent) GetDispositionId() AuditEvent_DispositionId {
	if x != nil {
		return x.DispositionId
	}
	return AuditEvent_DISPOSITION_ID_UNKNOWN
}

func (x *AuditEvent) GetDstEndpoint() *NetworkEndpoint {
	if x != nil {
		return x.DstEndpoint
	}
	return nil
}

func (x *AuditEvent) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AuditEvent) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *AuditEvent) GetEndTimeDt() string {
	if x != nil {
		return x.EndTimeDt
	}
	return ""
}

func (x *AuditEvent) GetEnrichments() []*Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *AuditEvent) GetEntity() *ManagedEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *AuditEvent) GetEntityResult() *ManagedEntity {
	if x != nil {
		return x.EntityResult
	}
	return nil
}

func (x *AuditEvent) GetFirewallRule() *FirewallRule {
	if x != nil {
		return x.FirewallRule
	}
	return nil
}

func (x *AuditEvent) GetHttpRequest() *HttpRequest {
	if x != nil {
		return x.HttpRequest
	}
	return nil
}

func (x *AuditEvent) GetHttpResponse() *HttpResponse {
	if x != nil {
		return x.HttpResponse
	}
	return nil
}

func (x *AuditEvent) GetIsAlert() bool {
	if x != nil {
		return x.IsAlert
	}
	return false
}

func (x *AuditEvent) GetMalware() []*Malware {
	if x != nil {
		return x.Malware
	}
	return nil
}

func (x *AuditEvent) GetMalwareScanInfo() *MalwareScanInfo {
	if x != nil {
		return x.MalwareScanInfo
	}
	return nil
}

func (x *AuditEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AuditEvent) GetMessageContext() *MessageContext {
	if x != nil {
		return x.MessageContext
	}
	return nil
}

func (x *AuditEvent) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *AuditEvent) GetObservables() []*Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *AuditEvent) GetOsint() []*Osint {
	if x != nil {
		return x.Osint
	}
	return nil
}

func (x *AuditEvent) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *AuditEvent) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *AuditEvent) GetRawDataHash() *Fingerprint {
	if x != nil {
		return x.RawDataHash
	}
	return nil
}

func (x *AuditEvent) GetRawDataSize() int64 {
	if x != nil {
		return x.RawDataSize
	}
	return 0
}

func (x *AuditEvent) GetResources() []*ResourceDetails {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *AuditEvent) GetRiskDetails() string {
	if x != nil {
		return x.RiskDetails
	}
	return ""
}

func (x *AuditEvent) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *AuditEvent) GetRiskLevelId() AuditEvent_RiskLevelId {
	if x != nil {
		return x.RiskLevelId
	}
	return AuditEvent_RISK_LEVEL_ID_INFO
}

func (x *AuditEvent) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *AuditEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AuditEvent) GetSeverityId() AuditEvent_SeverityId {
	if x != nil {
		return x.SeverityId
	}
	return AuditEvent_SEVERITY_ID_UNKNOWN
}

func (x *AuditEvent) GetSrcEndpoint() *NetworkEndpoint {
	if x != nil {
		return x.SrcEndpoint
	}
	return nil
}

func (x *AuditEvent) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AuditEvent) GetStartTimeDt() string {
	if x != nil {
		return x.StartTimeDt
	}
	return ""
}

func (x *AuditEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AuditEvent) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *AuditEvent) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *AuditEvent) GetStatusId() AuditEvent_StatusId {
	if x != nil {
		return x.StatusId
	}
	return AuditEvent_STATUS_ID_UNKNOWN
}

func (x *AuditEvent) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *AuditEvent) GetTimeDt() string {
	if x != nil {
		return x.TimeDt
	}
	return ""
}

func (x *AuditEvent) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *AuditEvent) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *AuditEvent) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *AuditEvent) GetTypeUid() AuditEvent_TypeUid {
	if x != nil {
		return x.TypeUid
	}
	return AuditEvent_TYPE_UID_UNKNOWN
}

func (x *AuditEvent) GetUnmapped() *structpb.Value {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

var File_ocsf_v1_audit_event_proto protoreflect.FileDescriptor

const file_ocsf_v1_audit_event_proto_rawDesc = "" +
	"\n" +
	"\x19ocsf/v1/audit_event.proto\x12\aocsf.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15ocsf/v1/objects.proto\x1a,redpanda/api/common/v1/schema_registry.proto\"\x87<\n" +
	"\n" +
	"AuditEvent\x12\x1f\n" +
	"\vaccess_list\x18\x01 \x03(\tR\n" +
	"accessList\x12\x1f\n" +
	"\vaccess_mask\x18\x02 \x01(\x05R\n" +
	"accessMask\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x129\n" +
	"\taction_id\x18\x04 \x01(\x0e2\x1c.ocsf.v1.AuditEvent.ActionIdR\bactionId\x12'\n" +
	"\vactivity_id\x18\x05 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x06 \x01(\tR\factivityName\x12$\n" +
	"\x05actor\x18\a \x01(\v2\x0e.ocsf.v1.ActorR\x05actor\x12+\n" +
	"\bai_model\x18\b \x01(\v2\x10.ocsf.v1.AiModelR\aaiModel\x12\x1e\n" +
	"\x03api\x18\t \x01(\v2\f.ocsf.v1.ApiR\x03api\x12)\n" +
	"\aattacks\x18\n" +
	" \x03(\v2\x0f.ocsf.v1.AttackR\aattacks\x12>\n" +
	"\x0eauthorizations\x18\v \x03(\v2\x16.ocsf.v1.AuthorizationR\x0eauthorizations\x12#\n" +
	"\rcategory_name\x18\f \x01(\tR\fcategoryName\x12J\n" +
	"\fcategory_uid\x18\r \x01(\x0e2\x1f.ocsf.v1.AuditEvent.CategoryUidB\x06\xbaH\x03\xc8\x01\x01R\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\x0e \x01(\tR\tclassName\x12A\n" +
	"\tclass_uid\x18\x0f \x01(\x0e2\x1c.ocsf.v1.AuditEvent.ClassUidB\x06\xbaH\x03\xc8\x01\x01R\bclassUid\x12,\n" +
	"\x05cloud\x18\x10 \x01(\v2\x0e.ocsf.v1.CloudB\x06\xbaH\x03\xc8\x01\x01R\x05cloud\x12\x18\n" +
	"\acomment\x18\x11 \x01(\tR\acomment\x12\x1e\n" +
	"\n" +
	"confidence\x18\x12 \x01(\tR\n" +
	"confidence\x12E\n" +
	"\rconfidence_id\x18\x13 \x01(\x0e2 .ocsf.v1.AuditEvent.ConfidenceIdR\fconfidenceId\x12)\n" +
	"\x10confidence_score\x18\x14 \x01(\x05R\x0fconfidenceScore\x12\x14\n" +
	"\x05count\x18\x15 \x01(\x05R\x05count\x12'\n" +
	"\x06device\x18\x16 \x01(\v2\x0f.ocsf.v1.DeviceR\x06device\x12 \n" +
	"\vdisposition\x18\x17 \x01(\tR\vdisposition\x12H\n" +
	"\x0edisposition_id\x18\x18 \x01(\x0e2!.ocsf.v1.AuditEvent.DispositionIdR\rdispositionId\x12;\n" +
	"\fdst_endpoint\x18\x19 \x01(\v2\x18.ocsf.v1.NetworkEndpointR\vdstEndpoint\x12\x1a\n" +
	"\bduration\x18\x1a \x01(\x03R\bduration\x12\x19\n" +
	"\bend_time\x18\x1b \x01(\x03R\aendTime\x12\x1e\n" +
	"\vend_time_dt\x18\x1c \x01(\tR\tendTimeDt\x125\n" +
	"\venrichments\x18\x1d \x03(\v2\x13.ocsf.v1.EnrichmentR\venrichments\x12.\n" +
	"\x06entity\x18\x1e \x01(\v2\x16.ocsf.v1.ManagedEntityR\x06entity\x12;\n" +
	"\rentity_result\x18\x1f \x01(\v2\x16.ocsf.v1.ManagedEntityR\fentityResult\x12:\n" +
	"\rfirewall_rule\x18  \x01(\v2\x15.ocsf.v1.FirewallRuleR\ffirewallRule\x127\n" +
	"\fhttp_request\x18! \x01(\v2\x14.ocsf.v1.HttpRequestR\vhttpRequest\x12:\n" +
	"\rhttp_response\x18\" \x01(\v2\x15.ocsf.v1.HttpResponseR\fhttpResponse\x12\x19\n" +
	"\bis_alert\x18# \x01(\bR\aisAlert\x12*\n" +
	"\amalware\x18$ \x03(\v2\x10.ocsf.v1.MalwareR\amalware\x12D\n" +
	"\x11malware_scan_info\x18% \x01(\v2\x18.ocsf.v1.MalwareScanInfoR\x0fmalwareScanInfo\x12\x18\n" +
	"\amessage\x18& \x01(\tR\amessage\x12@\n" +
	"\x0fmessage_context\x18' \x01(\v2\x17.ocsf.v1.MessageContextR\x0emessageContext\x125\n" +
	"\bmetadata\x18( \x01(\v2\x11.ocsf.v1.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x125\n" +
	"\vobservables\x18) \x03(\v2\x13.ocsf.v1.ObservableR\vobservables\x12$\n" +
	"\x05osint\x18* \x03(\v2\x0e.ocsf.v1.OsintR\x05osint\x12'\n" +
	"\x06policy\x18+ \x01(\v2\x0f.ocsf.v1.PolicyR\x06policy\x12\x19\n" +
	"\braw_data\x18, \x01(\tR\arawData\x128\n" +
	"\rraw_data_hash\x18- \x01(\v2\x14.ocsf.v1.FingerprintR\vrawDataHash\x12\"\n" +
	"\rraw_data_size\x18. \x01(\x03R\vrawDataSize\x126\n" +
	"\tresources\x18/ \x03(\v2\x18.ocsf.v1.ResourceDetailsR\tresources\x12!\n" +
	"\frisk_details\x180 \x01(\tR\vriskDetails\x12\x1d\n" +
	"\n" +
	"risk_level\x181 \x01(\tR\triskLevel\x12C\n" +
	"\rrisk_level_id\x182 \x01(\x0e2\x1f.ocsf.v1.AuditEvent.RiskLevelIdR\vriskLevelId\x12\x1d\n" +
	"\n" +
	"risk_score\x183 \x01(\x05R\triskScore\x12\x1a\n" +
	"\bseverity\x184 \x01(\tR\bseverity\x12G\n" +
	"\vseverity_id\x185 \x01(\x0e2\x1e.ocsf.v1.AuditEvent.SeverityIdB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"severityId\x12;\n" +
	"\fsrc_endpoint\x186 \x01(\v2\x18.ocsf.v1.NetworkEndpointR\vsrcEndpoint\x12\x1d\n" +
	"\n" +
	"start_time\x187 \x01(\x03R\tstartTime\x12\"\n" +
	"\rstart_time_dt\x188 \x01(\tR\vstartTimeDt\x12\x16\n" +
	"\x06status\x189 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x18: \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x18; \x01(\tR\fstatusDetail\x129\n" +
	"\tstatus_id\x18< \x01(\x0e2\x1c.ocsf.v1.AuditEvent.StatusIdR\bstatusId\x12\x1a\n" +
	"\x04time\x18= \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x04time\x12\x17\n" +
	"\atime_dt\x18> \x01(\tR\x06timeDt\x12'\n" +
	"\x0ftimezone_offset\x18? \x01(\x05R\x0etimezoneOffset\x12$\n" +
	"\x05trace\x18@ \x01(\v2\x0e.ocsf.v1.TraceR\x05trace\x12\x1b\n" +
	"\ttype_name\x18A \x01(\tR\btypeName\x12>\n" +
	"\btype_uid\x18B \x01(\x0e2\x1b.ocsf.v1.AuditEvent.TypeUidB\x06\xbaH\x03\xc8\x01\x01R\atypeUid\x122\n" +
	"\bunmapped\x18C \x01(\v2\x16.google.protobuf.ValueR\bunmapped\"\x93\x01\n" +
	"\bActionId\x12\x15\n" +
	"\x11ACTION_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11ACTION_ID_ALLOWED\x10\x01\x12\x14\n" +
	"\x10ACTION_ID_DENIED\x10\x02\x12\x16\n" +
	"\x12ACTION_ID_OBSERVED\x10\x03\x12\x16\n" +
	"\x12ACTION_ID_MODIFIED\x10\x04\x12\x13\n" +
	"\x0fACTION_ID_OTHER\x10c\"{\n" +
	"\vCategoryUid\x12\x18\n" +
	"\x14CATEGORY_UID_UNKNOWN\x10\x00\x12+\n" +
	"'CATEGORY_UID_IDENTITY_ACCESS_MANAGEMENT\x10\x03\x12%\n" +
	"!CATEGORY_UID_APPLICATION_ACTIVITY\x10\x06\"`\n" +
	"\bClassUid\x12\x15\n" +
	"\x11CLASS_UID_UNKNOWN\x10\x00\x12 \n" +
	"\x1bCLASS_UID_ENTITY_MANAGEMENT\x10\xbc\x17\x12\x1b\n" +
	"\x16CLASS_UID_API_ACTIVITY\x10\xf3.\"\x8b\x01\n" +
	"\fConfidenceId\x12\x19\n" +
	"\x15CONFIDENCE_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CONFIDENCE_ID_LOW\x10\x01\x12\x18\n" +
	"\x14CONFIDENCE_ID_MEDIUM\x10\x02\x12\x16\n" +
	"\x12CONFIDENCE_ID_HIGH\x10\x03\x12\x17\n" +
	"\x13CONFIDENCE_ID_OTHER\x10c\"\xe3\x06\n" +
	"\rDispositionId\x12\x1a\n" +
	"\x16DISPOSITION_ID_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16DISPOSITION_ID_ALLOWED\x10\x01\x12\x1a\n" +
	"\x16DISPOSITION_ID_BLOCKED\x10\x02\x12\x1e\n" +
	"\x1aDISPOSITION_ID_QUARANTINED\x10\x03\x12\x1b\n" +
	"\x17DISPOSITION_ID_ISOLATED\x10\x04\x12\x1a\n" +
	"\x16DISPOSITION_ID_DELETED\x10\x05\x12\x1a\n" +
	"\x16DISPOSITION_ID_DROPPED\x10\x06\x12 \n" +
	"\x1cDISPOSITION_ID_CUSTOM_ACTION\x10\a\x12\x1b\n" +
	"\x17DISPOSITION_ID_APPROVED\x10\b\x12\x1b\n" +
	"\x17DISPOSITION_ID_RESTORED\x10\t\x12\x1d\n" +
	"\x19DISPOSITION_ID_EXONERATED\x10\n" +
	"\x12\x1c\n" +
	"\x18DISPOSITION_ID_CORRECTED\x10\v\x12&\n" +
	"\"DISPOSITION_ID_PARTIALLY_CORRECTED\x10\f\x12\x1e\n" +
	"\x1aDISPOSITION_ID_UNCORRECTED\x10\r\x12\x1a\n" +
	"\x16DISPOSITION_ID_DELAYED\x10\x0e\x12\x1b\n" +
	"\x17DISPOSITION_ID_DETECTED\x10\x0f\x12\x1c\n" +
	"\x18DISPOSITION_ID_NO_ACTION\x10\x10\x12\x19\n" +
	"\x15DISPOSITION_ID_LOGGED\x10\x11\x12\x19\n" +
	"\x15DISPOSITION_ID_TAGGED\x10\x12\x12\x18\n" +
	"\x14DISPOSITION_ID_ALERT\x10\x13\x12\x18\n" +
	"\x14DISPOSITION_ID_COUNT\x10\x14\x12\x18\n" +
	"\x14DISPOSITION_ID_RESET\x10\x15\x12\x1a\n" +
	"\x16DISPOSITION_ID_CAPTCHA\x10\x16\x12\x1c\n" +
	"\x18DISPOSITION_ID_CHALLENGE\x10\x17\x12!\n" +
	"\x1dDISPOSITION_ID_ACCESS_REVOKED\x10\x18\x12\x1b\n" +
	"\x17DISPOSITION_ID_REJECTED\x10\x19\x12\x1f\n" +
	"\x1bDISPOSITION_ID_UNAUTHORIZED\x10\x1a\x12\x18\n" +
	"\x14DISPOSITION_ID_ERROR\x10\x1b\x12\x18\n" +
	"\x14DISPOSITION_ID_OTHER\x10c\"\xa3\x01\n" +
	"\vRiskLevelId\x12\x16\n" +
	"\x12RISK_LEVEL_ID_INFO\x10\x00\x12\x15\n" +
	"\x11RISK_LEVEL_ID_LOW\x10\x01\x12\x18\n" +
	"\x14RISK_LEVEL_ID_MEDIUM\x10\x02\x12\x16\n" +
	"\x12RISK_LEVEL_ID_HIGH\x10\x03\x12\x1a\n" +
	"\x16RISK_LEVEL_ID_CRITICAL\x10\x04\x12\x17\n" +
	"\x13RISK_LEVEL_ID_OTHER\x10c\"\xcf\x01\n" +
	"\n" +
	"SeverityId\x12\x17\n" +
	"\x13SEVERITY_ID_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19SEVERITY_ID_INFORMATIONAL\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_ID_LOW\x10\x02\x12\x16\n" +
	"\x12SEVERITY_ID_MEDIUM\x10\x03\x12\x14\n" +
	"\x10SEVERITY_ID_HIGH\x10\x04\x12\x18\n" +
	"\x14SEVERITY_ID_CRITICAL\x10\x05\x12\x15\n" +
	"\x11SEVERITY_ID_FATAL\x10\x06\x12\x15\n" +
	"\x11SEVERITY_ID_OTHER\x10c\"d\n" +
	"\bStatusId\x12\x15\n" +
	"\x11STATUS_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11STATUS_ID_SUCCESS\x10\x01\x12\x15\n" +
	"\x11STATUS_ID_FAILURE\x10\x02\x12\x13\n" +
	"\x0fSTATUS_ID_OTHER\x10c\"\xe2\x06\n" +
	"\aTypeUid\x12\x14\n" +
	"\x10TYPE_UID_UNKNOWN\x10\x00\x12(\n" +
	"\"TYPE_UID_ENTITY_MANAGEMENT_UNKNOWN\x10\xf0\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_CREATE\x10\xf1\xaa\x12\x12%\n" +
	"\x1fTYPE_UID_ENTITY_MANAGEMENT_READ\x10\xf2\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_UPDATE\x10\xf3\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_DELETE\x10\xf4\xaa\x12\x12%\n" +
	"\x1fTYPE_UID_ENTITY_MANAGEMENT_MOVE\x10\xf5\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_ENROLL\x10\xf6\xaa\x12\x12)\n" +
	"#TYPE_UID_ENTITY_MANAGEMENT_UNENROLL\x10\xf7\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_ENABLE\x10\xf8\xaa\x12\x12(\n" +
	"\"TYPE_UID_ENTITY_MANAGEMENT_DISABLE\x10\xf9\xaa\x12\x12)\n" +
	"#TYPE_UID_ENTITY_MANAGEMENT_ACTIVATE\x10\xfa\xaa\x12\x12+\n" +
	"%TYPE_UID_ENTITY_MANAGEMENT_DEACTIVATE\x10\xfb\xaa\x12\x12(\n" +
	"\"TYPE_UID_ENTITY_MANAGEMENT_SUSPEND\x10\xfc\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_RESUME\x10\xfd\xaa\x12\x12&\n" +
	" TYPE_UID_ENTITY_MANAGEMENT_OTHER\x10ӫ\x12\x12#\n" +
	"\x1dTYPE_UID_API_ACTIVITY_UNKNOWN\x10\xec\xd1$\x12\"\n" +
	"\x1cTYPE_UID_API_ACTIVITY_CREATE\x10\xed\xd1$\x12 \n" +
	"\x1aTYPE_UID_API_ACTIVITY_READ\x10\xee\xd1$\x12\"\n" +
	"\x1cTYPE_UID_API_ACTIVITY_UPDATE\x10\xef\xd1$\x12\"\n" +
	"\x1cTYPE_UID_API_ACTIVITY_DELETE\x10\xf0\xd1$\x12!\n" +
	"\x1bTYPE_UID_API_ACTIVITY_OTHER\x10\xcf\xd2$:\xba\x0f\xbaH\x90\x0f\x1a\x82\x01\n" +
	"\x13AuditEvent.type_uid\x121type_uid must equal class_uid * 100 + activity_id\x1a8this.type_uid == this.class_uid * 100 + this.activity_id\x1a|\n" +
	"\x1aAuditEvent.own.access_list\x12,access_list is only valid for class_uid 3004\x1a0!has(this.access_list) || this.class_uid == 3004\x1a|\n" +
	"\x1aAuditEvent.own.access_mask\x12,access_mask is only valid for class_uid 3004\x1a0!has(this.access_mask) || this.class_uid == 3004\x1as\n" +
	"\x17AuditEvent.own.ai_model\x12)ai_model is only valid for class_uid 6003\x1a-!has(this.ai_model) || this.class_uid == 6003\x1ap\n" +
	"\x16AuditEvent.own.comment\x12(comment is only valid for class_uid 3004\x1a,!has(this.comment) || this.class_uid == 3004\x1a\x7f\n" +
	"\x1bAuditEvent.own.dst_endpoint\x12-dst_endpoint is only valid for class_uid 6003\x1a1!has(this.dst_endpoint) || this.class_uid == 6003\x1am\n" +
	"\x15AuditEvent.own.entity\x12'entity is only valid for class_uid 3004\x1a+!has(this.entity) || this.class_uid == 3004\x1a\x82\x01\n" +
	"\x1cAuditEvent.own.entity_result\x12.entity_result is only valid for class_uid 3004\x1a2!has(this.entity_result) || this.class_uid == 3004\x1a\x88\x01\n" +
	"\x1eAuditEvent.own.message_context\x120message_context is only valid for class_uid 6003\x1a4!has(this.message_context) || this.class_uid == 6003\x1av\n" +
	"\x18AuditEvent.own.resources\x12*resources is only valid for class_uid 6003\x1a.!has(this.resources) || this.class_uid == 6003\x1aj\n" +
	"\x14AuditEvent.own.trace\x12&trace is only valid for class_uid 6003\x1a*!has(this.trace) || this.class_uid == 6003\x1a\x87\x01\n" +
	"!AuditEvent.req.api_activity.actor\x127actor is required when class_uid == 6003 (api_activity)\x1a)this.class_uid != 6003 || has(this.actor)\x1a\x81\x01\n" +
	"\x1fAuditEvent.req.api_activity.api\x125api is required when class_uid == 6003 (api_activity)\x1a'this.class_uid != 6003 || has(this.api)\x1a\x9c\x01\n" +
	"(AuditEvent.req.api_activity.src_endpoint\x12>src_endpoint is required when class_uid == 6003 (api_activity)\x1a0this.class_uid != 6003 || has(this.src_endpoint)\x1a\x94\x01\n" +
	"'AuditEvent.req.entity_management.entity\x12=entity is required when class_uid == 3004 (entity_management)\x1a*this.class_uid != 3004 || has(this.entity)\x82\xc0\a\"\n" +
	" redpanda.ocsf.audit-events-valueb\x06proto3"

var (
	file_ocsf_v1_audit_event_proto_rawDescOnce sync.Once
	file_ocsf_v1_audit_event_proto_rawDescData []byte
)

func file_ocsf_v1_audit_event_proto_rawDescGZIP() []byte {
	file_ocsf_v1_audit_event_proto_rawDescOnce.Do(func() {
		file_ocsf_v1_audit_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocsf_v1_audit_event_proto_rawDesc), len(file_ocsf_v1_audit_event_proto_rawDesc)))
	})
	return file_ocsf_v1_audit_event_proto_rawDescData
}

var file_ocsf_v1_audit_event_proto_enumTypes = make([]protoimpl.EnumInfo, 9)
var file_ocsf_v1_audit_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ocsf_v1_audit_event_proto_goTypes = []any{
	(AuditEvent_ActionId)(0),      // 0: ocsf.v1.AuditEvent.ActionId
	(AuditEvent_CategoryUid)(0),   // 1: ocsf.v1.AuditEvent.CategoryUid
	(AuditEvent_ClassUid)(0),      // 2: ocsf.v1.AuditEvent.ClassUid
	(AuditEvent_ConfidenceId)(0),  // 3: ocsf.v1.AuditEvent.ConfidenceId
	(AuditEvent_DispositionId)(0), // 4: ocsf.v1.AuditEvent.DispositionId
	(AuditEvent_RiskLevelId)(0),   // 5: ocsf.v1.AuditEvent.RiskLevelId
	(AuditEvent_SeverityId)(0),    // 6: ocsf.v1.AuditEvent.SeverityId
	(AuditEvent_StatusId)(0),      // 7: ocsf.v1.AuditEvent.StatusId
	(AuditEvent_TypeUid)(0),       // 8: ocsf.v1.AuditEvent.TypeUid
	(*AuditEvent)(nil),            // 9: ocsf.v1.AuditEvent
	(*Actor)(nil),                 // 10: ocsf.v1.Actor
	(*AiModel)(nil),               // 11: ocsf.v1.AiModel
	(*Api)(nil),                   // 12: ocsf.v1.Api
	(*Attack)(nil),                // 13: ocsf.v1.Attack
	(*Authorization)(nil),         // 14: ocsf.v1.Authorization
	(*Cloud)(nil),                 // 15: ocsf.v1.Cloud
	(*Device)(nil),                // 16: ocsf.v1.Device
	(*NetworkEndpoint)(nil),       // 17: ocsf.v1.NetworkEndpoint
	(*Enrichment)(nil),            // 18: ocsf.v1.Enrichment
	(*ManagedEntity)(nil),         // 19: ocsf.v1.ManagedEntity
	(*FirewallRule)(nil),          // 20: ocsf.v1.FirewallRule
	(*HttpRequest)(nil),           // 21: ocsf.v1.HttpRequest
	(*HttpResponse)(nil),          // 22: ocsf.v1.HttpResponse
	(*Malware)(nil),               // 23: ocsf.v1.Malware
	(*MalwareScanInfo)(nil),       // 24: ocsf.v1.MalwareScanInfo
	(*MessageContext)(nil),        // 25: ocsf.v1.MessageContext
	(*Metadata)(nil),              // 26: ocsf.v1.Metadata
	(*Observable)(nil),            // 27: ocsf.v1.Observable
	(*Osint)(nil),                 // 28: ocsf.v1.Osint
	(*Policy)(nil),                // 29: ocsf.v1.Policy
	(*Fingerprint)(nil),           // 30: ocsf.v1.Fingerprint
	(*ResourceDetails)(nil),       // 31: ocsf.v1.ResourceDetails
	(*Trace)(nil),                 // 32: ocsf.v1.Trace
	(*structpb.Value)(nil),        // 33: google.protobuf.Value
}
var file_ocsf_v1_audit_event_proto_depIdxs = []int32{
	0,  // 0: ocsf.v1.AuditEvent.action_id:type_name -> ocsf.v1.AuditEvent.ActionId
	10, // 1: ocsf.v1.AuditEvent.actor:type_name -> ocsf.v1.Actor
	11, // 2: ocsf.v1.AuditEvent.ai_model:type_name -> ocsf.v1.AiModel
	12, // 3: ocsf.v1.AuditEvent.api:type_name -> ocsf.v1.Api
	13, // 4: ocsf.v1.AuditEvent.attacks:type_name -> ocsf.v1.Attack
	14, // 5: ocsf.v1.AuditEvent.authorizations:type_name -> ocsf.v1.Authorization
	1,  // 6: ocsf.v1.AuditEvent.category_uid:type_name -> ocsf.v1.AuditEvent.CategoryUid
	2,  // 7: ocsf.v1.AuditEvent.class_uid:type_name -> ocsf.v1.AuditEvent.ClassUid
	15, // 8: ocsf.v1.AuditEvent.cloud:type_name -> ocsf.v1.Cloud
	3,  // 9: ocsf.v1.AuditEvent.confidence_id:type_name -> ocsf.v1.AuditEvent.ConfidenceId
	16, // 10: ocsf.v1.AuditEvent.device:type_name -> ocsf.v1.Device
	4,  // 11: ocsf.v1.AuditEvent.disposition_id:type_name -> ocsf.v1.AuditEvent.DispositionId
	17, // 12: ocsf.v1.AuditEvent.dst_endpoint:type_name -> ocsf.v1.NetworkEndpoint
	18, // 13: ocsf.v1.AuditEvent.enrichments:type_name -> ocsf.v1.Enrichment
	19, // 14: ocsf.v1.AuditEvent.entity:type_name -> ocsf.v1.ManagedEntity
	19, // 15: ocsf.v1.AuditEvent.entity_result:type_name -> ocsf.v1.ManagedEntity
	20, // 16: ocsf.v1.AuditEvent.firewall_rule:type_name -> ocsf.v1.FirewallRule
	21, // 17: ocsf.v1.AuditEvent.http_request:type_name -> ocsf.v1.HttpRequest
	22, // 18: ocsf.v1.AuditEvent.http_response:type_name -> ocsf.v1.HttpResponse
	23, // 19: ocsf.v1.AuditEvent.malware:type_name -> ocsf.v1.Malware
	24, // 20: ocsf.v1.AuditEvent.malware_scan_info:type_name -> ocsf.v1.MalwareScanInfo
	25, // 21: ocsf.v1.AuditEvent.message_context:type_name -> ocsf.v1.MessageContext
	26, // 22: ocsf.v1.AuditEvent.metadata:type_name -> ocsf.v1.Metadata
	27, // 23: ocsf.v1.AuditEvent.observables:type_name -> ocsf.v1.Observable
	28, // 24: ocsf.v1.AuditEvent.osint:type_name -> ocsf.v1.Osint
	29, // 25: ocsf.v1.AuditEvent.policy:type_name -> ocsf.v1.Policy
	30, // 26: ocsf.v1.AuditEvent.raw_data_hash:type_name -> ocsf.v1.Fingerprint
	31, // 27: ocsf.v1.AuditEvent.resources:type_name -> ocsf.v1.ResourceDetails
	5,  // 28: ocsf.v1.AuditEvent.risk_level_id:type_name -> ocsf.v1.AuditEvent.RiskLevelId
	6,  // 29: ocsf.v1.AuditEvent.severity_id:type_name -> ocsf.v1.AuditEvent.SeverityId
	17, // 30: ocsf.v1.AuditEvent.src_endpoint:type_name -> ocsf.v1.NetworkEndpoint
	7,  // 31: ocsf.v1.AuditEvent.status_id:type_name -> ocsf.v1.AuditEvent.StatusId
	32, // 32: ocsf.v1.AuditEvent.trace:type_name -> ocsf.v1.Trace
	8,  // 33: ocsf.v1.AuditEvent.type_uid:type_name -> ocsf.v1.AuditEvent.TypeUid
	33, // 34: ocsf.v1.AuditEvent.unmapped:type_name -> google.protobuf.Value
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_ocsf_v1_audit_event_proto_init() }
func file_ocsf_v1_audit_event_proto_init() {
	if File_ocsf_v1_audit_event_proto != nil {
		return
	}
	file_ocsf_v1_objects_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_audit_event_proto_rawDesc), len(file_ocsf_v1_audit_event_proto_rawDesc)),
			NumEnums:      9,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_audit_event_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_audit_event_proto_depIdxs,
		EnumInfos:         file_ocsf_v1_audit_event_proto_enumTypes,
		MessageInfos:      file_ocsf_v1_audit_event_proto_msgTypes,
	}.Build()
	File_ocsf_v1_audit_event_proto = out.File
	file_ocsf_v1_audit_event_proto_goTypes = nil
	file_ocsf_v1_audit_event_proto_depIdxs = nil
}
