// Copyright 2026 Redpanda Data, Inc.
//
// Use of this software is governed by the Business Source License
// included in the file licenses/BSL.md
//
// As of the Change Date specified in that file, in accordance with
// the Business Source License, use of this software will be governed
// by the Apache License, Version 2.0

// Code generated by ocsf-protogen. DO NOT EDIT.
// Source: OCSF schema 1.8.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: ocsf/v1/entity_management.proto

package ocsfv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityManagement_ActionId int32

const (
	EntityManagement_ACTION_ID_UNKNOWN  EntityManagement_ActionId = 0
	EntityManagement_ACTION_ID_ALLOWED  EntityManagement_ActionId = 1
	EntityManagement_ACTION_ID_DENIED   EntityManagement_ActionId = 2
	EntityManagement_ACTION_ID_OBSERVED EntityManagement_ActionId = 3
	EntityManagement_ACTION_ID_MODIFIED EntityManagement_ActionId = 4
	EntityManagement_ACTION_ID_OTHER    EntityManagement_ActionId = 99
)

// Enum value maps for EntityManagement_ActionId.
var (
	EntityManagement_ActionId_name = map[int32]string{
		0:  "ACTION_ID_UNKNOWN",
		1:  "ACTION_ID_ALLOWED",
		2:  "ACTION_ID_DENIED",
		3:  "ACTION_ID_OBSERVED",
		4:  "ACTION_ID_MODIFIED",
		99: "ACTION_ID_OTHER",
	}
	EntityManagement_ActionId_value = map[string]int32{
		"ACTION_ID_UNKNOWN":  0,
		"ACTION_ID_ALLOWED":  1,
		"ACTION_ID_DENIED":   2,
		"ACTION_ID_OBSERVED": 3,
		"ACTION_ID_MODIFIED": 4,
		"ACTION_ID_OTHER":    99,
	}
)

func (x EntityManagement_ActionId) Enum() *EntityManagement_ActionId {
	p := new(EntityManagement_ActionId)
	*p = x
	return p
}

func (x EntityManagement_ActionId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_ActionId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[0].Descriptor()
}

func (EntityManagement_ActionId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[0]
}

func (x EntityManagement_ActionId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_ActionId.Descriptor instead.
func (EntityManagement_ActionId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 0}
}

type EntityManagement_ActivityId int32

const (
	EntityManagement_ACTIVITY_ID_UNKNOWN    EntityManagement_ActivityId = 0
	EntityManagement_ACTIVITY_ID_CREATE     EntityManagement_ActivityId = 1
	EntityManagement_ACTIVITY_ID_READ       EntityManagement_ActivityId = 2
	EntityManagement_ACTIVITY_ID_UPDATE     EntityManagement_ActivityId = 3
	EntityManagement_ACTIVITY_ID_DELETE     EntityManagement_ActivityId = 4
	EntityManagement_ACTIVITY_ID_MOVE       EntityManagement_ActivityId = 5
	EntityManagement_ACTIVITY_ID_ENROLL     EntityManagement_ActivityId = 6
	EntityManagement_ACTIVITY_ID_UNENROLL   EntityManagement_ActivityId = 7
	EntityManagement_ACTIVITY_ID_ENABLE     EntityManagement_ActivityId = 8
	EntityManagement_ACTIVITY_ID_DISABLE    EntityManagement_ActivityId = 9
	EntityManagement_ACTIVITY_ID_ACTIVATE   EntityManagement_ActivityId = 10
	EntityManagement_ACTIVITY_ID_DEACTIVATE EntityManagement_ActivityId = 11
	EntityManagement_ACTIVITY_ID_SUSPEND    EntityManagement_ActivityId = 12
	EntityManagement_ACTIVITY_ID_RESUME     EntityManagement_ActivityId = 13
	EntityManagement_ACTIVITY_ID_OTHER      EntityManagement_ActivityId = 99
)

// Enum value maps for EntityManagement_ActivityId.
var (
	EntityManagement_ActivityId_name = map[int32]string{
		0:  "ACTIVITY_ID_UNKNOWN",
		1:  "ACTIVITY_ID_CREATE",
		2:  "ACTIVITY_ID_READ",
		3:  "ACTIVITY_ID_UPDATE",
		4:  "ACTIVITY_ID_DELETE",
		5:  "ACTIVITY_ID_MOVE",
		6:  "ACTIVITY_ID_ENROLL",
		7:  "ACTIVITY_ID_UNENROLL",
		8:  "ACTIVITY_ID_ENABLE",
		9:  "ACTIVITY_ID_DISABLE",
		10: "ACTIVITY_ID_ACTIVATE",
		11: "ACTIVITY_ID_DEACTIVATE",
		12: "ACTIVITY_ID_SUSPEND",
		13: "ACTIVITY_ID_RESUME",
		99: "ACTIVITY_ID_OTHER",
	}
	EntityManagement_ActivityId_value = map[string]int32{
		"ACTIVITY_ID_UNKNOWN":    0,
		"ACTIVITY_ID_CREATE":     1,
		"ACTIVITY_ID_READ":       2,
		"ACTIVITY_ID_UPDATE":     3,
		"ACTIVITY_ID_DELETE":     4,
		"ACTIVITY_ID_MOVE":       5,
		"ACTIVITY_ID_ENROLL":     6,
		"ACTIVITY_ID_UNENROLL":   7,
		"ACTIVITY_ID_ENABLE":     8,
		"ACTIVITY_ID_DISABLE":    9,
		"ACTIVITY_ID_ACTIVATE":   10,
		"ACTIVITY_ID_DEACTIVATE": 11,
		"ACTIVITY_ID_SUSPEND":    12,
		"ACTIVITY_ID_RESUME":     13,
		"ACTIVITY_ID_OTHER":      99,
	}
)

func (x EntityManagement_ActivityId) Enum() *EntityManagement_ActivityId {
	p := new(EntityManagement_ActivityId)
	*p = x
	return p
}

func (x EntityManagement_ActivityId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_ActivityId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[1].Descriptor()
}

func (EntityManagement_ActivityId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[1]
}

func (x EntityManagement_ActivityId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_ActivityId.Descriptor instead.
func (EntityManagement_ActivityId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 1}
}

type EntityManagement_CategoryUid int32

const (
	EntityManagement_CATEGORY_UID_UNKNOWN                    EntityManagement_CategoryUid = 0
	EntityManagement_CATEGORY_UID_IDENTITY_ACCESS_MANAGEMENT EntityManagement_CategoryUid = 3
)

// Enum value maps for EntityManagement_CategoryUid.
var (
	EntityManagement_CategoryUid_name = map[int32]string{
		0: "CATEGORY_UID_UNKNOWN",
		3: "CATEGORY_UID_IDENTITY_ACCESS_MANAGEMENT",
	}
	EntityManagement_CategoryUid_value = map[string]int32{
		"CATEGORY_UID_UNKNOWN":                    0,
		"CATEGORY_UID_IDENTITY_ACCESS_MANAGEMENT": 3,
	}
)

func (x EntityManagement_CategoryUid) Enum() *EntityManagement_CategoryUid {
	p := new(EntityManagement_CategoryUid)
	*p = x
	return p
}

func (x EntityManagement_CategoryUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_CategoryUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[2].Descriptor()
}

func (EntityManagement_CategoryUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[2]
}

func (x EntityManagement_CategoryUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_CategoryUid.Descriptor instead.
func (EntityManagement_CategoryUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 2}
}

type EntityManagement_ClassUid int32

const (
	EntityManagement_CLASS_UID_UNKNOWN           EntityManagement_ClassUid = 0
	EntityManagement_CLASS_UID_ENTITY_MANAGEMENT EntityManagement_ClassUid = 3004
)

// Enum value maps for EntityManagement_ClassUid.
var (
	EntityManagement_ClassUid_name = map[int32]string{
		0:    "CLASS_UID_UNKNOWN",
		3004: "CLASS_UID_ENTITY_MANAGEMENT",
	}
	EntityManagement_ClassUid_value = map[string]int32{
		"CLASS_UID_UNKNOWN":           0,
		"CLASS_UID_ENTITY_MANAGEMENT": 3004,
	}
)

func (x EntityManagement_ClassUid) Enum() *EntityManagement_ClassUid {
	p := new(EntityManagement_ClassUid)
	*p = x
	return p
}

func (x EntityManagement_ClassUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_ClassUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[3].Descriptor()
}

func (EntityManagement_ClassUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[3]
}

func (x EntityManagement_ClassUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_ClassUid.Descriptor instead.
func (EntityManagement_ClassUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 3}
}

type EntityManagement_ConfidenceId int32

const (
	EntityManagement_CONFIDENCE_ID_UNKNOWN EntityManagement_ConfidenceId = 0
	EntityManagement_CONFIDENCE_ID_LOW     EntityManagement_ConfidenceId = 1
	EntityManagement_CONFIDENCE_ID_MEDIUM  EntityManagement_ConfidenceId = 2
	EntityManagement_CONFIDENCE_ID_HIGH    EntityManagement_ConfidenceId = 3
	EntityManagement_CONFIDENCE_ID_OTHER   EntityManagement_ConfidenceId = 99
)

// Enum value maps for EntityManagement_ConfidenceId.
var (
	EntityManagement_ConfidenceId_name = map[int32]string{
		0:  "CONFIDENCE_ID_UNKNOWN",
		1:  "CONFIDENCE_ID_LOW",
		2:  "CONFIDENCE_ID_MEDIUM",
		3:  "CONFIDENCE_ID_HIGH",
		99: "CONFIDENCE_ID_OTHER",
	}
	EntityManagement_ConfidenceId_value = map[string]int32{
		"CONFIDENCE_ID_UNKNOWN": 0,
		"CONFIDENCE_ID_LOW":     1,
		"CONFIDENCE_ID_MEDIUM":  2,
		"CONFIDENCE_ID_HIGH":    3,
		"CONFIDENCE_ID_OTHER":   99,
	}
)

func (x EntityManagement_ConfidenceId) Enum() *EntityManagement_ConfidenceId {
	p := new(EntityManagement_ConfidenceId)
	*p = x
	return p
}

func (x EntityManagement_ConfidenceId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_ConfidenceId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[4].Descriptor()
}

func (EntityManagement_ConfidenceId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[4]
}

func (x EntityManagement_ConfidenceId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_ConfidenceId.Descriptor instead.
func (EntityManagement_ConfidenceId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 4}
}

type EntityManagement_DispositionId int32

const (
	EntityManagement_DISPOSITION_ID_UNKNOWN             EntityManagement_DispositionId = 0
	EntityManagement_DISPOSITION_ID_ALLOWED             EntityManagement_DispositionId = 1
	EntityManagement_DISPOSITION_ID_BLOCKED             EntityManagement_DispositionId = 2
	EntityManagement_DISPOSITION_ID_QUARANTINED         EntityManagement_DispositionId = 3
	EntityManagement_DISPOSITION_ID_ISOLATED            EntityManagement_DispositionId = 4
	EntityManagement_DISPOSITION_ID_DELETED             EntityManagement_DispositionId = 5
	EntityManagement_DISPOSITION_ID_DROPPED             EntityManagement_DispositionId = 6
	EntityManagement_DISPOSITION_ID_CUSTOM_ACTION       EntityManagement_DispositionId = 7
	EntityManagement_DISPOSITION_ID_APPROVED            EntityManagement_DispositionId = 8
	EntityManagement_DISPOSITION_ID_RESTORED            EntityManagement_DispositionId = 9
	EntityManagement_DISPOSITION_ID_EXONERATED          EntityManagement_DispositionId = 10
	EntityManagement_DISPOSITION_ID_CORRECTED           EntityManagement_DispositionId = 11
	EntityManagement_DISPOSITION_ID_PARTIALLY_CORRECTED EntityManagement_DispositionId = 12
	EntityManagement_DISPOSITION_ID_UNCORRECTED         EntityManagement_DispositionId = 13
	EntityManagement_DISPOSITION_ID_DELAYED             EntityManagement_DispositionId = 14
	EntityManagement_DISPOSITION_ID_DETECTED            EntityManagement_DispositionId = 15
	EntityManagement_DISPOSITION_ID_NO_ACTION           EntityManagement_DispositionId = 16
	EntityManagement_DISPOSITION_ID_LOGGED              EntityManagement_DispositionId = 17
	EntityManagement_DISPOSITION_ID_TAGGED              EntityManagement_DispositionId = 18
	EntityManagement_DISPOSITION_ID_ALERT               EntityManagement_DispositionId = 19
	EntityManagement_DISPOSITION_ID_COUNT               EntityManagement_DispositionId = 20
	EntityManagement_DISPOSITION_ID_RESET               EntityManagement_DispositionId = 21
	EntityManagement_DISPOSITION_ID_CAPTCHA             EntityManagement_DispositionId = 22
	EntityManagement_DISPOSITION_ID_CHALLENGE           EntityManagement_DispositionId = 23
	EntityManagement_DISPOSITION_ID_ACCESS_REVOKED      EntityManagement_DispositionId = 24
	EntityManagement_DISPOSITION_ID_REJECTED            EntityManagement_DispositionId = 25
	EntityManagement_DISPOSITION_ID_UNAUTHORIZED        EntityManagement_DispositionId = 26
	EntityManagement_DISPOSITION_ID_ERROR               EntityManagement_DispositionId = 27
	EntityManagement_DISPOSITION_ID_OTHER               EntityManagement_DispositionId = 99
)

// Enum value maps for EntityManagement_DispositionId.
var (
	EntityManagement_DispositionId_name = map[int32]string{
		0:  "DISPOSITION_ID_UNKNOWN",
		1:  "DISPOSITION_ID_ALLOWED",
		2:  "DISPOSITION_ID_BLOCKED",
		3:  "DISPOSITION_ID_QUARANTINED",
		4:  "DISPOSITION_ID_ISOLATED",
		5:  "DISPOSITION_ID_DELETED",
		6:  "DISPOSITION_ID_DROPPED",
		7:  "DISPOSITION_ID_CUSTOM_ACTION",
		8:  "DISPOSITION_ID_APPROVED",
		9:  "DISPOSITION_ID_RESTORED",
		10: "DISPOSITION_ID_EXONERATED",
		11: "DISPOSITION_ID_CORRECTED",
		12: "DISPOSITION_ID_PARTIALLY_CORRECTED",
		13: "DISPOSITION_ID_UNCORRECTED",
		14: "DISPOSITION_ID_DELAYED",
		15: "DISPOSITION_ID_DETECTED",
		16: "DISPOSITION_ID_NO_ACTION",
		17: "DISPOSITION_ID_LOGGED",
		18: "DISPOSITION_ID_TAGGED",
		19: "DISPOSITION_ID_ALERT",
		20: "DISPOSITION_ID_COUNT",
		21: "DISPOSITION_ID_RESET",
		22: "DISPOSITION_ID_CAPTCHA",
		23: "DISPOSITION_ID_CHALLENGE",
		24: "DISPOSITION_ID_ACCESS_REVOKED",
		25: "DISPOSITION_ID_REJECTED",
		26: "DISPOSITION_ID_UNAUTHORIZED",
		27: "DISPOSITION_ID_ERROR",
		99: "DISPOSITION_ID_OTHER",
	}
	EntityManagement_DispositionId_value = map[string]int32{
		"DISPOSITION_ID_UNKNOWN":             0,
		"DISPOSITION_ID_ALLOWED":             1,
		"DISPOSITION_ID_BLOCKED":             2,
		"DISPOSITION_ID_QUARANTINED":         3,
		"DISPOSITION_ID_ISOLATED":            4,
		"DISPOSITION_ID_DELETED":             5,
		"DISPOSITION_ID_DROPPED":             6,
		"DISPOSITION_ID_CUSTOM_ACTION":       7,
		"DISPOSITION_ID_APPROVED":            8,
		"DISPOSITION_ID_RESTORED":            9,
		"DISPOSITION_ID_EXONERATED":          10,
		"DISPOSITION_ID_CORRECTED":           11,
		"DISPOSITION_ID_PARTIALLY_CORRECTED": 12,
		"DISPOSITION_ID_UNCORRECTED":         13,
		"DISPOSITION_ID_DELAYED":             14,
		"DISPOSITION_ID_DETECTED":            15,
		"DISPOSITION_ID_NO_ACTION":           16,
		"DISPOSITION_ID_LOGGED":              17,
		"DISPOSITION_ID_TAGGED":              18,
		"DISPOSITION_ID_ALERT":               19,
		"DISPOSITION_ID_COUNT":               20,
		"DISPOSITION_ID_RESET":               21,
		"DISPOSITION_ID_CAPTCHA":             22,
		"DISPOSITION_ID_CHALLENGE":           23,
		"DISPOSITION_ID_ACCESS_REVOKED":      24,
		"DISPOSITION_ID_REJECTED":            25,
		"DISPOSITION_ID_UNAUTHORIZED":        26,
		"DISPOSITION_ID_ERROR":               27,
		"DISPOSITION_ID_OTHER":               99,
	}
)

func (x EntityManagement_DispositionId) Enum() *EntityManagement_DispositionId {
	p := new(EntityManagement_DispositionId)
	*p = x
	return p
}

func (x EntityManagement_DispositionId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_DispositionId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[5].Descriptor()
}

func (EntityManagement_DispositionId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[5]
}

func (x EntityManagement_DispositionId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_DispositionId.Descriptor instead.
func (EntityManagement_DispositionId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 5}
}

type EntityManagement_RiskLevelId int32

const (
	EntityManagement_RISK_LEVEL_ID_INFO     EntityManagement_RiskLevelId = 0
	EntityManagement_RISK_LEVEL_ID_LOW      EntityManagement_RiskLevelId = 1
	EntityManagement_RISK_LEVEL_ID_MEDIUM   EntityManagement_RiskLevelId = 2
	EntityManagement_RISK_LEVEL_ID_HIGH     EntityManagement_RiskLevelId = 3
	EntityManagement_RISK_LEVEL_ID_CRITICAL EntityManagement_RiskLevelId = 4
	EntityManagement_RISK_LEVEL_ID_OTHER    EntityManagement_RiskLevelId = 99
)

// Enum value maps for EntityManagement_RiskLevelId.
var (
	EntityManagement_RiskLevelId_name = map[int32]string{
		0:  "RISK_LEVEL_ID_INFO",
		1:  "RISK_LEVEL_ID_LOW",
		2:  "RISK_LEVEL_ID_MEDIUM",
		3:  "RISK_LEVEL_ID_HIGH",
		4:  "RISK_LEVEL_ID_CRITICAL",
		99: "RISK_LEVEL_ID_OTHER",
	}
	EntityManagement_RiskLevelId_value = map[string]int32{
		"RISK_LEVEL_ID_INFO":     0,
		"RISK_LEVEL_ID_LOW":      1,
		"RISK_LEVEL_ID_MEDIUM":   2,
		"RISK_LEVEL_ID_HIGH":     3,
		"RISK_LEVEL_ID_CRITICAL": 4,
		"RISK_LEVEL_ID_OTHER":    99,
	}
)

func (x EntityManagement_RiskLevelId) Enum() *EntityManagement_RiskLevelId {
	p := new(EntityManagement_RiskLevelId)
	*p = x
	return p
}

func (x EntityManagement_RiskLevelId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_RiskLevelId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[6].Descriptor()
}

func (EntityManagement_RiskLevelId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[6]
}

func (x EntityManagement_RiskLevelId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_RiskLevelId.Descriptor instead.
func (EntityManagement_RiskLevelId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 6}
}

type EntityManagement_SeverityId int32

const (
	EntityManagement_SEVERITY_ID_UNKNOWN       EntityManagement_SeverityId = 0
	EntityManagement_SEVERITY_ID_INFORMATIONAL EntityManagement_SeverityId = 1
	EntityManagement_SEVERITY_ID_LOW           EntityManagement_SeverityId = 2
	EntityManagement_SEVERITY_ID_MEDIUM        EntityManagement_SeverityId = 3
	EntityManagement_SEVERITY_ID_HIGH          EntityManagement_SeverityId = 4
	EntityManagement_SEVERITY_ID_CRITICAL      EntityManagement_SeverityId = 5
	EntityManagement_SEVERITY_ID_FATAL         EntityManagement_SeverityId = 6
	EntityManagement_SEVERITY_ID_OTHER         EntityManagement_SeverityId = 99
)

// Enum value maps for EntityManagement_SeverityId.
var (
	EntityManagement_SeverityId_name = map[int32]string{
		0:  "SEVERITY_ID_UNKNOWN",
		1:  "SEVERITY_ID_INFORMATIONAL",
		2:  "SEVERITY_ID_LOW",
		3:  "SEVERITY_ID_MEDIUM",
		4:  "SEVERITY_ID_HIGH",
		5:  "SEVERITY_ID_CRITICAL",
		6:  "SEVERITY_ID_FATAL",
		99: "SEVERITY_ID_OTHER",
	}
	EntityManagement_SeverityId_value = map[string]int32{
		"SEVERITY_ID_UNKNOWN":       0,
		"SEVERITY_ID_INFORMATIONAL": 1,
		"SEVERITY_ID_LOW":           2,
		"SEVERITY_ID_MEDIUM":        3,
		"SEVERITY_ID_HIGH":          4,
		"SEVERITY_ID_CRITICAL":      5,
		"SEVERITY_ID_FATAL":         6,
		"SEVERITY_ID_OTHER":         99,
	}
)

func (x EntityManagement_SeverityId) Enum() *EntityManagement_SeverityId {
	p := new(EntityManagement_SeverityId)
	*p = x
	return p
}

func (x EntityManagement_SeverityId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_SeverityId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[7].Descriptor()
}

func (EntityManagement_SeverityId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[7]
}

func (x EntityManagement_SeverityId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_SeverityId.Descriptor instead.
func (EntityManagement_SeverityId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 7}
}

type EntityManagement_StatusId int32

const (
	EntityManagement_STATUS_ID_UNKNOWN EntityManagement_StatusId = 0
	EntityManagement_STATUS_ID_SUCCESS EntityManagement_StatusId = 1
	EntityManagement_STATUS_ID_FAILURE EntityManagement_StatusId = 2
	EntityManagement_STATUS_ID_OTHER   EntityManagement_StatusId = 99
)

// Enum value maps for EntityManagement_StatusId.
var (
	EntityManagement_StatusId_name = map[int32]string{
		0:  "STATUS_ID_UNKNOWN",
		1:  "STATUS_ID_SUCCESS",
		2:  "STATUS_ID_FAILURE",
		99: "STATUS_ID_OTHER",
	}
	EntityManagement_StatusId_value = map[string]int32{
		"STATUS_ID_UNKNOWN": 0,
		"STATUS_ID_SUCCESS": 1,
		"STATUS_ID_FAILURE": 2,
		"STATUS_ID_OTHER":   99,
	}
)

func (x EntityManagement_StatusId) Enum() *EntityManagement_StatusId {
	p := new(EntityManagement_StatusId)
	*p = x
	return p
}

func (x EntityManagement_StatusId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_StatusId) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[8].Descriptor()
}

func (EntityManagement_StatusId) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[8]
}

func (x EntityManagement_StatusId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_StatusId.Descriptor instead.
func (EntityManagement_StatusId) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 8}
}

type EntityManagement_TypeUid int32

const (
	EntityManagement_TYPE_UID_UNKNOWN                      EntityManagement_TypeUid = 0
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_UNKNOWN    EntityManagement_TypeUid = 300400
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_CREATE     EntityManagement_TypeUid = 300401
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_READ       EntityManagement_TypeUid = 300402
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_UPDATE     EntityManagement_TypeUid = 300403
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_DELETE     EntityManagement_TypeUid = 300404
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_MOVE       EntityManagement_TypeUid = 300405
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_ENROLL     EntityManagement_TypeUid = 300406
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_UNENROLL   EntityManagement_TypeUid = 300407
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_ENABLE     EntityManagement_TypeUid = 300408
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_DISABLE    EntityManagement_TypeUid = 300409
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_ACTIVATE   EntityManagement_TypeUid = 300410
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_DEACTIVATE EntityManagement_TypeUid = 300411
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_SUSPEND    EntityManagement_TypeUid = 300412
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_RESUME     EntityManagement_TypeUid = 300413
	EntityManagement_TYPE_UID_ENTITY_MANAGEMENT_OTHER      EntityManagement_TypeUid = 300499
)

// Enum value maps for EntityManagement_TypeUid.
var (
	EntityManagement_TypeUid_name = map[int32]string{
		0:      "TYPE_UID_UNKNOWN",
		300400: "TYPE_UID_ENTITY_MANAGEMENT_UNKNOWN",
		300401: "TYPE_UID_ENTITY_MANAGEMENT_CREATE",
		300402: "TYPE_UID_ENTITY_MANAGEMENT_READ",
		300403: "TYPE_UID_ENTITY_MANAGEMENT_UPDATE",
		300404: "TYPE_UID_ENTITY_MANAGEMENT_DELETE",
		300405: "TYPE_UID_ENTITY_MANAGEMENT_MOVE",
		300406: "TYPE_UID_ENTITY_MANAGEMENT_ENROLL",
		300407: "TYPE_UID_ENTITY_MANAGEMENT_UNENROLL",
		300408: "TYPE_UID_ENTITY_MANAGEMENT_ENABLE",
		300409: "TYPE_UID_ENTITY_MANAGEMENT_DISABLE",
		300410: "TYPE_UID_ENTITY_MANAGEMENT_ACTIVATE",
		300411: "TYPE_UID_ENTITY_MANAGEMENT_DEACTIVATE",
		300412: "TYPE_UID_ENTITY_MANAGEMENT_SUSPEND",
		300413: "TYPE_UID_ENTITY_MANAGEMENT_RESUME",
		300499: "TYPE_UID_ENTITY_MANAGEMENT_OTHER",
	}
	EntityManagement_TypeUid_value = map[string]int32{
		"TYPE_UID_UNKNOWN":                      0,
		"TYPE_UID_ENTITY_MANAGEMENT_UNKNOWN":    300400,
		"TYPE_UID_ENTITY_MANAGEMENT_CREATE":     300401,
		"TYPE_UID_ENTITY_MANAGEMENT_READ":       300402,
		"TYPE_UID_ENTITY_MANAGEMENT_UPDATE":     300403,
		"TYPE_UID_ENTITY_MANAGEMENT_DELETE":     300404,
		"TYPE_UID_ENTITY_MANAGEMENT_MOVE":       300405,
		"TYPE_UID_ENTITY_MANAGEMENT_ENROLL":     300406,
		"TYPE_UID_ENTITY_MANAGEMENT_UNENROLL":   300407,
		"TYPE_UID_ENTITY_MANAGEMENT_ENABLE":     300408,
		"TYPE_UID_ENTITY_MANAGEMENT_DISABLE":    300409,
		"TYPE_UID_ENTITY_MANAGEMENT_ACTIVATE":   300410,
		"TYPE_UID_ENTITY_MANAGEMENT_DEACTIVATE": 300411,
		"TYPE_UID_ENTITY_MANAGEMENT_SUSPEND":    300412,
		"TYPE_UID_ENTITY_MANAGEMENT_RESUME":     300413,
		"TYPE_UID_ENTITY_MANAGEMENT_OTHER":      300499,
	}
)

func (x EntityManagement_TypeUid) Enum() *EntityManagement_TypeUid {
	p := new(EntityManagement_TypeUid)
	*p = x
	return p
}

func (x EntityManagement_TypeUid) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityManagement_TypeUid) Descriptor() protoreflect.EnumDescriptor {
	return file_ocsf_v1_entity_management_proto_enumTypes[9].Descriptor()
}

func (EntityManagement_TypeUid) Type() protoreflect.EnumType {
	return &file_ocsf_v1_entity_management_proto_enumTypes[9]
}

func (x EntityManagement_TypeUid) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityManagement_TypeUid.Descriptor instead.
func (EntityManagement_TypeUid) EnumDescriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0, 9}
}

type EntityManagement struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	AccessList      []string                       `protobuf:"bytes,1,rep,name=access_list,json=accessList,proto3" json:"access_list,omitempty"`
	AccessMask      int32                          `protobuf:"varint,2,opt,name=access_mask,json=accessMask,proto3" json:"access_mask,omitempty"`
	Action          string                         `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	ActionId        EntityManagement_ActionId      `protobuf:"varint,4,opt,name=action_id,json=actionId,proto3,enum=ocsf.v1.EntityManagement_ActionId" json:"action_id,omitempty"`
	ActivityId      EntityManagement_ActivityId    `protobuf:"varint,5,opt,name=activity_id,json=activityId,proto3,enum=ocsf.v1.EntityManagement_ActivityId" json:"activity_id,omitempty"`
	ActivityName    string                         `protobuf:"bytes,6,opt,name=activity_name,json=activityName,proto3" json:"activity_name,omitempty"`
	Actor           *Actor                         `protobuf:"bytes,7,opt,name=actor,proto3" json:"actor,omitempty"`
	Api             *Api                           `protobuf:"bytes,8,opt,name=api,proto3" json:"api,omitempty"`
	Attacks         []*Attack                      `protobuf:"bytes,9,rep,name=attacks,proto3" json:"attacks,omitempty"`
	Authorizations  []*Authorization               `protobuf:"bytes,10,rep,name=authorizations,proto3" json:"authorizations,omitempty"`
	CategoryName    string                         `protobuf:"bytes,11,opt,name=category_name,json=categoryName,proto3" json:"category_name,omitempty"`
	CategoryUid     EntityManagement_CategoryUid   `protobuf:"varint,12,opt,name=category_uid,json=categoryUid,proto3,enum=ocsf.v1.EntityManagement_CategoryUid" json:"category_uid,omitempty"`
	ClassName       string                         `protobuf:"bytes,13,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	ClassUid        EntityManagement_ClassUid      `protobuf:"varint,14,opt,name=class_uid,json=classUid,proto3,enum=ocsf.v1.EntityManagement_ClassUid" json:"class_uid,omitempty"`
	Cloud           *Cloud                         `protobuf:"bytes,15,opt,name=cloud,proto3" json:"cloud,omitempty"`
	Comment         string                         `protobuf:"bytes,16,opt,name=comment,proto3" json:"comment,omitempty"`
	Confidence      string                         `protobuf:"bytes,17,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ConfidenceId    EntityManagement_ConfidenceId  `protobuf:"varint,18,opt,name=confidence_id,json=confidenceId,proto3,enum=ocsf.v1.EntityManagement_ConfidenceId" json:"confidence_id,omitempty"`
	ConfidenceScore int32                          `protobuf:"varint,19,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	Count           int32                          `protobuf:"varint,20,opt,name=count,proto3" json:"count,omitempty"`
	Device          *Device                        `protobuf:"bytes,21,opt,name=device,proto3" json:"device,omitempty"`
	Disposition     string                         `protobuf:"bytes,22,opt,name=disposition,proto3" json:"disposition,omitempty"`
	DispositionId   EntityManagement_DispositionId `protobuf:"varint,23,opt,name=disposition_id,json=dispositionId,proto3,enum=ocsf.v1.EntityManagement_DispositionId" json:"disposition_id,omitempty"`
	Duration        int64                          `protobuf:"varint,24,opt,name=duration,proto3" json:"duration,omitempty"`
	EndTime         int64                          `protobuf:"varint,25,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	EndTimeDt       string                         `protobuf:"bytes,26,opt,name=end_time_dt,json=endTimeDt,proto3" json:"end_time_dt,omitempty"`
	Enrichments     []*Enrichment                  `protobuf:"bytes,27,rep,name=enrichments,proto3" json:"enrichments,omitempty"`
	Entity          *ManagedEntity                 `protobuf:"bytes,28,opt,name=entity,proto3" json:"entity,omitempty"`
	EntityResult    *ManagedEntity                 `protobuf:"bytes,29,opt,name=entity_result,json=entityResult,proto3" json:"entity_result,omitempty"`
	FirewallRule    *FirewallRule                  `protobuf:"bytes,30,opt,name=firewall_rule,json=firewallRule,proto3" json:"firewall_rule,omitempty"`
	HttpRequest     *HttpRequest                   `protobuf:"bytes,31,opt,name=http_request,json=httpRequest,proto3" json:"http_request,omitempty"`
	HttpResponse    *HttpResponse                  `protobuf:"bytes,32,opt,name=http_response,json=httpResponse,proto3" json:"http_response,omitempty"`
	IsAlert         bool                           `protobuf:"varint,33,opt,name=is_alert,json=isAlert,proto3" json:"is_alert,omitempty"`
	Malware         []*Malware                     `protobuf:"bytes,34,rep,name=malware,proto3" json:"malware,omitempty"`
	MalwareScanInfo *MalwareScanInfo               `protobuf:"bytes,35,opt,name=malware_scan_info,json=malwareScanInfo,proto3" json:"malware_scan_info,omitempty"`
	Message         string                         `protobuf:"bytes,36,opt,name=message,proto3" json:"message,omitempty"`
	Metadata        *Metadata                      `protobuf:"bytes,37,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Observables     []*Observable                  `protobuf:"bytes,38,rep,name=observables,proto3" json:"observables,omitempty"`
	Osint           []*Osint                       `protobuf:"bytes,39,rep,name=osint,proto3" json:"osint,omitempty"`
	Policy          *Policy                        `protobuf:"bytes,40,opt,name=policy,proto3" json:"policy,omitempty"`
	RawData         string                         `protobuf:"bytes,41,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	RawDataHash     *Fingerprint                   `protobuf:"bytes,42,opt,name=raw_data_hash,json=rawDataHash,proto3" json:"raw_data_hash,omitempty"`
	RawDataSize     int64                          `protobuf:"varint,43,opt,name=raw_data_size,json=rawDataSize,proto3" json:"raw_data_size,omitempty"`
	RiskDetails     string                         `protobuf:"bytes,44,opt,name=risk_details,json=riskDetails,proto3" json:"risk_details,omitempty"`
	RiskLevel       string                         `protobuf:"bytes,45,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	RiskLevelId     EntityManagement_RiskLevelId   `protobuf:"varint,46,opt,name=risk_level_id,json=riskLevelId,proto3,enum=ocsf.v1.EntityManagement_RiskLevelId" json:"risk_level_id,omitempty"`
	RiskScore       int32                          `protobuf:"varint,47,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	Severity        string                         `protobuf:"bytes,48,opt,name=severity,proto3" json:"severity,omitempty"`
	SeverityId      EntityManagement_SeverityId    `protobuf:"varint,49,opt,name=severity_id,json=severityId,proto3,enum=ocsf.v1.EntityManagement_SeverityId" json:"severity_id,omitempty"`
	SrcEndpoint     *NetworkEndpoint               `protobuf:"bytes,50,opt,name=src_endpoint,json=srcEndpoint,proto3" json:"src_endpoint,omitempty"`
	StartTime       int64                          `protobuf:"varint,51,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	StartTimeDt     string                         `protobuf:"bytes,52,opt,name=start_time_dt,json=startTimeDt,proto3" json:"start_time_dt,omitempty"`
	Status          string                         `protobuf:"bytes,53,opt,name=status,proto3" json:"status,omitempty"`
	StatusCode      string                         `protobuf:"bytes,54,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	StatusDetail    string                         `protobuf:"bytes,55,opt,name=status_detail,json=statusDetail,proto3" json:"status_detail,omitempty"`
	StatusId        EntityManagement_StatusId      `protobuf:"varint,56,opt,name=status_id,json=statusId,proto3,enum=ocsf.v1.EntityManagement_StatusId" json:"status_id,omitempty"`
	Time            int64                          `protobuf:"varint,57,opt,name=time,proto3" json:"time,omitempty"`
	TimeDt          string                         `protobuf:"bytes,58,opt,name=time_dt,json=timeDt,proto3" json:"time_dt,omitempty"`
	TimezoneOffset  int32                          `protobuf:"varint,59,opt,name=timezone_offset,json=timezoneOffset,proto3" json:"timezone_offset,omitempty"`
	TypeName        string                         `protobuf:"bytes,60,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	TypeUid         EntityManagement_TypeUid       `protobuf:"varint,61,opt,name=type_uid,json=typeUid,proto3,enum=ocsf.v1.EntityManagement_TypeUid" json:"type_uid,omitempty"`
	Unmapped        *structpb.Value                `protobuf:"bytes,62,opt,name=unmapped,proto3" json:"unmapped,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EntityManagement) Reset() {
	*x = EntityManagement{}
	mi := &file_ocsf_v1_entity_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityManagement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityManagement) ProtoMessage() {}

func (x *EntityManagement) ProtoReflect() protoreflect.Message {
	mi := &file_ocsf_v1_entity_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityManagement.ProtoReflect.Descriptor instead.
func (*EntityManagement) Descriptor() ([]byte, []int) {
	return file_ocsf_v1_entity_management_proto_rawDescGZIP(), []int{0}
}

func (x *EntityManagement) GetAccessList() []string {
	if x != nil {
		return x.AccessList
	}
	return nil
}

func (x *EntityManagement) GetAccessMask() int32 {
	if x != nil {
		return x.AccessMask
	}
	return 0
}

func (x *EntityManagement) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *EntityManagement) GetActionId() EntityManagement_ActionId {
	if x != nil {
		return x.ActionId
	}
	return EntityManagement_ACTION_ID_UNKNOWN
}

func (x *EntityManagement) GetActivityId() EntityManagement_ActivityId {
	if x != nil {
		return x.ActivityId
	}
	return EntityManagement_ACTIVITY_ID_UNKNOWN
}

func (x *EntityManagement) GetActivityName() string {
	if x != nil {
		return x.ActivityName
	}
	return ""
}

func (x *EntityManagement) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *EntityManagement) GetApi() *Api {
	if x != nil {
		return x.Api
	}
	return nil
}

func (x *EntityManagement) GetAttacks() []*Attack {
	if x != nil {
		return x.Attacks
	}
	return nil
}

func (x *EntityManagement) GetAuthorizations() []*Authorization {
	if x != nil {
		return x.Authorizations
	}
	return nil
}

func (x *EntityManagement) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *EntityManagement) GetCategoryUid() EntityManagement_CategoryUid {
	if x != nil {
		return x.CategoryUid
	}
	return EntityManagement_CATEGORY_UID_UNKNOWN
}

func (x *EntityManagement) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *EntityManagement) GetClassUid() EntityManagement_ClassUid {
	if x != nil {
		return x.ClassUid
	}
	return EntityManagement_CLASS_UID_UNKNOWN
}

func (x *EntityManagement) GetCloud() *Cloud {
	if x != nil {
		return x.Cloud
	}
	return nil
}

func (x *EntityManagement) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *EntityManagement) GetConfidence() string {
	if x != nil {
		return x.Confidence
	}
	return ""
}

func (x *EntityManagement) GetConfidenceId() EntityManagement_ConfidenceId {
	if x != nil {
		return x.ConfidenceId
	}
	return EntityManagement_CONFIDENCE_ID_UNKNOWN
}

func (x *EntityManagement) GetConfidenceScore() int32 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *EntityManagement) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *EntityManagement) GetDevice() *Device {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *EntityManagement) GetDisposition() string {
	if x != nil {
		return x.Disposition
	}
	return ""
}

func (x *EntityManagement) GetDispositionId() EntityManagement_DispositionId {
	if x != nil {
		return x.DispositionId
	}
	return EntityManagement_DISPOSITION_ID_UNKNOWN
}

func (x *EntityManagement) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *EntityManagement) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *EntityManagement) GetEndTimeDt() string {
	if x != nil {
		return x.EndTimeDt
	}
	return ""
}

func (x *EntityManagement) GetEnrichments() []*Enrichment {
	if x != nil {
		return x.Enrichments
	}
	return nil
}

func (x *EntityManagement) GetEntity() *ManagedEntity {
	if x != nil {
		return x.Entity
	}
	return nil
}

func (x *EntityManagement) GetEntityResult() *ManagedEntity {
	if x != nil {
		return x.EntityResult
	}
	return nil
}

func (x *EntityManagement) GetFirewallRule() *FirewallRule {
	if x != nil {
		return x.FirewallRule
	}
	return nil
}

func (x *EntityManagement) GetHttpRequest() *HttpRequest {
	if x != nil {
		return x.HttpRequest
	}
	return nil
}

func (x *EntityManagement) GetHttpResponse() *HttpResponse {
	if x != nil {
		return x.HttpResponse
	}
	return nil
}

func (x *EntityManagement) GetIsAlert() bool {
	if x != nil {
		return x.IsAlert
	}
	return false
}

func (x *EntityManagement) GetMalware() []*Malware {
	if x != nil {
		return x.Malware
	}
	return nil
}

func (x *EntityManagement) GetMalwareScanInfo() *MalwareScanInfo {
	if x != nil {
		return x.MalwareScanInfo
	}
	return nil
}

func (x *EntityManagement) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EntityManagement) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *EntityManagement) GetObservables() []*Observable {
	if x != nil {
		return x.Observables
	}
	return nil
}

func (x *EntityManagement) GetOsint() []*Osint {
	if x != nil {
		return x.Osint
	}
	return nil
}

func (x *EntityManagement) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *EntityManagement) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

func (x *EntityManagement) GetRawDataHash() *Fingerprint {
	if x != nil {
		return x.RawDataHash
	}
	return nil
}

func (x *EntityManagement) GetRawDataSize() int64 {
	if x != nil {
		return x.RawDataSize
	}
	return 0
}

func (x *EntityManagement) GetRiskDetails() string {
	if x != nil {
		return x.RiskDetails
	}
	return ""
}

func (x *EntityManagement) GetRiskLevel() string {
	if x != nil {
		return x.RiskLevel
	}
	return ""
}

func (x *EntityManagement) GetRiskLevelId() EntityManagement_RiskLevelId {
	if x != nil {
		return x.RiskLevelId
	}
	return EntityManagement_RISK_LEVEL_ID_INFO
}

func (x *EntityManagement) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *EntityManagement) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *EntityManagement) GetSeverityId() EntityManagement_SeverityId {
	if x != nil {
		return x.SeverityId
	}
	return EntityManagement_SEVERITY_ID_UNKNOWN
}

func (x *EntityManagement) GetSrcEndpoint() *NetworkEndpoint {
	if x != nil {
		return x.SrcEndpoint
	}
	return nil
}

func (x *EntityManagement) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *EntityManagement) GetStartTimeDt() string {
	if x != nil {
		return x.StartTimeDt
	}
	return ""
}

func (x *EntityManagement) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EntityManagement) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

func (x *EntityManagement) GetStatusDetail() string {
	if x != nil {
		return x.StatusDetail
	}
	return ""
}

func (x *EntityManagement) GetStatusId() EntityManagement_StatusId {
	if x != nil {
		return x.StatusId
	}
	return EntityManagement_STATUS_ID_UNKNOWN
}

func (x *EntityManagement) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *EntityManagement) GetTimeDt() string {
	if x != nil {
		return x.TimeDt
	}
	return ""
}

func (x *EntityManagement) GetTimezoneOffset() int32 {
	if x != nil {
		return x.TimezoneOffset
	}
	return 0
}

func (x *EntityManagement) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *EntityManagement) GetTypeUid() EntityManagement_TypeUid {
	if x != nil {
		return x.TypeUid
	}
	return EntityManagement_TYPE_UID_UNKNOWN
}

func (x *EntityManagement) GetUnmapped() *structpb.Value {
	if x != nil {
		return x.Unmapped
	}
	return nil
}

var File_ocsf_v1_entity_management_proto protoreflect.FileDescriptor

const file_ocsf_v1_entity_management_proto_rawDesc = "" +
	"\n" +
	"\x1focsf/v1/entity_management.proto\x12\aocsf.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x15ocsf/v1/objects.proto\"\x8d,\n" +
	"\x10EntityManagement\x12\x1f\n" +
	"\vaccess_list\x18\x01 \x03(\tR\n" +
	"accessList\x12\x1f\n" +
	"\vaccess_mask\x18\x02 \x01(\x05R\n" +
	"accessMask\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12?\n" +
	"\taction_id\x18\x04 \x01(\x0e2\".ocsf.v1.EntityManagement.ActionIdR\bactionId\x12M\n" +
	"\vactivity_id\x18\x05 \x01(\x0e2$.ocsf.v1.EntityManagement.ActivityIdB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"activityId\x12#\n" +
	"\ractivity_name\x18\x06 \x01(\tR\factivityName\x12$\n" +
	"\x05actor\x18\a \x01(\v2\x0e.ocsf.v1.ActorR\x05actor\x12\x1e\n" +
	"\x03api\x18\b \x01(\v2\f.ocsf.v1.ApiR\x03api\x12)\n" +
	"\aattacks\x18\t \x03(\v2\x0f.ocsf.v1.AttackR\aattacks\x12>\n" +
	"\x0eauthorizations\x18\n" +
	" \x03(\v2\x16.ocsf.v1.AuthorizationR\x0eauthorizations\x12#\n" +
	"\rcategory_name\x18\v \x01(\tR\fcategoryName\x12P\n" +
	"\fcategory_uid\x18\f \x01(\x0e2%.ocsf.v1.EntityManagement.CategoryUidB\x06\xbaH\x03\xc8\x01\x01R\vcategoryUid\x12\x1d\n" +
	"\n" +
	"class_name\x18\r \x01(\tR\tclassName\x12G\n" +
	"\tclass_uid\x18\x0e \x01(\x0e2\".ocsf.v1.EntityManagement.ClassUidB\x06\xbaH\x03\xc8\x01\x01R\bclassUid\x12,\n" +
	"\x05cloud\x18\x0f \x01(\v2\x0e.ocsf.v1.CloudB\x06\xbaH\x03\xc8\x01\x01R\x05cloud\x12\x18\n" +
	"\acomment\x18\x10 \x01(\tR\acomment\x12\x1e\n" +
	"\n" +
	"confidence\x18\x11 \x01(\tR\n" +
	"confidence\x12K\n" +
	"\rconfidence_id\x18\x12 \x01(\x0e2&.ocsf.v1.EntityManagement.ConfidenceIdR\fconfidenceId\x12)\n" +
	"\x10confidence_score\x18\x13 \x01(\x05R\x0fconfidenceScore\x12\x14\n" +
	"\x05count\x18\x14 \x01(\x05R\x05count\x12'\n" +
	"\x06device\x18\x15 \x01(\v2\x0f.ocsf.v1.DeviceR\x06device\x12 \n" +
	"\vdisposition\x18\x16 \x01(\tR\vdisposition\x12N\n" +
	"\x0edisposition_id\x18\x17 \x01(\x0e2'.ocsf.v1.EntityManagement.DispositionIdR\rdispositionId\x12\x1a\n" +
	"\bduration\x18\x18 \x01(\x03R\bduration\x12\x19\n" +
	"\bend_time\x18\x19 \x01(\x03R\aendTime\x12\x1e\n" +
	"\vend_time_dt\x18\x1a \x01(\tR\tendTimeDt\x125\n" +
	"\venrichments\x18\x1b \x03(\v2\x13.ocsf.v1.EnrichmentR\venrichments\x126\n" +
	"\x06entity\x18\x1c \x01(\v2\x16.ocsf.v1.ManagedEntityB\x06\xbaH\x03\xc8\x01\x01R\x06entity\x12;\n" +
	"\rentity_result\x18\x1d \x01(\v2\x16.ocsf.v1.ManagedEntityR\fentityResult\x12:\n" +
	"\rfirewall_rule\x18\x1e \x01(\v2\x15.ocsf.v1.FirewallRuleR\ffirewallRule\x127\n" +
	"\fhttp_request\x18\x1f \x01(\v2\x14.ocsf.v1.HttpRequestR\vhttpRequest\x12:\n" +
	"\rhttp_response\x18  \x01(\v2\x15.ocsf.v1.HttpResponseR\fhttpResponse\x12\x19\n" +
	"\bis_alert\x18! \x01(\bR\aisAlert\x12*\n" +
	"\amalware\x18\" \x03(\v2\x10.ocsf.v1.MalwareR\amalware\x12D\n" +
	"\x11malware_scan_info\x18# \x01(\v2\x18.ocsf.v1.MalwareScanInfoR\x0fmalwareScanInfo\x12\x18\n" +
	"\amessage\x18$ \x01(\tR\amessage\x125\n" +
	"\bmetadata\x18% \x01(\v2\x11.ocsf.v1.MetadataB\x06\xbaH\x03\xc8\x01\x01R\bmetadata\x125\n" +
	"\vobservables\x18& \x03(\v2\x13.ocsf.v1.ObservableR\vobservables\x12$\n" +
	"\x05osint\x18' \x03(\v2\x0e.ocsf.v1.OsintR\x05osint\x12'\n" +
	"\x06policy\x18( \x01(\v2\x0f.ocsf.v1.PolicyR\x06policy\x12\x19\n" +
	"\braw_data\x18) \x01(\tR\arawData\x128\n" +
	"\rraw_data_hash\x18* \x01(\v2\x14.ocsf.v1.FingerprintR\vrawDataHash\x12\"\n" +
	"\rraw_data_size\x18+ \x01(\x03R\vrawDataSize\x12!\n" +
	"\frisk_details\x18, \x01(\tR\vriskDetails\x12\x1d\n" +
	"\n" +
	"risk_level\x18- \x01(\tR\triskLevel\x12I\n" +
	"\rrisk_level_id\x18. \x01(\x0e2%.ocsf.v1.EntityManagement.RiskLevelIdR\vriskLevelId\x12\x1d\n" +
	"\n" +
	"risk_score\x18/ \x01(\x05R\triskScore\x12\x1a\n" +
	"\bseverity\x180 \x01(\tR\bseverity\x12M\n" +
	"\vseverity_id\x181 \x01(\x0e2$.ocsf.v1.EntityManagement.SeverityIdB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"severityId\x12;\n" +
	"\fsrc_endpoint\x182 \x01(\v2\x18.ocsf.v1.NetworkEndpointR\vsrcEndpoint\x12\x1d\n" +
	"\n" +
	"start_time\x183 \x01(\x03R\tstartTime\x12\"\n" +
	"\rstart_time_dt\x184 \x01(\tR\vstartTimeDt\x12\x16\n" +
	"\x06status\x185 \x01(\tR\x06status\x12\x1f\n" +
	"\vstatus_code\x186 \x01(\tR\n" +
	"statusCode\x12#\n" +
	"\rstatus_detail\x187 \x01(\tR\fstatusDetail\x12?\n" +
	"\tstatus_id\x188 \x01(\x0e2\".ocsf.v1.EntityManagement.StatusIdR\bstatusId\x12\x1a\n" +
	"\x04time\x189 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\x04time\x12\x17\n" +
	"\atime_dt\x18: \x01(\tR\x06timeDt\x12'\n" +
	"\x0ftimezone_offset\x18; \x01(\x05R\x0etimezoneOffset\x12\x1b\n" +
	"\ttype_name\x18< \x01(\tR\btypeName\x12D\n" +
	"\btype_uid\x18= \x01(\x0e2!.ocsf.v1.EntityManagement.TypeUidB\x06\xbaH\x03\xc8\x01\x01R\atypeUid\x122\n" +
	"\bunmapped\x18> \x01(\v2\x16.google.protobuf.ValueR\bunmapped\"\x93\x01\n" +
	"\bActionId\x12\x15\n" +
	"\x11ACTION_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11ACTION_ID_ALLOWED\x10\x01\x12\x14\n" +
	"\x10ACTION_ID_DENIED\x10\x02\x12\x16\n" +
	"\x12ACTION_ID_OBSERVED\x10\x03\x12\x16\n" +
	"\x12ACTION_ID_MODIFIED\x10\x04\x12\x13\n" +
	"\x0fACTION_ID_OTHER\x10c\"\xfa\x02\n" +
	"\n" +
	"ActivityId\x12\x17\n" +
	"\x13ACTIVITY_ID_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12ACTIVITY_ID_CREATE\x10\x01\x12\x14\n" +
	"\x10ACTIVITY_ID_READ\x10\x02\x12\x16\n" +
	"\x12ACTIVITY_ID_UPDATE\x10\x03\x12\x16\n" +
	"\x12ACTIVITY_ID_DELETE\x10\x04\x12\x14\n" +
	"\x10ACTIVITY_ID_MOVE\x10\x05\x12\x16\n" +
	"\x12ACTIVITY_ID_ENROLL\x10\x06\x12\x18\n" +
	"\x14ACTIVITY_ID_UNENROLL\x10\a\x12\x16\n" +
	"\x12ACTIVITY_ID_ENABLE\x10\b\x12\x17\n" +
	"\x13ACTIVITY_ID_DISABLE\x10\t\x12\x18\n" +
	"\x14ACTIVITY_ID_ACTIVATE\x10\n" +
	"\x12\x1a\n" +
	"\x16ACTIVITY_ID_DEACTIVATE\x10\v\x12\x17\n" +
	"\x13ACTIVITY_ID_SUSPEND\x10\f\x12\x16\n" +
	"\x12ACTIVITY_ID_RESUME\x10\r\x12\x15\n" +
	"\x11ACTIVITY_ID_OTHER\x10c\"T\n" +
	"\vCategoryUid\x12\x18\n" +
	"\x14CATEGORY_UID_UNKNOWN\x10\x00\x12+\n" +
	"'CATEGORY_UID_IDENTITY_ACCESS_MANAGEMENT\x10\x03\"C\n" +
	"\bClassUid\x12\x15\n" +
	"\x11CLASS_UID_UNKNOWN\x10\x00\x12 \n" +
	"\x1bCLASS_UID_ENTITY_MANAGEMENT\x10\xbc\x17\"\x8b\x01\n" +
	"\fConfidenceId\x12\x19\n" +
	"\x15CONFIDENCE_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11CONFIDENCE_ID_LOW\x10\x01\x12\x18\n" +
	"\x14CONFIDENCE_ID_MEDIUM\x10\x02\x12\x16\n" +
	"\x12CONFIDENCE_ID_HIGH\x10\x03\x12\x17\n" +
	"\x13CONFIDENCE_ID_OTHER\x10c\"\xe3\x06\n" +
	"\rDispositionId\x12\x1a\n" +
	"\x16DISPOSITION_ID_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16DISPOSITION_ID_ALLOWED\x10\x01\x12\x1a\n" +
	"\x16DISPOSITION_ID_BLOCKED\x10\x02\x12\x1e\n" +
	"\x1aDISPOSITION_ID_QUARANTINED\x10\x03\x12\x1b\n" +
	"\x17DISPOSITION_ID_ISOLATED\x10\x04\x12\x1a\n" +
	"\x16DISPOSITION_ID_DELETED\x10\x05\x12\x1a\n" +
	"\x16DISPOSITION_ID_DROPPED\x10\x06\x12 \n" +
	"\x1cDISPOSITION_ID_CUSTOM_ACTION\x10\a\x12\x1b\n" +
	"\x17DISPOSITION_ID_APPROVED\x10\b\x12\x1b\n" +
	"\x17DISPOSITION_ID_RESTORED\x10\t\x12\x1d\n" +
	"\x19DISPOSITION_ID_EXONERATED\x10\n" +
	"\x12\x1c\n" +
	"\x18DISPOSITION_ID_CORRECTED\x10\v\x12&\n" +
	"\"DISPOSITION_ID_PARTIALLY_CORRECTED\x10\f\x12\x1e\n" +
	"\x1aDISPOSITION_ID_UNCORRECTED\x10\r\x12\x1a\n" +
	"\x16DISPOSITION_ID_DELAYED\x10\x0e\x12\x1b\n" +
	"\x17DISPOSITION_ID_DETECTED\x10\x0f\x12\x1c\n" +
	"\x18DISPOSITION_ID_NO_ACTION\x10\x10\x12\x19\n" +
	"\x15DISPOSITION_ID_LOGGED\x10\x11\x12\x19\n" +
	"\x15DISPOSITION_ID_TAGGED\x10\x12\x12\x18\n" +
	"\x14DISPOSITION_ID_ALERT\x10\x13\x12\x18\n" +
	"\x14DISPOSITION_ID_COUNT\x10\x14\x12\x18\n" +
	"\x14DISPOSITION_ID_RESET\x10\x15\x12\x1a\n" +
	"\x16DISPOSITION_ID_CAPTCHA\x10\x16\x12\x1c\n" +
	"\x18DISPOSITION_ID_CHALLENGE\x10\x17\x12!\n" +
	"\x1dDISPOSITION_ID_ACCESS_REVOKED\x10\x18\x12\x1b\n" +
	"\x17DISPOSITION_ID_REJECTED\x10\x19\x12\x1f\n" +
	"\x1bDISPOSITION_ID_UNAUTHORIZED\x10\x1a\x12\x18\n" +
	"\x14DISPOSITION_ID_ERROR\x10\x1b\x12\x18\n" +
	"\x14DISPOSITION_ID_OTHER\x10c\"\xa3\x01\n" +
	"\vRiskLevelId\x12\x16\n" +
	"\x12RISK_LEVEL_ID_INFO\x10\x00\x12\x15\n" +
	"\x11RISK_LEVEL_ID_LOW\x10\x01\x12\x18\n" +
	"\x14RISK_LEVEL_ID_MEDIUM\x10\x02\x12\x16\n" +
	"\x12RISK_LEVEL_ID_HIGH\x10\x03\x12\x1a\n" +
	"\x16RISK_LEVEL_ID_CRITICAL\x10\x04\x12\x17\n" +
	"\x13RISK_LEVEL_ID_OTHER\x10c\"\xcf\x01\n" +
	"\n" +
	"SeverityId\x12\x17\n" +
	"\x13SEVERITY_ID_UNKNOWN\x10\x00\x12\x1d\n" +
	"\x19SEVERITY_ID_INFORMATIONAL\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_ID_LOW\x10\x02\x12\x16\n" +
	"\x12SEVERITY_ID_MEDIUM\x10\x03\x12\x14\n" +
	"\x10SEVERITY_ID_HIGH\x10\x04\x12\x18\n" +
	"\x14SEVERITY_ID_CRITICAL\x10\x05\x12\x15\n" +
	"\x11SEVERITY_ID_FATAL\x10\x06\x12\x15\n" +
	"\x11SEVERITY_ID_OTHER\x10c\"d\n" +
	"\bStatusId\x12\x15\n" +
	"\x11STATUS_ID_UNKNOWN\x10\x00\x12\x15\n" +
	"\x11STATUS_ID_SUCCESS\x10\x01\x12\x15\n" +
	"\x11STATUS_ID_FAILURE\x10\x02\x12\x13\n" +
	"\x0fSTATUS_ID_OTHER\x10c\"\x8c\x05\n" +
	"\aTypeUid\x12\x14\n" +
	"\x10TYPE_UID_UNKNOWN\x10\x00\x12(\n" +
	"\"TYPE_UID_ENTITY_MANAGEMENT_UNKNOWN\x10\xf0\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_CREATE\x10\xf1\xaa\x12\x12%\n" +
	"\x1fTYPE_UID_ENTITY_MANAGEMENT_READ\x10\xf2\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_UPDATE\x10\xf3\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_DELETE\x10\xf4\xaa\x12\x12%\n" +
	"\x1fTYPE_UID_ENTITY_MANAGEMENT_MOVE\x10\xf5\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_ENROLL\x10\xf6\xaa\x12\x12)\n" +
	"#TYPE_UID_ENTITY_MANAGEMENT_UNENROLL\x10\xf7\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_ENABLE\x10\xf8\xaa\x12\x12(\n" +
	"\"TYPE_UID_ENTITY_MANAGEMENT_DISABLE\x10\xf9\xaa\x12\x12)\n" +
	"#TYPE_UID_ENTITY_MANAGEMENT_ACTIVATE\x10\xfa\xaa\x12\x12+\n" +
	"%TYPE_UID_ENTITY_MANAGEMENT_DEACTIVATE\x10\xfb\xaa\x12\x12(\n" +
	"\"TYPE_UID_ENTITY_MANAGEMENT_SUSPEND\x10\xfc\xaa\x12\x12'\n" +
	"!TYPE_UID_ENTITY_MANAGEMENT_RESUME\x10\xfd\xaa\x12\x12&\n" +
	" TYPE_UID_ENTITY_MANAGEMENT_OTHER\x10ӫ\x12b\x06proto3"

var (
	file_ocsf_v1_entity_management_proto_rawDescOnce sync.Once
	file_ocsf_v1_entity_management_proto_rawDescData []byte
)

func file_ocsf_v1_entity_management_proto_rawDescGZIP() []byte {
	file_ocsf_v1_entity_management_proto_rawDescOnce.Do(func() {
		file_ocsf_v1_entity_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ocsf_v1_entity_management_proto_rawDesc), len(file_ocsf_v1_entity_management_proto_rawDesc)))
	})
	return file_ocsf_v1_entity_management_proto_rawDescData
}

var file_ocsf_v1_entity_management_proto_enumTypes = make([]protoimpl.EnumInfo, 10)
var file_ocsf_v1_entity_management_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ocsf_v1_entity_management_proto_goTypes = []any{
	(EntityManagement_ActionId)(0),      // 0: ocsf.v1.EntityManagement.ActionId
	(EntityManagement_ActivityId)(0),    // 1: ocsf.v1.EntityManagement.ActivityId
	(EntityManagement_CategoryUid)(0),   // 2: ocsf.v1.EntityManagement.CategoryUid
	(EntityManagement_ClassUid)(0),      // 3: ocsf.v1.EntityManagement.ClassUid
	(EntityManagement_ConfidenceId)(0),  // 4: ocsf.v1.EntityManagement.ConfidenceId
	(EntityManagement_DispositionId)(0), // 5: ocsf.v1.EntityManagement.DispositionId
	(EntityManagement_RiskLevelId)(0),   // 6: ocsf.v1.EntityManagement.RiskLevelId
	(EntityManagement_SeverityId)(0),    // 7: ocsf.v1.EntityManagement.SeverityId
	(EntityManagement_StatusId)(0),      // 8: ocsf.v1.EntityManagement.StatusId
	(EntityManagement_TypeUid)(0),       // 9: ocsf.v1.EntityManagement.TypeUid
	(*EntityManagement)(nil),            // 10: ocsf.v1.EntityManagement
	(*Actor)(nil),                       // 11: ocsf.v1.Actor
	(*Api)(nil),                         // 12: ocsf.v1.Api
	(*Attack)(nil),                      // 13: ocsf.v1.Attack
	(*Authorization)(nil),               // 14: ocsf.v1.Authorization
	(*Cloud)(nil),                       // 15: ocsf.v1.Cloud
	(*Device)(nil),                      // 16: ocsf.v1.Device
	(*Enrichment)(nil),                  // 17: ocsf.v1.Enrichment
	(*ManagedEntity)(nil),               // 18: ocsf.v1.ManagedEntity
	(*FirewallRule)(nil),                // 19: ocsf.v1.FirewallRule
	(*HttpRequest)(nil),                 // 20: ocsf.v1.HttpRequest
	(*HttpResponse)(nil),                // 21: ocsf.v1.HttpResponse
	(*Malware)(nil),                     // 22: ocsf.v1.Malware
	(*MalwareScanInfo)(nil),             // 23: ocsf.v1.MalwareScanInfo
	(*Metadata)(nil),                    // 24: ocsf.v1.Metadata
	(*Observable)(nil),                  // 25: ocsf.v1.Observable
	(*Osint)(nil),                       // 26: ocsf.v1.Osint
	(*Policy)(nil),                      // 27: ocsf.v1.Policy
	(*Fingerprint)(nil),                 // 28: ocsf.v1.Fingerprint
	(*NetworkEndpoint)(nil),             // 29: ocsf.v1.NetworkEndpoint
	(*structpb.Value)(nil),              // 30: google.protobuf.Value
}
var file_ocsf_v1_entity_management_proto_depIdxs = []int32{
	0,  // 0: ocsf.v1.EntityManagement.action_id:type_name -> ocsf.v1.EntityManagement.ActionId
	1,  // 1: ocsf.v1.EntityManagement.activity_id:type_name -> ocsf.v1.EntityManagement.ActivityId
	11, // 2: ocsf.v1.EntityManagement.actor:type_name -> ocsf.v1.Actor
	12, // 3: ocsf.v1.EntityManagement.api:type_name -> ocsf.v1.Api
	13, // 4: ocsf.v1.EntityManagement.attacks:type_name -> ocsf.v1.Attack
	14, // 5: ocsf.v1.EntityManagement.authorizations:type_name -> ocsf.v1.Authorization
	2,  // 6: ocsf.v1.EntityManagement.category_uid:type_name -> ocsf.v1.EntityManagement.CategoryUid
	3,  // 7: ocsf.v1.EntityManagement.class_uid:type_name -> ocsf.v1.EntityManagement.ClassUid
	15, // 8: ocsf.v1.EntityManagement.cloud:type_name -> ocsf.v1.Cloud
	4,  // 9: ocsf.v1.EntityManagement.confidence_id:type_name -> ocsf.v1.EntityManagement.ConfidenceId
	16, // 10: ocsf.v1.EntityManagement.device:type_name -> ocsf.v1.Device
	5,  // 11: ocsf.v1.EntityManagement.disposition_id:type_name -> ocsf.v1.EntityManagement.DispositionId
	17, // 12: ocsf.v1.EntityManagement.enrichments:type_name -> ocsf.v1.Enrichment
	18, // 13: ocsf.v1.EntityManagement.entity:type_name -> ocsf.v1.ManagedEntity
	18, // 14: ocsf.v1.EntityManagement.entity_result:type_name -> ocsf.v1.ManagedEntity
	19, // 15: ocsf.v1.EntityManagement.firewall_rule:type_name -> ocsf.v1.FirewallRule
	20, // 16: ocsf.v1.EntityManagement.http_request:type_name -> ocsf.v1.HttpRequest
	21, // 17: ocsf.v1.EntityManagement.http_response:type_name -> ocsf.v1.HttpResponse
	22, // 18: ocsf.v1.EntityManagement.malware:type_name -> ocsf.v1.Malware
	23, // 19: ocsf.v1.EntityManagement.malware_scan_info:type_name -> ocsf.v1.MalwareScanInfo
	24, // 20: ocsf.v1.EntityManagement.metadata:type_name -> ocsf.v1.Metadata
	25, // 21: ocsf.v1.EntityManagement.observables:type_name -> ocsf.v1.Observable
	26, // 22: ocsf.v1.EntityManagement.osint:type_name -> ocsf.v1.Osint
	27, // 23: ocsf.v1.EntityManagement.policy:type_name -> ocsf.v1.Policy
	28, // 24: ocsf.v1.EntityManagement.raw_data_hash:type_name -> ocsf.v1.Fingerprint
	6,  // 25: ocsf.v1.EntityManagement.risk_level_id:type_name -> ocsf.v1.EntityManagement.RiskLevelId
	7,  // 26: ocsf.v1.EntityManagement.severity_id:type_name -> ocsf.v1.EntityManagement.SeverityId
	29, // 27: ocsf.v1.EntityManagement.src_endpoint:type_name -> ocsf.v1.NetworkEndpoint
	8,  // 28: ocsf.v1.EntityManagement.status_id:type_name -> ocsf.v1.EntityManagement.StatusId
	9,  // 29: ocsf.v1.EntityManagement.type_uid:type_name -> ocsf.v1.EntityManagement.TypeUid
	30, // 30: ocsf.v1.EntityManagement.unmapped:type_name -> google.protobuf.Value
	31, // [31:31] is the sub-list for method output_type
	31, // [31:31] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_ocsf_v1_entity_management_proto_init() }
func file_ocsf_v1_entity_management_proto_init() {
	if File_ocsf_v1_entity_management_proto != nil {
		return
	}
	file_ocsf_v1_objects_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ocsf_v1_entity_management_proto_rawDesc), len(file_ocsf_v1_entity_management_proto_rawDesc)),
			NumEnums:      10,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ocsf_v1_entity_management_proto_goTypes,
		DependencyIndexes: file_ocsf_v1_entity_management_proto_depIdxs,
		EnumInfos:         file_ocsf_v1_entity_management_proto_enumTypes,
		MessageInfos:      file_ocsf_v1_entity_management_proto_msgTypes,
	}.Build()
	File_ocsf_v1_entity_management_proto = out.File
	file_ocsf_v1_entity_management_proto_goTypes = nil
	file_ocsf_v1_entity_management_proto_depIdxs = nil
}
