version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - cyclop
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  settings:
    cyclop:
      max-complexity: 16
    errorlint:
      errorf: false
    exhaustive:
      default-signifies-exhaustive: true
    gocognit:
      min-complexity: 30
    gocritic:
      disabled-checks:
        - evalOrder
        - importShadow
        - hugeParam
        - rangeValCopy
        - typeDefFirst
        - paramTypeCombine
        - unnamedResult
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 30
    gosec:
      excludes:
        - G104
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    revive:
      confidence: 0.7
      severity: warning
      enable-all-rules: true
      rules:
        - name: redundant-import-alias
          disabled: true
        - name: add-constant
          disabled: true
        - name: argument-limit
          disabled: true
        - name: banned-characters
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: file-header
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: function-length
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: modifies-parameter
          disabled: true
        - name: nested-structs
          disabled: true
        - name: package-comments
          disabled: true
        - name: redefines-builtin-id
          disabled: true
        - name: unhandled-error
          disabled: true
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - bodyclose
          - goconst
          - gosec
          - staticcheck
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/redpanda-data/common-go)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
