// protoc-gen-go-sr generates self-contained Schema Registry proto schemas
// and emits them as Go string constants.
//
// Messages annotated with (redpanda.api.common.v1.schema_registry) get a
// generated Go file containing the schema string and subject name. The target
// message is always at index 0 in the generated proto.
package main

import (
	"fmt"
	"sort"
	"strings"

	commonv1 "buf.build/gen/go/redpandadata/common/protocolbuffers/go/redpanda/api/common/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
)

func main() {
	protogen.Options{}.Run(func(p *protogen.Plugin) error {
		for _, f := range p.Files {
			if !f.Generate {
				continue
			}
			if err := generateFile(p, f); err != nil {
				return err
			}
		}
		return nil
	})
}

type target struct {
	msg     *protogen.Message
	subject string
}

func generateFile(p *protogen.Plugin, file *protogen.File) error {
	var targets []target
	for _, msg := range file.Messages {
		subject, ok := getSROptions(msg)
		if !ok {
			continue
		}
		targets = append(targets, target{msg: msg, subject: subject})
	}
	if len(targets) == 0 {
		return nil
	}

	filename := file.GeneratedFilenamePrefix + "_sr.go"
	g := p.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-sr. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	for _, t := range targets {
		schema, err := renderSelfContainedProto(file, t.msg)
		if err != nil {
			return fmt.Errorf("render schema for %s: %w", t.msg.Desc.Name(), err)
		}

		constPrefix := string(t.msg.Desc.Name())
		g.P("// ", constPrefix, "SRSchema is a self-contained proto for Schema Registry.")
		g.P("// The target message is at index 0.")
		g.P("const ", constPrefix, "SRSchema = `", schema, "`")
		g.P()
		g.P("// ", constPrefix, "SRSubject is the Schema Registry subject name.")
		g.P("const ", constPrefix, "SRSubject = ", fmt.Sprintf("%q", t.subject))
		g.P()
	}

	return nil
}

// renderSelfContainedProto generates a minimal .proto string with the target
// message at index 0, followed by its transitive dependencies (enums, messages).
// Services, RPC methods, and validation annotations are stripped.
// Well-known imports (google/protobuf/*) are kept as import statements.
func renderSelfContainedProto(file *protogen.File, target *protogen.Message) (string, error) {
	var b strings.Builder

	// Collect all transitive dependencies.
	deps := &depCollector{
		msgs:  make(map[protoreflect.FullName]*protogen.Message),
		enums: make(map[protoreflect.FullName]*protogen.Enum),
		file:  file,
	}
	deps.walkMessage(target)

	// Collect required well-known imports.
	imports := deps.wellKnownImports()

	b.WriteString("// Generated by protoc-gen-go-sr. DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("syntax = %q;\n", "proto3"))
	b.WriteString(fmt.Sprintf("package %s;\n", file.Desc.Package()))

	for _, imp := range imports {
		b.WriteString(fmt.Sprintf("import %q;\n", imp))
	}
	b.WriteString("\n")

	// Target message first (index 0).
	renderMessage(&b, target, "")

	// Dependent messages (excluding target).
	for _, msg := range deps.orderedMessages() {
		if msg.Desc.FullName() == target.Desc.FullName() {
			continue
		}
		renderMessage(&b, msg, "")
	}

	// Dependent enums.
	for _, enum := range deps.orderedEnums() {
		renderEnum(&b, enum, "")
	}

	return b.String(), nil
}

// depCollector walks proto descriptors and collects transitive dependencies.
type depCollector struct {
	msgs  map[protoreflect.FullName]*protogen.Message
	enums map[protoreflect.FullName]*protogen.Enum
	file  *protogen.File
}

func (d *depCollector) walkMessage(msg *protogen.Message) {
	if _, seen := d.msgs[msg.Desc.FullName()]; seen {
		return
	}
	d.msgs[msg.Desc.FullName()] = msg

	for _, field := range msg.Fields {
		if field.Enum != nil {
			d.enums[field.Enum.Desc.FullName()] = field.Enum
		}
		if field.Message != nil {
			// Skip well-known types (they stay as imports).
			if isWellKnown(field.Message.Desc.FullName()) {
				continue
			}
			// Skip map entry messages -- they're rendered inline.
			if field.Message.Desc.IsMapEntry() {
				// But walk the map value's dependencies.
				for _, mf := range field.Message.Fields {
					if mf.Enum != nil {
						d.enums[mf.Enum.Desc.FullName()] = mf.Enum
					}
					if mf.Message != nil && !isWellKnown(mf.Message.Desc.FullName()) {
						d.walkMessage(mf.Message)
					}
				}
				continue
			}
			d.walkMessage(field.Message)
		}
	}
}

func (d *depCollector) wellKnownImports() []string {
	seen := make(map[string]bool)
	var imports []string

	var check func(msg *protogen.Message)
	check = func(msg *protogen.Message) {
		for _, field := range msg.Fields {
			if field.Message != nil && isWellKnown(field.Message.Desc.FullName()) {
				path := field.Message.Desc.ParentFile().Path()
				if !seen[path] {
					seen[path] = true
					imports = append(imports, path)
				}
			}
			if field.Message != nil && !field.Message.Desc.IsMapEntry() && !isWellKnown(field.Message.Desc.FullName()) {
				check(field.Message)
			}
		}
	}

	for _, msg := range d.msgs {
		check(msg)
	}

	sort.Strings(imports)
	return imports
}

func (d *depCollector) orderedMessages() []*protogen.Message {
	var out []*protogen.Message
	for _, msg := range d.msgs {
		out = append(out, msg)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Desc.FullName() < out[j].Desc.FullName()
	})
	return out
}

func (d *depCollector) orderedEnums() []*protogen.Enum {
	var out []*protogen.Enum
	for _, enum := range d.enums {
		out = append(out, enum)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].Desc.FullName() < out[j].Desc.FullName()
	})
	return out
}

func isWellKnown(name protoreflect.FullName) bool {
	return strings.HasPrefix(string(name), "google.protobuf.")
}

// renderMessage writes a message definition to the builder.
func renderMessage(b *strings.Builder, msg *protogen.Message, indent string) {
	b.WriteString(fmt.Sprintf("%smessage %s {\n", indent, msg.Desc.Name()))

	// Render oneofs declarations first (fields reference them by index).
	oneofRendered := make(map[string]bool)

	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			name := string(field.Oneof.Desc.Name())
			if oneofRendered[name] {
				continue
			}
			oneofRendered[name] = true
			b.WriteString(fmt.Sprintf("%s  oneof %s {\n", indent, name))
			for _, of := range field.Oneof.Fields {
				b.WriteString(fmt.Sprintf("%s    %s %s = %d;\n", indent, fieldTypeName(of), of.Desc.Name(), of.Desc.Number()))
			}
			b.WriteString(fmt.Sprintf("%s  }\n", indent))
		}
	}

	// Reserved fields.
	reservations := msg.Desc.ReservedRanges()
	for i := 0; i < reservations.Len(); i++ {
		r := reservations.Get(i)
		if r[0]+1 == r[1] {
			b.WriteString(fmt.Sprintf("%s  reserved %d;\n", indent, r[0]))
		} else {
			b.WriteString(fmt.Sprintf("%s  reserved %d to %d;\n", indent, r[0], r[1]-1))
		}
	}

	// Regular fields (skip oneof members, already rendered).
	for _, field := range msg.Fields {
		if field.Oneof != nil && !field.Oneof.Desc.IsSynthetic() {
			continue
		}
		if field.Desc.IsMap() {
			keyType := fieldTypeName(field.Message.Fields[0])
			valType := fieldTypeName(field.Message.Fields[1])
			b.WriteString(fmt.Sprintf("%s  map<%s, %s> %s = %d;\n", indent, keyType, valType, field.Desc.Name(), field.Desc.Number()))
			continue
		}
		repeated := ""
		if field.Desc.IsList() {
			repeated = "repeated "
		}
		optional := ""
		if field.Desc.HasOptionalKeyword() {
			optional = "optional "
		}
		b.WriteString(fmt.Sprintf("%s  %s%s%s %s = %d;\n", indent, optional, repeated, fieldTypeName(field), field.Desc.Name(), field.Desc.Number()))
	}

	// Nested messages (non-map-entry).
	for _, nested := range msg.Messages {
		if nested.Desc.IsMapEntry() {
			continue
		}
		renderMessage(b, nested, indent+"  ")
	}

	// Nested enums.
	for _, enum := range msg.Enums {
		renderEnum(b, enum, indent+"  ")
	}

	b.WriteString(fmt.Sprintf("%s}\n\n", indent))
}

func renderEnum(b *strings.Builder, enum *protogen.Enum, indent string) {
	b.WriteString(fmt.Sprintf("%senum %s {\n", indent, enum.Desc.Name()))
	for _, val := range enum.Values {
		b.WriteString(fmt.Sprintf("%s  %s = %d;\n", indent, val.Desc.Name(), val.Desc.Number()))
	}
	b.WriteString(fmt.Sprintf("%s}\n\n", indent))
}

// fieldTypeName returns the proto type name for a field.
func fieldTypeName(field *protogen.Field) string {
	if field.Enum != nil {
		return relativeName(field.Enum.Desc.FullName(), field.Desc.Parent().(protoreflect.MessageDescriptor).FullName())
	}
	if field.Message != nil {
		return relativeName(field.Message.Desc.FullName(), field.Desc.Parent().(protoreflect.MessageDescriptor).FullName())
	}
	return field.Desc.Kind().String()
}

// relativeName returns a type name relative to the parent scope.
// If both are in the same package, returns just the local name.
func relativeName(target, parent protoreflect.FullName) string {
	// Strip shared package prefix.
	targetParts := strings.Split(string(target), ".")
	parentParts := strings.Split(string(parent), ".")

	// Find common prefix length (package parts).
	common := 0
	for i := 0; i < len(targetParts)-1 && i < len(parentParts)-1; i++ {
		if targetParts[i] == parentParts[i] {
			common = i + 1
		} else {
			break
		}
	}

	return strings.Join(targetParts[common:], ".")
}

func getSROptions(msg *protogen.Message) (subject string, ok bool) {
	opts, _ := msg.Desc.Options().(*descriptorpb.MessageOptions)
	if opts == nil {
		return "", false
	}
	if !proto.HasExtension(opts, commonv1.E_SchemaRegistry) {
		return "", false
	}
	sr := proto.GetExtension(opts, commonv1.E_SchemaRegistry).(*commonv1.SchemaRegistryOptions)
	return sr.GetSubject(), true
}
