// Code generated by controller-gen. DO NOT EDIT.

package v1

// ExampleStatusApplyConfiguration represents a declarative configuration of the ExampleStatus type for use
// with apply.
//
// ExampleStatus is the status for an example
type ExampleStatusApplyConfiguration struct {
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`
}

// ExampleStatusApplyConfiguration constructs a declarative configuration of the ExampleStatus type for use with
// apply.
func ExampleStatus() *ExampleStatusApplyConfiguration {
	return &ExampleStatusApplyConfiguration{}
}

// WithObservedGeneration sets the ObservedGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedGeneration field is set to the value of the last call.
func (b *ExampleStatusApplyConfiguration) WithObservedGeneration(value int64) *ExampleStatusApplyConfiguration {
	b.ObservedGeneration = &value
	return b
}
