// Copyright 2026 Redpanda Data, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"

	resources "github.com/redpanda-data/common-go/kube/example/api/resources"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterRef)(nil), (*resources.ClusterRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_ClusterRef_To_resources_ClusterRef(a.(*ClusterRef), b.(*resources.ClusterRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*resources.ClusterRef)(nil), (*ClusterRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_resources_ClusterRef_To_v1_ClusterRef(a.(*resources.ClusterRef), b.(*ClusterRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Virtual)(nil), (*resources.Virtual)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Virtual_To_resources_Virtual(a.(*Virtual), b.(*resources.Virtual), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*resources.Virtual)(nil), (*Virtual)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_resources_Virtual_To_v1_Virtual(a.(*resources.Virtual), b.(*Virtual), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualList)(nil), (*resources.VirtualList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VirtualList_To_resources_VirtualList(a.(*VirtualList), b.(*resources.VirtualList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*resources.VirtualList)(nil), (*VirtualList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_resources_VirtualList_To_v1_VirtualList(a.(*resources.VirtualList), b.(*VirtualList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualSpec)(nil), (*resources.VirtualSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VirtualSpec_To_resources_VirtualSpec(a.(*VirtualSpec), b.(*resources.VirtualSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*resources.VirtualSpec)(nil), (*VirtualSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_resources_VirtualSpec_To_v1_VirtualSpec(a.(*resources.VirtualSpec), b.(*VirtualSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VirtualStatus)(nil), (*resources.VirtualStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_VirtualStatus_To_resources_VirtualStatus(a.(*VirtualStatus), b.(*resources.VirtualStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*resources.VirtualStatus)(nil), (*VirtualStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_resources_VirtualStatus_To_v1_VirtualStatus(a.(*resources.VirtualStatus), b.(*VirtualStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_ClusterRef_To_resources_ClusterRef(in *ClusterRef, out *resources.ClusterRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_v1_ClusterRef_To_resources_ClusterRef is an autogenerated conversion function.
func Convert_v1_ClusterRef_To_resources_ClusterRef(in *ClusterRef, out *resources.ClusterRef, s conversion.Scope) error {
	return autoConvert_v1_ClusterRef_To_resources_ClusterRef(in, out, s)
}

func autoConvert_resources_ClusterRef_To_v1_ClusterRef(in *resources.ClusterRef, out *ClusterRef, s conversion.Scope) error {
	out.Name = in.Name
	return nil
}

// Convert_resources_ClusterRef_To_v1_ClusterRef is an autogenerated conversion function.
func Convert_resources_ClusterRef_To_v1_ClusterRef(in *resources.ClusterRef, out *ClusterRef, s conversion.Scope) error {
	return autoConvert_resources_ClusterRef_To_v1_ClusterRef(in, out, s)
}

func autoConvert_v1_Virtual_To_resources_Virtual(in *Virtual, out *resources.Virtual, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_VirtualSpec_To_resources_VirtualSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1_VirtualStatus_To_resources_VirtualStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_Virtual_To_resources_Virtual is an autogenerated conversion function.
func Convert_v1_Virtual_To_resources_Virtual(in *Virtual, out *resources.Virtual, s conversion.Scope) error {
	return autoConvert_v1_Virtual_To_resources_Virtual(in, out, s)
}

func autoConvert_resources_Virtual_To_v1_Virtual(in *resources.Virtual, out *Virtual, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_resources_VirtualSpec_To_v1_VirtualSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_resources_VirtualStatus_To_v1_VirtualStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_resources_Virtual_To_v1_Virtual is an autogenerated conversion function.
func Convert_resources_Virtual_To_v1_Virtual(in *resources.Virtual, out *Virtual, s conversion.Scope) error {
	return autoConvert_resources_Virtual_To_v1_Virtual(in, out, s)
}

func autoConvert_v1_VirtualList_To_resources_VirtualList(in *VirtualList, out *resources.VirtualList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]resources.Virtual)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_VirtualList_To_resources_VirtualList is an autogenerated conversion function.
func Convert_v1_VirtualList_To_resources_VirtualList(in *VirtualList, out *resources.VirtualList, s conversion.Scope) error {
	return autoConvert_v1_VirtualList_To_resources_VirtualList(in, out, s)
}

func autoConvert_resources_VirtualList_To_v1_VirtualList(in *resources.VirtualList, out *VirtualList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Virtual)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_resources_VirtualList_To_v1_VirtualList is an autogenerated conversion function.
func Convert_resources_VirtualList_To_v1_VirtualList(in *resources.VirtualList, out *VirtualList, s conversion.Scope) error {
	return autoConvert_resources_VirtualList_To_v1_VirtualList(in, out, s)
}

func autoConvert_v1_VirtualSpec_To_resources_VirtualSpec(in *VirtualSpec, out *resources.VirtualSpec, s conversion.Scope) error {
	if err := Convert_v1_ClusterRef_To_resources_ClusterRef(&in.ClusterRef, &out.ClusterRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_VirtualSpec_To_resources_VirtualSpec is an autogenerated conversion function.
func Convert_v1_VirtualSpec_To_resources_VirtualSpec(in *VirtualSpec, out *resources.VirtualSpec, s conversion.Scope) error {
	return autoConvert_v1_VirtualSpec_To_resources_VirtualSpec(in, out, s)
}

func autoConvert_resources_VirtualSpec_To_v1_VirtualSpec(in *resources.VirtualSpec, out *VirtualSpec, s conversion.Scope) error {
	if err := Convert_resources_ClusterRef_To_v1_ClusterRef(&in.ClusterRef, &out.ClusterRef, s); err != nil {
		return err
	}
	return nil
}

// Convert_resources_VirtualSpec_To_v1_VirtualSpec is an autogenerated conversion function.
func Convert_resources_VirtualSpec_To_v1_VirtualSpec(in *resources.VirtualSpec, out *VirtualSpec, s conversion.Scope) error {
	return autoConvert_resources_VirtualSpec_To_v1_VirtualSpec(in, out, s)
}

func autoConvert_v1_VirtualStatus_To_resources_VirtualStatus(in *VirtualStatus, out *resources.VirtualStatus, s conversion.Scope) error {
	out.Linked = in.Linked
	return nil
}

// Convert_v1_VirtualStatus_To_resources_VirtualStatus is an autogenerated conversion function.
func Convert_v1_VirtualStatus_To_resources_VirtualStatus(in *VirtualStatus, out *resources.VirtualStatus, s conversion.Scope) error {
	return autoConvert_v1_VirtualStatus_To_resources_VirtualStatus(in, out, s)
}

func autoConvert_resources_VirtualStatus_To_v1_VirtualStatus(in *resources.VirtualStatus, out *VirtualStatus, s conversion.Scope) error {
	out.Linked = in.Linked
	return nil
}

// Convert_resources_VirtualStatus_To_v1_VirtualStatus is an autogenerated conversion function.
func Convert_resources_VirtualStatus_To_v1_VirtualStatus(in *resources.VirtualStatus, out *VirtualStatus, s conversion.Scope) error {
	return autoConvert_resources_VirtualStatus_To_v1_VirtualStatus(in, out, s)
}
